### ISSUE TITLE
Loads should not be applied to a floor if floor is an air wall (Bugzilla #671)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#110]
On 2012-04-24 09:16:00, @macumber wrote nothing.

On 2012-05-10 14:52:29, @DavidGoldwasser wrote:

> Created an attachment (id=169)
> Made a test model to confirm this bug. Attached for future use

On 2012-05-10 16:42:45, @DavidGoldwasser wrote:

> <batch change - re-validated with OpenStudio 0.7.3>

On 2012-09-10 08:16:35, @DavidGoldwasser wrote:

> <changed status of bugs in Pivotal to Assigned>

Original attachments:
* bug671_TestModel.osm (ID 169)

Keywords: BadSimResults, EdgeCase

**Comment by DavidGoldwasser** [comment]
I know this has been discussed but I can't remember what has been done. Before this is closed we should build some test cases for it. The susurration I'm most concerned about is when stacked spaces don't have an air wall. OpenStudio will report on floor area, and EnergyPlus another. They might have to be this way, but we should make sure the internal load values are based on the large OpenStudio floor area. Or if nothing else give a warning to the user to alert them of this in pre-flight decks. I'll flag this as a feature, and move it to minimal (because there is a workaround) but it still important because it can produce unexpected results and users may not be aware of the issue.

**Comment by DavidGoldwasser** [comment]
issue #561 which is an open feature request covers this
