### ISSUE TITLE
Radiance Parameters are reset to Coarse every time the osm is loaded

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#1135]

**Comment by rpg777** [comment]
The Radiance simulation settings get __reset__ to "coarse" every time you visit the Simulation Settings tab, even if you don't expand the Radiance Sim settings triangle thingy.(!) If the user sets the Rad settings to fine or custom, and then goes straight to the run tab, the user-selected settings are used. But if the user revisits the Simulation Settings tab for any reason, the Radiance settings are reset to "coarse".  
(Tested with 1.7.0)

**Comment by macumber** [comment]
@rpg777 looks like this was always this way but it used to get reset only when you started the app, now it gets reset every time you switch to the sim settings tab (due to the one tab in memory refactor):

https://github.com/NREL/OpenStudio/blame/develop/openstudiocore/src/openstudio_lib/SimSettingsView.cpp#L945

@evanweaver I thought there was more logic around detecting if the user had coarse, fine, or custom radiance parameters.  Do you remember what happened to that logic?  I'm guessing it was removed due to bugs?  Here is a link to the archive version:

https://github.com/NREL/OpenStudio-archive/blame/master/openstudiocore/src/openstudio_lib/SimSettingsView.cpp#L964

**Comment by macumber** [comment]
Raised to major severity due to changing user model without warning

**Comment by macumber** [comment]
I believe a simple fix would be to only create a RadianceParameters and set these options if the users model did not already have one

https://github.com/NREL/OpenStudio/blame/develop/openstudiocore/src/openstudio_lib/SimSettingsView.cpp#L1570

**Comment by rpg777** [comment]
So, two questions then: 
1. Is this something that we are trying to push into the 1.7.0. RC?
2. If so can I add a parameter to this set (it doesn't have to be displayed in the GUI for now)

**Comment by macumber** [comment]
Send me your parameter, I'll make a commit and let @axelstudios decide if he can handle the bandwidth of remaking packages

**Comment by macumber** [comment]
This https://github.com/NREL/OpenStudio/commit/d03ac678501af30a4df573673fcf8490eecb7f0a fixes the settings getting whacked each time the tab reloads

However, the radio button state is not maintained correctly after the one tab in memory change so I think we should keep the issue open

**Comment by macumber** [comment]
@evanweaver my suggestion is to move the coarse, medium, and fine radiance parameters into the object.  Then we just have applyCoarseSettings and isCoarseSettings methods for the GUI to use, we can call applyCoarseSettings in the object ctor. 

We also need to fix this at the same time:
https://github.com/NREL/OpenStudio/issues/1549

**Comment by evanweaver** [comment]
We will still need to address #1549.

**Comment by evanweaver** [comment]
Previously fixed, closed in Pivotal, but not in GitHub.  See https://www.pivotaltracker.com/n/projects/134010/stories/101286556
