### ISSUE TITLE
Fix volume calculation to match EnergyPlus (Bugzilla #730)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#127]
On 2012-06-08 14:19:09, @DavidGoldwasser wrote:

> Just wanted to file this before I forgot about it. Current method will have problem with spaces that have sloped walls or ceilings.

On 2012-09-09 23:24:43, @DavidGoldwasser wrote:

> I added BadSimResults but that would be an edge case where walls or roofs are not vertical.

On 2012-12-17 13:42:44, @DavidGoldwasser wrote:

> This was inadvertently under C#

Keywords: BadSimResults

**Comment by DavidGoldwasser** [comment]
@macumber I'll keep this open, but I know it is more of a feature than a bug, but it can be important for proper calculation of some internal load values on forward translation of complex geometry.

**Comment by agonzalezesteve** [comment]
I propose using the divergence theorem to compute the space volume, instead of multiplying the space area by a "mean" space height.
![image](https://user-images.githubusercontent.com/38532229/39042198-89e2f86e-448a-11e8-9afb-04f47bf9f674.png)
Then, using that every surface belongs to a plane, whose normal is parallel to its coefficients a, b and c;
![image](https://user-images.githubusercontent.com/38532229/39042288-b9944770-448a-11e8-9fa3-f9782df3947a.png)
only a constant integral is needed in every surface of the space.
![image](https://user-images.githubusercontent.com/38532229/39042362-e27e2034-448a-11e8-8453-52c764eab314.png)
Then, the volume integral reduces to
![image](https://user-images.githubusercontent.com/38532229/39042456-2891eb00-448b-11e8-8aaf-37661a4adaf0.png)
where d_i is the d coefficent of the plane where the i-th surface belongs and A_i is the area of the i-th surface.

I've tested it using this ruby code.
![image](https://user-images.githubusercontent.com/38532229/39042540-5e6ecc34-448b-11e8-84aa-fb9d3adf4804.png)

**Comment by eringold** [comment]
@agonzalezesteve thank you, this is awesome. 

I just tested the following single space geometry: 
![image](https://user-images.githubusercontent.com/10799524/39071790-9a1af36a-44a5-11e8-9c28-0fb74ff1fad2.png)

By hand, I calculate the volume at 17.6642 m^3 (measuring from sketchup in ft/in and converting ft^3 to m^3 in excel)
The default `space.volume` method for this space returns 19.0972 m^3
Your method returns 17.5825 m^3.
I'd say that's an improvement!

I've had many problems with OpenStudio geometry from sketchup ending up with EnergyPlus 'volume not enclosed' errors, to the point where I've taken to hard-assigning zone volume from a script. For complex spaces, I've had to hand-calc the volumes. I think this method is a huge improvement, and the dev team might consider implementing it to set zone volume at forward translation to avoid problems that EnergyPlus has calculating non-enclosed zone volumes with tiny surface gaps.

**Comment by macumber** [comment]
The divergence calculation does not work for volumes which are not fully enclosed, I didn't implement it for OpenStudio because we don't have a check that the volumes are fully enclosed (no gaps or overlapping surfaces).  I agree that it is best to match E+, I have been holding out for a solution where OS and E+ *share* code for calculations like this.  That way we can make sure we are using the best available algorithms.

**Comment by eringold** [comment]
@macumber ok maybe not implement it in OS by default, but the above algorithm is still better than zone volumes being set to 10 m^3 when E+ detects an edge that's not shared by two surfaces due to tiny gaps from sketchup. It will "work", just not "totally correctly" 😄

**Comment by macumber** [comment]
I'm not really following @eringold, it sounds like you are having problems with the EnergyPlus calculation which fails due to tiny gaps (which invalidate the divergence calculation).  Is that right? Is your problem with the OS calculation or the E+ one?

**Comment by agonzalezesteve** [comment]
@macumber in which cases the geometry is not fully enclosed?

It is true that the divergence calculation doesn't work with unenclosed spaces, but the actual method neither if there is no floor or roof.

Furthermore, the actual method is a product of a "mean" height times the floor area, that in complex geometries this simplification fails.

In short, the current and the proposed methods for volume computation don't work with unenclosed volumes but the divergence method is more accurate in complex geometries.

**Comment by macumber** [comment]
First of all, thank you @agonzalezesteve for this conversation, it is great to have you contributing here!

I don't know all the cases that geometry isn't fully enclosed.  Thank you very much for your suggestion, I agree with your evaluation of the two approaches, the only thing I am unsure about is the robustness of both approaches.  I was under the impression that you could get wildy wrong volumes from the divergence routine if you were missing a wall or something like that so the current routine is more robust to failure, I could be wrong here.  In the end I suspect that a hybrid routine (e.g. use divergence if fully enclosed, issue warning and use some other method if not) would be best suited here.  My hope was to implement this hybrid routine in a shared library used by both OpenStudio and EnergyPlus, I still think this is possible.

Currently OpenStudio does not hard set volume on translation to E+ so I don't think OpenStudio's current volume method affects most users.  Am I missing some case where OpenStudio's volume calculation is commonly invoked?  If a user wants to hard set volume in a measure then I think it is good for them to be able to choose between methods.  I don't have a strong opinion on which one should be the default so my preference is to keep the current algorithm for now and point users to your snippet if they want to try that approach.

**Comment by agonzalezesteve** [comment]
@macumber thank you for the welcome!

You are right, the divergence method fails if one wall is missing and the current method is more robust in these cases.

I just tried to find a new volume algorithm because the current method gave me wrong values of air change per hour in spaces with complex geometry, like staircases inside buildings.

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/blob/a007b7801e3bb05731f012f585facdd814ef31fb/src/model/Space.cpp#L887-L916

**Comment by jmarrec** [comment]
The corresponding entry point for E+ calculation is around here: https://github.com/NREL/EnergyPlus/blob/29b5decc089394689a97932f66fa64d5a2fac062/src/EnergyPlus/SurfaceGeometry.cc#L11506-L11534

**Comment by wassimj** [comment]
This has not been fixed since 2013! I tried the workaround osThermalZone.setVolume but, while this fixes it for the .OSM file, it does not fix it for the .gbxml output which continues to calculate the wrong volume for more complex shapes (mainly slanted hip roofs etc).

**Comment by jmarrec** [comment]
I have implemented a fix for this long overdue issue in #4592, would appreciate a review from anyone interested
