### ISSUE TITLE
SPM Mixed Air Magic Fails on AirLoops with Unitary Equipment

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1357]
If you have an AirLoop with a piece of unitary equipment on it, and you also have other components (like an ERV) that require SPM Mixed Airs to operate on that same AirLoop, the magic doesn't happen.
Here is the model before:
![beforefancymagic](https://cloud.githubusercontent.com/assets/2009290/5888349/b657f848-a3b8-11e4-8866-273c6d839f7f.PNG)
Here is the model after the fancy magic:
![afterfancymagic](https://cloud.githubusercontent.com/assets/2009290/5888348/b657bc5c-a3b8-11e4-8845-9e613800271c.PNG)
Here is a [link to the model](https://www.dropbox.com/s/z9wtd7opsn6jqgc/spm_magic_fails.osm?dl=0)

Here is my guess on a fix:
1. Add the `updateFanInletOutletNodes` method to the Unitary `.addToNode` method.
2. Update the `updateFanInletOutletNodes` to look for fans inside of unitary systems.

I'm not quite sure whether the appropriate nodes are the ones outside of the Unitary or inside of the unitary.

This might be a good time to add methods for `.supplyFan`, `returnFan`, and `reliefFan` to AirLoopHVAC, and have those methods also retrieve the fans inside of Unitary equipment.

I noticed this while working on the PTool analysis, which is why it is higher priority.

**Comment by asparke2** [comment]
It is worse than I thought.  In addition to not adding the SPM MA properly, something in the ForwardTranslator is messing up SPM MAs that you put there manually (which I was trying as a workaround in my Measure).

The left side shows the .osm before ModelToIdf, the right side shows the .idf after ModelToIDF.  Notice that the Fan Inlet Node and Fan Outlet Node fields for some SPM MAs were cleared on translation.

![spm fwd trans](https://cloud.githubusercontent.com/assets/2009290/5888605/5aabf980-a3c3-11e4-9d2d-d0ce564a94a2.PNG)

**Comment by kbenne** [comment]
@asparke2 

"This might be a good time to add methods for .supplyFan, returnFan, and reliefFan to AirLoopHVAC, and have those methods also retrieve the fans inside of Unitary equipment."

Yes.  Will do.

"It is worse than I thought. In addition to not adding the SPM MA properly, something in the ForwardTranslator is messing up SPM MAs that you put there manually (which I was trying as a workaround in my Measure)."

Yes.  Bad news.  I will fix that asap.

As for the magic.  I'm inclined to fix it so that it works properly with unitary systems, but I'd like to get you thinking about this...  Say your supply outlet node has a single zone reset, and your mixed air managers track that.  The unitary is in no way tracking the single zone reset, so you have a situation where the ERV (or whatever) is tracking one supply air temperature, and the unitary a different one.  Probably no big deal, because they are close enough.  I have used this method myself with little concern to the issue.  But note that it is there, and might justify a little more careful thought before we set things up this way by default magic.

I wonder what real systems do.  Probably some kind of scheduled temperature.  Certainly not SPM single zone reset since that is not a real thing.

**Comment by kbenne** [comment]
@asparke2 in your comparison of osm to idf above, it seems as though you might be comparing different SPMs.  Setpoint Manager Mixed Air 1 in the osm vs Setpoint Manager Mixed Air 11 in the idf. Is that possible?

Please clarify which magic you are expecting here.  There is magic to default the fan inlet and outlet fields when you drop a mixed air SPM in the OS model.  There is separate magic to add a mixed air SPM in the translator if none exists at all.  Neither of these are accounting for fans inside unitary systems, and I expect to fix both issues.

**Comment by kbenne** [comment]
https://github.com/NREL/OpenStudio/pull/1367

**Comment by macumber** [comment]
@asparke2 looks like you accepted in pivotal, can you close here?
