### ISSUE TITLE
Support all fields needed for thermal comfort studies

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1447]

**Comment by aaron-boranian** [comment]
Problem: Thermal comfort studies cannot be fully performed due to lack of access to all fields in the underlying EnergyPlus objects

Solution: Support access to all fields of thermal comfort objects for OpenStudio users

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9097798)

**Comment by jmarrec** [comment]
I think this is outdated, or I'm missing what "all fields of thermal comfort objects" mean.

You can set the People Comfort fields on the loads tabs for SpaceType/Spaces at least, just not the Load Definition tab. See https://github.com/NREL/OpenStudio/issues/2756

**Comment by jmarrec** [comment]
Duplicated #2756
