### ISSUE TITLE
Add Import / Load Library Feature for MEP Schedules

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1473]
This feature could significantly speed up the workflow for consulting, and to my knowledge is not supported in other software. I mentioned this in a conversation with @asparke2, but I thought I'd get the ball rolling and document it. 

My suggestion is to use an Excel-based template that the user could paste a schedule into, reorganize to fit, and then be read by a measure that would add the equipment to the Library, essentially creating a separate project-specific HVAC Library. 

Since [ASHRAE Standard 205](http://spc205.ashraepcs.org/) is a ways off, and no doubt widespread adoption even further, this seems like it would work for schedule formats that are project-specific. I'd be interested in hearing other possible solutions and can provide example schedules if needed.

**Comment by macumber** [comment]
@MatthewSteen what new features are needed in OpenStudio to support this?

**Comment by MatthewSteen** [comment]
@macumber I think the main feature would be populating the Thermal Zones and HVAC Systems tab Libraries with project-specific equipment that could be dragged/dropped in to a model. This could be done through File > Load Library as currently available for schedules, constructions, loads, and space types. 

For example, in a model with ~100 FCUs, these could translated to OSM via Excel/Measure and then loaded into the model as FCUs with the fields already completed. Possible or already in the works?

**Comment by macumber** [comment]
I believe you can load a custom OSM to get new zone equipment/system components in the library, @kbenne or @asparke2 might know for sure

Measures can currently have resource files (e.g. your Excel file) that they can read from at run time (currently we don't have an Excel reader library available for Measures on Mac, that would be an addition) to get data to make calls to the OpenStudio API (e.g. to create equipment, attach to zones, etc)  

I could see one measure to export your model to a spreadsheet and another measure to read in the same spreadsheet and apply it to your model.  That should mostly be available now.

**Comment by eringold** [comment]
@MatthewSteen I've had success with measures that use the [CSV] (http://ruby-doc.org/stdlib-1.9.2/libdoc/csv/rdoc/CSV.html) class to read from a formatted spreadsheet of mechanical schedules to create and assign e.g. zone HVAC objects. The ::foreach method is useful for looping through the CSV rows, and takes a string argument of the file path (I believe OpenStudio supports a Path argument, but a string works fine with ::foreach). You also need to add a `require 'csv'` at the top of your measure file.

**Comment by MatthewSteen** [comment]
Thanks @eringold, do you assign the equipment to the appropriate zone in the measure or have you been able to populate the library with equipment from the MEP schedule to drop into the zone?

Adding project-specific equipment to the`hvac_library.osm` file would be one way to accomplish this, but I think having a separate HVAC library file that's attached to the model would be preferable to altering the built in one (maybe in the `files` folder with the wx file).

**Comment by eringold** [comment]
@MatthewSteen The measure assigns the equipment to the appropriate zone. I haven't considered adding the equipment to a library file. Right now I just have the equipment schedule values mapped to the zone name in the .csv, and the measure loops through the model zones and csv rows, matches the zone name, creates the equipment and assign it to the zone, and sets the equipment parameters from the specific csv column. 

It's still a work in progress for full workflow integration, but the long-term plan is to standardize the arrangement of the spreadsheet so that a measure can create design-case HVAC with one run.

**Comment by MatthewSteen** [comment]
@eringold that's the dream, thanks again for the input.

**Comment by macumber** [comment]
@MatthewSteen if there are no changes needed to OpenStudio to support this feature can we close this issue?

**Comment by MatthewSteen** [comment]
@macumber I was waiting to hear from @asparke2 or @kbenne about their thoughts. I realize that additional hvac components (e.g. FanOnOff) can be added to the shared hvac library. However, to my knowledge loading hvac equipment into a model as can be done with schedules, constructions, and loads is not currently supported.

**Comment by kbenne** [comment]
Currently OpenStudio will only look for hvac_library.osm and there is no way to coerce it into using a different file of your choosing.  So you're forced to edit that file if you want to make custom libraries.  It is a small task to enhance OpenStudio with a user facing option to select a library osm.  

If you want to queue up a feature request along these lines be my guest.  It will probably get picked up and implemented without too much hesitation.  But my ambitions for the library are slightly larger.  The monolithic hvac library file is awful to maintain.  I want to rework it as a directory of component Measures or actual BCL components.  Something more granular and supporting extensibility.

Would your needs be satisfied if I simply enabled the HVAC library to show BCL components and allowed their drag and drop within the GUI?  This is supported for non HVAC stuff now, the drop handling just hasn't been implemented in the HVAC interfaces so we don't show BCL components for HVAC in the library.  You'd end up with two sources of HVAC library material, the hvac_library.osm and any HVAC in your BCL components directory.  In this scenario you could extend the library by creating new BCL Components.  

I promoting this way because it would be useful for other high value use cases involving VRF.  I also think it might be a step in the right direction of deprecating hvac_library.osm altogether.

**Comment by macumber** [comment]
@kbenne What about loading HVAC components in the user's library that they load with File->Load Library?

**Comment by kbenne** [comment]
@macumber essentially tell OS hey don't look at hvac_library.osm look here instead?  What I'm saying is if @MatthewSteen wants that I'm pretty sure it can be delivered with low effort.  It doesn't solve the more systemic maintenance problem but it is a useful feature.

**Comment by macumber** [comment]
@kbenne well it already works for things like constructions, etc.  The user can pick a second OSM to load as their library, I just don't know if HVAC objects in that user library are being merged with the list presented on HVAC tabs.

**Comment by kbenne** [comment]
@macumber I see your point.  I'm not sure.  I was assuming it didn't just work, but I guess it is possible thinking about how that is all put together.

**Comment by MatthewSteen** [comment]
For my use, being able to load HVAC equipment into a model via the File > Load Library menu would be preferable. We already do this for inputs common to both the baseline and proposed models (e.g. schedules). 

Being able to add HVAC equipment for the proposed design with the object fields already completed (e.g. FCU 3-1 serving the 3rd floor corner office) and then simply dropping them into the respective zone would save a lot of time.

**Comment by macumber** [comment]
I think it is just a matter of returning a combined hvac model here'ish:

https://github.com/NREL/OpenStudio/blob/3aaa0984dbc185867261bde6305b141deb118d5e/openstudiocore/src/openstudio_lib/OSDocument.cpp#L1342

Looking at it, I think I see some bugs that need to get fixed though

**Comment by kbenne** [comment]
Not giving me warm fuzzies.

https://github.com/NREL/OpenStudio/blob/3aaa0984dbc185867261bde6305b141deb118d5e/openstudiocore/src/openstudio_lib/OSDocument.cpp#L1335

Looking at this code I'd say its pretty clear it doesn't "just work" but I'm testing just to confirm.

**Comment by MatthewSteen** [comment]
Closing as no longer needed and probably obsolete. This can be accomplished using the API to generate a CSV template of thermal zones and zone HVAC fields, which can be populated with design information from mechanical schedules and then used to create and set inputs for zone-level objects.
