### ISSUE TITLE
registerValue not working with units

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1494]
Reported by @phylroy 

 If you use runner.registerValue(''name','some_string_value', 'some_unit' ) the value turns into the some_unit and not the some_string_value.  The work around is to not use the units optional arg...

**Comment by macumber** [comment]
I wonder if the correct version of the function is getting called?  There are several overloads:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/ruleset/OSRunner.hpp#L136

**Comment by asparke2** [comment]
@phylroy can you reconfirm this issue?

**Comment by jmarrec** [comment]
There's no problem, you're just not calling the right overload. 

https://github.com/jmarrec/OpenStudio/blob/324e645751ebf769d75dbf74090bcb918652d810/openstudiocore/src/measure/OSRunner.hpp#L188:L190

```c++
  virtual void registerValue(const std::string& name,
                             const std::string& displayName,
                             const std::string& value);
```

instead you need to call one of these two (or the equivalent ones with an `int` instead of `double`

```c++
  /** \overload Shortcut method for registering double attribute. */
  virtual void registerValue(const std::string& name, double value, const std::string& units);
  
  /** \overload Shortcut method for registering double attribute. */
  virtual void registerValue(const std::string& name,
                             const std::string& displayName,
                             double value,
                             const std::string& units);
```

**Comment by DavidGoldwasser** [comment]
@jmarrec there used to be a limit where you couldn't add a unit if your value was a string. In my case I had a string what was of integers "1.2, 2.3 ,3.4" I was holding 12 monthly values in one register value. I just wanted to confirm if this was still the case because someone else had a similar use case.
