### ISSUE TITLE
Multi-select - Can't copy terminals, to other zones, but looks like you can

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1544]
@kbenne and @evanweaver I can see the reason for not copying terminals across zones, as they have connections to many other objects. My use case was an air loop with a few zones, I changed one terminal and wanted to apply that change to other terminals on the same loop. Clicking "Apply to Selected" doesn't do anything.

My first thought was should we remove the "Apply to Selected" from the top of the "Zone Equipment" header, but you can for example copy an exhaust fan. Can we have the "Apply to Selected" grayed out just as if nothing is selected, if an invalid object type (for multi-copy) is selected.

I don't see this as something we have to fix now, could be known issue, and then fixed in later release. I expect there may be a few other simulation situations.

![3-20-2015 9-30-51 am](https://cloud.githubusercontent.com/assets/4857055/6754805/7b2ba1f0-cee4-11e4-9e93-f919893064eb.png)

**Comment by kbenne** [comment]
@DavidGoldwasser that is a good use case if you ask me.  But I think you're appreciating the complications of multi edit / cloning terminal.  The work to make any of this happen is not hard.  It is more tricky to define all of the potential scenarios, and design a solution that is not opaque, magical or confusing to a client.  If you narrate a complete description of behaviors (with maybe a little buy in from Marj and Andrew, I will make it happen.  Consider cases like terminal attached to single zone system, terminal attached to multi zone system, and like you say just replacing a terminal.  Im inclined to think we should do nothing with the systems, and only support replacing an existing terminal.  But is even that too much or inconsistent?

**Comment by DavidGoldwasser** [comment]
Thanks @kbenne, I'll loop @asparke2 into this as well. I'll assign you instead of @evanweaver , but it can probably simmer for a while while we get user feedback from everyone. I don't think this is critical. I do think if we make a decision to have it not clone the object, that eventually the model should send a signal back to the GUI to let the use know this is an invalid object for "Apply to Selected". Otherwise the users will keep clicking the button wondering why they are not getting any feedback.

**Comment by kbenne** [comment]
How about this?  When "applying terminal to selected" if the selected zone that you are applying to is attached to an air system, then clone the terminal and attach to the selected zone.  Do this regardless of an existing terminal there or not.  If there is an existing terminal, remove it, then apply the new one.  I think all of this should happen at the App level, no Model implementation of this funkyness because I think it only makes sense in the context of the app's grid.  Thoughts?

**Comment by evanweaver** [comment]
Sounds fine to me.  If this works for you David, I'll be the one to implement the fix.

**Comment by kbenne** [comment]
They key points of my above suggestion is that it acknowledges that zones can be attached to air systems without a terminal in place.  And it avoids the rather extreme step of cloning entire systems, or adding new branches to existing ones.

**Comment by DavidGoldwasser** [comment]
Sounds good to me. I assume then if you try to attach terminal to a zone that isn't on an air loop, it will just do nothing? That is that you don't want terminals hanging out on a zone unless their is an air loop.

**Comment by kbenne** [comment]
@DavidGoldwasser right.

**Comment by evanweaver** [comment]
Kyle, it occurred to me that the Qt event loop is processed differently on Mac / Linux, compared to Windows.  Potentially, we could be facing a race condition with the "Apply to" button sending its clicked signal, and that same button being disabled because the GUI thinks that the work has been done.

**Comment by jmarrec** [comment]
tested that this didn't change yet with 2.7.1.

I actually think we should just close this issue instead of doing some funky business in the OS App. If you want to clone a terminal to other zones, you can in most cases do that by clicking on the AirLoopHVAC splitter and selecting your thermal zones.

But if you insist of having this implement, I could take care of it.

**Comment by DavidGoldwasser** [comment]
I'm fine closing this.
