### ISSUE TITLE
Updates to measure guide

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1572]
Boolean arguments not working?
Return types of getArgument methods
Discuss registerNA

**Comment by macumber** [comment]
Discuss how users can attach a weather file and run OSM for reporting measure, may need to update default reporting measure

**Comment by macumber** [comment]
Show how to use is model dependent flag, @DavidGoldwasser anything else to add?

**Comment by DavidGoldwasser** [comment]
@macumber that sounds good. As far as the weather file, maybe add in some specifics about measure testing for reporting measure. That currently isn't covered under the "Measure Testing" or "Advanced Topics/Reporting Measure", section, but if a new reporting measure made in app is well commented, then maybe we don't need this?

**Comment by DavidGoldwasser** [comment]
@macumber a question came in about using choice arguments from model objects. I gave an example of what I normally do which is using the normal choice object, since I typically want to filter.
https://unmethours.com/question/4501/how-to-make-a-choice-argument-for-all-objects-of-a-certain-type-measure/?answer=4504#post-id-4504

I saw issue #385 is related to this. We could probably expand on the method in the documentation to show our preferred solution. I think showing what has to happen on the run side of things to get the object from the argument is also a good idea.
