### ISSUE TITLE
Consistent Placement of Add/Delete/Copy Buttons

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1581]
It would be more intuitive if the add/delete/copy buttons were placed on a consistent part of the page, and in a consistent relation to each other. See example screenshots below.

![lump controls 3](https://cloud.githubusercontent.com/assets/6117383/7054185/dc650960-de08-11e4-8efe-ed12dae04b78.png)
![lump controls 2](https://cloud.githubusercontent.com/assets/6117383/7054186/dc6543f8-de08-11e4-896d-54c38aae5a15.png)
![lump controls 1](https://cloud.githubusercontent.com/assets/6117383/7054187/dc720070-de08-11e4-8e8c-60b26542bf72.png)

**Comment by evanweaver** [comment]
@dstuder your middle image, the grid view, is by Marj's design.

**Comment by dstuder** [comment]
@evanweaver I don't think it matters what the final design is, but I think that it is important to keep it consistent across tabs. I see that the dark gray bar is present at the bottom of the viewing pane in the grid view tab, but is truncated in the Loads tab and placed at the top of the viewing pane in the HVAC Systems tab. I guess my comment really should extend to this background pane as well, and I would advocate for this to be placed consistently. Seems like design wise that it could easily be moved to the bottom of the HVAC Systems tab and also extended to the right on the Loads tab. Not sure what level of effort is required to actually implement that though.

**Comment by marj-schott** [comment]
The bar with the buttons goes under the area where it provides actions. In the third example the buttons do not effect the center panel and should not be shown under that panel. In the second the buttons do effect the central panel and so should go across the as they do. We can move the trash button over to the right more like the 3rd image if that makes more sense.

HVAC is a different story and is the way it is because it started as another application and does have some differences from the rest of the application. We have talked about working on that top bar of buttons but have not had the time to do that yet.

**Comment by dstuder** [comment]
@marj-schott That logic makes sense. I do think it would be a little easier to use if the trash button was scooted over to the left (in the 2nd image) much like it is in the 3rd. Thanks for the info!
