### ISSUE TITLE
Grid View Column Width Sizing

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1587]
It appears to me that the column widths in grid view mode are autosizing to fill the entire width of the viewing pane. However, in certain views, this autosizing behavior causes the units in the right-most column to be cutoff from view and necessitates use of a horizontal scroll bar. Is there a way to tweak the logic so that this does not happen? The image below shows this cutoff occurring for the "Cooling Minimum Air Flow" column.

![image](https://cloud.githubusercontent.com/assets/6117383/7068701/2c2c9b2c-dea2-11e4-91b3-608ad2e176ef.png)

**Comment by marj-schott** [comment]
@kbenne and @evanweaver you two would know how this is set up and could address this better than me. I am not able to reproduce this. It looks like it is not set to fit until you exceed some panel width and I am not seeing the units get cut off when it autosizes. I am on a Mac if that makes any difference.

**Comment by evanweaver** [comment]
There is a minimum column width that Qt has dynamically determined.  If we try to modify it, we are likely going to introduce other undesirable behaviors (obviously, Qt has spent considerable time tring to make their sizing work well on all operating system, and various applications).  Additionally, if we made a "fix", another user with just a few pixels less than we planed for, would be in the same situation of needing to use the scroll bar.

This feature, and its noted behavior, are "by design", utilizing scroll bars in an industry accepted fashion.  I think this should be noted as such and closed.

**Comment by dstuder** [comment]
@evanweaver Thanks for the explanation. I had assumed that the auto sizing was being performed incorrectly (and forcing the last few pixels off the end of the page) rather than the minimum possible width serendipitously being just wider than my screen.

I suggest that this still be turned into a feature request and left open. I'm not sure how the text entry space is set up in Qt, but there is obviously a lot of screen real-estate that could be reclaimed if the text entry boxes were shortened up to reflect the allowed precision in each cell (note the extended white space to the right of each text entry cell; I doubt someone would need to enter temperature values to 12 decimals!).
