### ISSUE TITLE
Add Model::path() method to support copying files to resources 

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1590]
Use case is when calling setWeatherFile in a measure the weather file should be copied into the companion directory for you.  Currently logic to do this lives in the OS app, it should move into model.

Requires setting this path when the file is loaded and managing the path as file is saved/saved as.  

Will also require that this is set on model when running measures.  Need to discuss if this path should be to the last OSM on disk or to the original OSM at beginning of workflow, I think we want the latter.

Might want to add as a Workspace method?

**Comment by macumber** [comment]
I anticipate that this feature will require a lot of testing.

**Comment by macumber** [comment]
@DavidGoldwasser @evanweaver @kbenne @asparke2 @nllong you guys want to weigh in?

**Comment by macumber** [comment]
Might be able to implement https://github.com/NREL/OpenStudio/issues/1444 at same time

**Comment by macumber** [comment]
@nllong we may need to coordinate on what this returns on server versus locally?

**Comment by DavidGoldwasser** [comment]
I'm doing some testing with the proof of concept BCL measure I wrote, which changes/set the weather file. It does change the weather path and downloads the component from BCL. Works fine via command line, and apply measure now, but had very odd behavior in PAT with local run. All of the jobs run, but they run with the original weather file, vs. the one on BCL. I would expect the simulation to fail or run with the requested weather file. I confirmed similar behavior in PAT if I use the existing ChangeBuildingLocation measure which doesn't pull from BCL. ChangeBuidlingLocation does work on the server (if files are in right location) I have not tested BCL measure yet on server.

Screenshot show modified file on left. I set it to chicago vs. denver for baseline. Notice no change in district heating and cooling. I also confirmed in html output that it thinks it is running in Denver.

![4-9-2015 10-45-19 am](https://cloud.githubusercontent.com/assets/4857055/7072294/5fe30108-dea8-11e4-9c5d-1a76138b9c64.png)

**Comment by DavidGoldwasser** [comment]
@macumber I think what you are suggesting is a good idea. In my case with example above the run section of the measure would be where the file is copied over, but I can see cases where we want to copy files over in the arguments section, in particular for measures that let you pull in resources from anywhere on your local system. We want that pulled in when arguments is run so you can do cloud PAT run without it breaking. For people using the spreadsheet, they would still have to put the file in a location that goes up as well since arguments section doesn't run until after upload. Would be nice tof the GUI to support path argument where user can browse to select vs. using a string argument, which is what is done now.

One issue with this, if you keep changing arguments, you would have multiple files in "files" when only one is needed. My proposed solution for this is good measure code where the file that is moved is renamed with measure_name_arg_name. That way if they key changing their selection, then the files will overwrite each other, and there will never be more than one; but on a parametric run, which each datapoint have its own "files" or would they share? If they share, then we would need to keep all the files, and could be issue if two files of same name pulled in from different source locations.

**Comment by asparke2** [comment]
Not sure how this would be different than `"#{File.dirname(__FILE__)}"` or something.

Below is the current code that the Create DOE Prototype Buildings Measure uses so that it will work on the Server, PAT and OS App, and OS App Apply Measure Now.  If what you are proposing helps simplify this, then yes, I support it.

```ruby
    # Set up the sizing simulation
    # Find the weather file
    epw_path = nil
    if self.weatherFile.is_initialized
      epw_path = self.weatherFile.get.path
      if epw_path.is_initialized
        if File.exist?(epw_path.get.to_s)
          epw_path = epw_path.get
        else
          # If this is an always-run Measure, need to check a different path
          alt_weath_path = File.expand_path(File.join(File.dirname(__FILE__), "../../../resources"))
          alt_epw_path = File.expand_path(File.join(alt_weath_path, epw_path.get.to_s))
          if File.exist?(alt_epw_path)
            epw_path = OpenStudio::Path.new(alt_epw_path)
          else
            OpenStudio::logFree(OpenStudio::Error, "openstudio.model.Model", "Model has been assigned a weather file, but the file is not in the specified location of '#{epw_path.get}'.")
            return false
          end
        end
      else
        OpenStudio::logFree(OpenStudio::Error, "openstudio.model.Model", "Model has a weather file assigned, but the weather file path has been deleted.")
        return false
      end
    else
      OpenStudio::logFree(OpenStudio::Error, 'openstudio.model.Model', 'Model has not been assigned a weather file.')
      return false
    end
```

**Comment by macumber** [comment]
Yeah I think this would be a more robust way to do what you are trying to do @asparke2

**Comment by macumber** [comment]
@rpg777 this is also helpful for reorganizing the exported radiance files

**Comment by macumber** [comment]
I am changing my mind on which path should be returned.  If you are running an apply measure now measure that sets the weather file then the weather file should be changed in the companion directory.  If you are running as part of a workflow then the input weather file should not be changed.  I assume this is what @asparke2 's code is doing.

**Comment by macumber** [comment]
It sounds like OSRunner needs a method for isApplyNowMeasure

**Comment by DavidGoldwasser** [comment]
@macumber if you aren't going to change the path as part of a workflow run, then how will PAT local run get fixed to work? It isn't working now if a measure tells it to sue a different weather file.

**Comment by macumber** [comment]
@DavidGoldwasser the weatherfile should be changed for the datapoint being run but not for the starting osm seed

**Comment by DavidGoldwasser** [comment]
@macumber I agree with that, as long as the datapoint has a way to run with the correct weather file. For cloud PAT simulation we can't leave it where it is, because it is on local hard drive location. Has to get packaged up somewhere.

**Comment by DavidGoldwasser** [comment]
New unmet hours post today. I'll see if I can fix meant with logic from prototype measure. The difference here is that the epw's are not contained in the measure.
https://unmethours.com/question/15544/change-building-location-measure-in-pat/?comment=15625#post-id-15625

**Comment by DavidGoldwasser** [comment]
I also need to see if works for parametric sweep vs just an always run measure.

**Comment by aaron-boranian** [comment]
Problem: TBD

Solution: Add Model::path() method to support copying files to resources

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9099193)
