### ISSUE TITLE
Setting color scales in ResultsViewer does not work

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1750]
See this user post: https://unmethours.com/question/9909/flood-plot-scale/

I tried this and setting the color scale did not seem to correctly update the image.  Would be nice to also be able to set the limits on y axis of line plots manually too.

**Comment by DavidGoldwasser** [comment]
Good catch, pretty nasty, since the scale at the right changes, but just not the image map. Would be good to fix that for 1.9 since it can cause someone to mis-interpenetrate simulation data. While I tested did some screenshots, I'll add them here since I have them already.

I like the ability to scale the color data. I'm no ta big fan of scaling the x or y. The general use of these flood plots is to see the entire run period all at once without any panning or zooming. 

![8-3-2015 10-50-34 am](https://cloud.githubusercontent.com/assets/4857055/9042790/4b8ab0d0-39ce-11e5-8f63-35ad78bc5ab2.png)
original autoscale plot

dialog showing change to scaling

resulting plot

**Comment by rpg777** [comment]
This has been [reported](https://unmethours.com/question/17163/illuminance-map-scale-change-doesnt-work/) by another user on UH today, as well. The issue here is that the control gives the user the ability (and thus the impression) that the plot scale can be changed; while the values in the legend do change, the flood plot does not remap/scale to the new max/min values.
