### ISSUE TITLE
OpenStudio App crash on user file

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1755]
Hello,

This file is in reference to the following post:

https://unmethours.com/question/9983/any-experience-with-the-following-openstudio-crash-an-unhandled-exception-has-occurred-access-violation-no-rtti-data/

I was assigning spaces to thermal zones and received the error when I went into OS and attempted to access the Facilities tab.  There are several simple images attached that I hope will describe the space types and zoning.  Note that the thermal zoning is incomplete at this point.

The v3-12 (3) *.osm file does not trigger the error message is OS.  The v3-12 (4) *.osm file does trigger the error in OS.

Please let me know what additional information is required and I'll happily provide it!

Many Thanks,
Nick

**Comment by macumber** [comment]
The call stack for this crash in OS 1.8.0 is the same as in #1763

**Comment by kbenne** [comment]
I repaired Nick's model and sent it back. The underlying issue is similar to https://github.com/NREL/OpenStudio/issues/1667 but almost the opposite. There we were seeing zones that did not get initialized. Here it is as if the initializers are over zealous and being called an extra time on a phantom zone. 

@jmarrec's [description](https://unmethours.com/question/9983/any-experience-with-the-following-openstudio-crash-an-unhandled-exception-has-occurred-access-violation-no-rtti-data/) of the repair is very accurate.

**Comment by kbenne** [comment]
@macumber and @DavidGoldwasser are we good to close?
