### ISSUE TITLE
When you make a new schedule "Temperature" shows up twice in the Schedule Type list.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1875]
reported by @jmarrec

**Comment by macumber** [comment]
The reason is that we end up with two scheduletypelimits for temperatures, one with a lower limit of 0 and the other with no lower limit:

OS:ScheduleTypeLimits,
  {ea1155da-584d-4c58-a0b7-6df2253be363}, !- Handle
  Temperature,                            !- Name
  ,                                       !- Lower Limit Value {BasedOnField A4}
  ,                                       !- Upper Limit Value {BasedOnField A4}
  Continuous,                             !- Numeric Type
  Temperature;                            !- Unit Type

OS:ScheduleTypeLimits,
  {74b29f4a-09e4-435e-b46b-89f8a5fd521f}, !- Handle
  Temperature 1,                          !- Name
  0,                                      !- Lower Limit Value {BasedOnField A4}
  ,                                       !- Upper Limit Value {BasedOnField A4}
  Continuous,                             !- Numeric Type
  Temperature;                            !- Unit Type

**Comment by macumber** [comment]
We could include the lower limit in the getDefaultName method

https://github.com/NREL/OpenStudio/blob/f3087fd11d114541d35ea140f02ed9bd0e5de07d/openstudiocore/src/model/ScheduleTypeRegistry.cpp#L400

**Comment by macumber** [comment]
Or we could remove the lower limit for the "PipeIndoor", "Ambient Temperature" schedule:

https://github.com/NREL/OpenStudio/blob/f3087fd11d114541d35ea140f02ed9bd0e5de07d/openstudiocore/src/model/ScheduleTypeRegistry.cpp#L260

**Comment by macumber** [comment]
Looks like @evanweaver did PipeIndoor, Evan do you care about constraining this object to only use schedules with lower limit 0?  My vote would be to remove this lower limit in OS and let it crash in E+.

@kbenne @mbadams5 any thoughts?

**Comment by evanweaver** [comment]
@macumber I'll defer to Kyle and Mark.
