### ISSUE TITLE
OpenStudio App loses weather file

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1915]
Reported by Elizabeth Gillmor, save as and update version may be related.  Symptom is that OSM which used to run correctly suddenly fails because weather file is missing.

**Comment by macumber** [comment]
I see two things that are odd in user's file; the WeatherFile object in your OSM is pointing to an absolute path instead of a relative one, the second odd thing is that the absolute path is pointing to the weather file in a different project.  If you delete your old OSM that might be breaking the new OSM, do you think that deleting old projects might be what is breaking your current project?  I’m not sure why you have absolute paths in your OSM, did you use the buttons on the first tab of the OS App to assign your weather file?  Did you ever rename the OSM and companion directory or move them?  Did you hand edit the weather file path in the OSM?  Did these OSM files come from a PAT run?

**Comment by macumber** [comment]
This could be happening if weather file is not found: https://github.com/NREL/OpenStudio/issues/138

**Comment by macumber** [comment]
https://github.com/NREL/OpenStudio/blob/3b0d232b5f99a2a331804a8f9762f32a99b1a56b/openstudiocore/src/openstudio_lib/LocationTabView.cpp#L552

**Comment by macumber** [comment]
I'm guessing that updateModelTempDir is somehow not being called after setting the weather file

**Comment by macumber** [comment]
From Elizabeth:

Weather file issues -- I still have the same problem where if I save a file as a new name and then move the old one into an archive directory, that the new file forgets that is has a weather file.  And then of course it fails after it has taken 10 minutes of runtime already.  I thought that was supposed to be fixed this version? Maybe not?  Anyways, I bet I have lost HOURS of time from failed runs because of this.  Would really like a fix.

**Comment by macumber** [comment]
@evanweaver this might be something to ignore on the 1.X branch, file handling is a big push for 2.0 branch

**Comment by evanweaver** [comment]
@macumber do we have a recommended workaround, in the meantime?

**Comment by macumber** [comment]
Reset the weather file when you do a save as

**Comment by egillmor** [comment]
Hi All. Not surprisingly, this is an issue with PAT as well.  Simply resetting the weather file is not as easy here.  I have to remove the osm files from PAT altogether which then of course deletes all the design alternatives and the results.  I have *hundreds* of wasted hours between these two issues.  Please let me know where this is on the priority list and when this will be fixed.  Thanks.

**Comment by macumber** [comment]
Issues affecting EDAPT users go to the top of the list, we take them very seriously.  Can you give a little more detail about what happened here?  An OSM had lost its weather file, then you used that as a seed in a PAT project?  You had a PAT project and wanted to change just the weather file and not the seed?

**Comment by egillmor** [comment]
Yes, this is an EDA project.  I took an older PAT project (1.7) from an FEA that was ready to be updated per the CD Review.  I updated it to PAT 1.9 since I haven't had time to mess with the 1.10 fix yet about opening older files and I didn't want to risk it getting eaten.  Saved it into a new folder, made a small change to one DA, ran it, all runs failed.  But weirdly nothing showed up in the .err files within the alternatives folders, the only fail indication was in the PAT results view.  

So then I guessed it must be the weather file thing and attempted to open the seed and alternative osm files to re-add the weather files, then re ran PAT, but those failed too.  

Then I deleted the alternative file model (my EDA baseline), and tried to re-add just that one.  Re-ran again. Failed again.

I finally scrapped the whole damn thing and started from scratch.  Re-opened the baseline and proposed models from the FEA, resaved the weather file for each, recreated the PAT project from scratch in 1.10, and recreated all the measures.  And then, it finally worked.
  
So what should have taken just a few minutes just took me two hours, and I don't know what I could have done to avoid it, other than starting the CD review PAT file from scratch in the first place.  At least in this case there were only four measures I had to recreate, but my other EDA projects might have 20-30.  It will not be fun.

**Comment by macumber** [comment]
So you updated an old PAT project and saved it to a new location and that broke links with all the weather files?  I'm not sure what happened after that (if you were opening the seed/alternative models in the PAT project or outside of it, etc) but I think the root cause was losing the weather file on update and/or save as. We can look into that.  

We are working on OS and PAT version 2.0 this year, better handling of external files (like weather files) is very high on the priority list for that work.

**Comment by egillmor** [comment]
Yes that's about it.  It's very possible that I had archived some older files in the other directory which "broke" the weather file link in the 1.7 file after I had finished the PAT project but before I did the save-as, I don't know.  

After the first run failed, I then tried to open the seed/alternative models of the new PAT file in OS 1.9 to re-attach the weather file, but for some reason that was unsuccessful.  Then I also tried removing the alternative model altogether, and reattached one with a corrected weather file, but that was also unsuccessful.  At that point I was tired of wasting time fiddling with it and I gave up.  I could only assume there was something embedded deep in there that I couldn't change.

While you are working on a more permanent fix, I'd like to know how to deal with this in the interim so that I don't have to totally recreate all my PAT projects.  Opening/changing the seed and alternative models within the PAT folders did not fix the issue.  My coworker and I use dropbox, and we will each create and run models under different file paths, so I can absolutely guarantee that this is going to be a serious, ongoing problem for us.  Resetting weather files for a single osm files (a zillion times) is annoying, but manageable -- ruining an entire PAT project is NOT OK.  Need a solution ASAP.

This didn't use to be a problem -- what changed, and why can't it be changed back?

**Comment by egillmor** [comment]
Also -- I'd like to put in my vote that this issue NOT wait until 2.0.  Something that destroys a existing file (or renders it totally useless) should be made a top priority.

**Comment by ljbrackney** [comment]
We agree.  Critical fixes to PAT 1.x will continue to be made while the team works on the more robust PAT 2.0.  Show stoppers from EDA users always bubble up to the top of the team's work queue.

On Jan 24, 2016, at 8:05 PM, egillmor <notifications@github.com<mailto:notifications@github.com>> wrote:


Also -- I'd like to put in my vote that this issue NOT wait until 2.0. Something that destroys a existing file (or renders it totally useless) should be made a top priority.

-

**Comment by macumber** [comment]
@egillmor I suspect that the issue goes back to the initial seed OSM losing it's weather file because the OSM is pointing to a weather file via an absolute path and then that weather file moves.  Then next time this happens, I suggest opening the OSM file in the seed folder of your PAT project in a text editor, search for the OS:WeatherFile object.  If the Url field points to a file that does not exist, you can update that field; this will not delete existing results.

**Comment by eringold** [comment]
I've also had some trouble with a 'save as' resulting in energyplus error for no weather file. Curiously, the weather file name remains in the Site tab, and clicking 'Change Weather File' opens the file location where the .epw is located. 

To pile on, if the YearDescription object is set to 'Calendar year', this will be re-set to 'Day of Week for start day' upon save-as. This can really foul up simulations with day-specific schedule priorities.

**Comment by egillmor** [comment]
Yes, I have had the calendar year thing happen as well.  In my case, it reverted in my proposed model but not my baseline, and I was pulling my hair out trying to figure out why my equipment kWh differed between the two, despite being modeled identically.  That was the culprit.

**Comment by macumber** [comment]
Here is the call stack that makes the epw file absolute when opening an older (1.10.0) file into 1.10.5:

```
 	openstudio_model.dll!openstudio::model::detail::WeatherFile_Impl::makeUrlAbsolute(const boost::filesystem::path & searchDirectory) Line 312	C++
 	openstudio_model.dll!openstudio::model::WeatherFile::makeUrlAbsolute(const boost::filesystem::path & searchDirectory) Line 513	C++
 	openstudio_lib.dll!openstudio::OSDocument::setFullWeatherFilePath() Line 1020	C++
 	openstudio_lib.dll!openstudio::OSDocument::setModel(const openstudio::model::Model & model, bool modified, bool saveCurrentTabs) Line 473	C++
 	openstudio_lib.dll!openstudio::OSDocument::OSDocument(openstudio::model::Model library, openstudio::model::Model hvacLibrary, const boost::filesystem::path & resourcesPath, boost::optional<openstudio::model::Model> model, QString filePath, bool isPlugin, int startTabIndex, int startSubTabIndex) Line 328	C++
 	OpenStudio.exe!openstudio::OpenStudioApp::openFile(const QString & fileName, bool restoreTabs) Line 277	C++
 	OpenStudio.exe!openstudio::OpenStudioApp::open() Line 740	C++
```

**Comment by macumber** [comment]
Moving the day of week for start day part of this thread to a new issue, https://github.com/NREL/OpenStudio/issues/2133

**Comment by macumber** [comment]
@evanweaver the changes in the first 1.10.5 packages are not good, can we remake the packages with change that I just committed, https://github.com/NREL/OpenStudio/commit/f96ea3e61babf0fa6cb70e498d8568eeede2b826 ?

I **ONLY** trust making this change if we can remake 1.10.5 installers so this gets well tested in the next two weeks

**Comment by macumber** [comment]
Need to test with:

- Creating new OSM and setting weather file
- Opening existing OSM with weather file
- Save as with weather file
