### ISSUE TITLE
Unable to assign thermalZone to Inverter

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1928]
Not sure why assigning a thermal zone to an inverter doesn't work...

```ruby
In [1]: inverter = OpenStudio::Model::ElectricLoadCenterInverterSimple.new(model)
In [2]: thermalZone = model.getThermalZones[0] # I do have a thermal zone...
In [3]: inverter.setThermalZone(thermalZone)
Out[3]: => false
```
     
Same result with `OpenStudio::Model::ElectricLoadCenterInverterLookUpTable`

**Comment by macumber** [comment]
Yeah I think I see the issue, [this line](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/resources/model/OpenStudio.idd#L24386) should be `\object-list ThermalZoneNames` instead of ZoneNames.  I see this is also an issue in OS:Controller:OutdoorAir humidistat control zone.  I'll fix this in the E+ 8.4 branch that I am merging today, will be in 1.9.3.

@kbenne @evanweaver FYI
