### ISSUE TITLE
Expose all fields of the Sizing:Zone object

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1947]
Not all fields of the Sizing:Zone object are exposed in OpenStudio as of 1.9.3, and that includes for example `Zone Cooling Design Supply Air Temperature Input Method` or `Zone Cooling Design Supply Air Temperature Difference`.

**More importantly, E+ 8.4 has changed the Sizing:Zone object to introduce an important and, I believe, well-anticipated feature to support proper sizing taking DOAS into account**, with 4 new fields:

*  Account for Dedicated Outdoor Air System
* Dedicated Outdoor Air System Control Strategy
* Dedicated Outdoor Air Low Temperatue Setpoint for Design
* Dedicated Outdoor Air High Temperature Setpoint for Design

As support of E+ 8.4 is rolling out (starts with 1.9.3), it think it's important to expose these fields.

**Comment by kbenne** [comment]
I have this done, but it is too close to release to drop in, so I will merge it immediately after 1.10. @jmarrec I'm sending you a friendly build with this feature.

**Comment by jmarrec** [comment]
@kbenne thanks!

**Comment by wta12** [comment]
@kbenne: May i get that sizing:zone release before. I am creating a DOAS system in OS.

**Comment by kbenne** [comment]
@wta12 send me an email kyle.benne@nrel.gov and I'll send you a link to a friendly build. I don't want to distribute this widely since it isn't an official build or iteration yet. I would appreciate the testing from a limited number of people. I created a build based on this PR https://github.com/NREL/OpenStudio/pull/2009 which has several pending features rolled up in it, including these new SizingZone features.

**Comment by kbenne** [comment]
@jmarrec I sent you a link on Slack.

**Comment by jmarrec** [comment]
@kbenne: I'm only getting to this now and I'm wondering if I see OS  v1.10.1 was released 4 days ago. Will I miss something big if I use your older friendly build?

**Comment by kbenne** [comment]
Please use the iteration build if possible. The problem with friendly builds is that there may be version translation problems down the road. Consider for instance if you build a model with a friendly build that reports itself as 1.10.0, but then after the friendly build some version changes came into the real 1.10.0. Your "friendly built" model will miss those version updates because OS will not run the version translator, thinking it is already up to date.
