### ISSUE TITLE
OS:LoadProfile:Plant Object not functioning properly 

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#1971]
When this object is added to an OS model (using OS v1.9.0 Win 64 Bit install), It appears the "Control Scheme Schedule Name" object is not being correctly populated. This field, while visible in the OS App GUI, does not appear to be editable. Thus, a severe error occurs at runtime. User was able to manually edit the OS generated .idf file and define a schedule for this field, which allowed the .idf file to execute properly (in the E+ 8.3 environment).. 

   *************    570   Plant Loop 1 Operation Schemes,         !- Name
   *************    571   PlantEquipmentOperation:HeatingLoad,    !- Control Scheme Object Type 1
   *************    572   Plant Loop 1 Heating Operation Scheme,  !- Control Scheme Name 1
   *************    573   ;                                       !- Control Scheme Schedule Name 1
   ** Severe  ** IP: IDF line~573 Error detected in Object=PLANTEQUIPMENTOPERATIONSCHEMES, name=PLANT LOOP 1 OPERATION SCHEMES
   **   ~~~   ** Field [Control Scheme 1 Schedule Name] is required but was blank
   ** Severe  ** IP: Blank "required" fields found in input
   ** Severe  ** IP: Out of "range" values and/or blank required fields found in input
   **  Fatal  ** IP: Errors occurred on processing IDF file. Preceding condition(s) cause termination.

**Comment by kbenne** [comment]
Hey @chrisbalbach I think there could be more than one thing going on here. The error you pasted is from the plant operation schemes, which pertain to sequencing the supply side plant components. LoadProfilePlant is a demand component so I don't think it is related. 

On the supply side, with respect to operation schemes, there has been large changes behind the scenes, in order to gain direct access to the operation schemes from OS Model. If you choose not to use these new features the same old operation scheme defaulting is still in place. Based on your error it is possible there is a regression with respect to the op scheme default logic, but I'm not yet sure. It could be other things such as no plant equipment at all, or maybe you have a heat pump involved, which had a bug i fixed here https://github.com/NREL/OpenStudio/commit/dbc4f2056a749a67471936eeda48ae4e454609a0#diff-5983125171f9206c9c662c6635f69444.

With respect to the LoadProfilePlant object, I see two schedules, "Load", and "Flow Rate Fraction", I believe they are both being translated ok.

Can you send the model? Seems to me if there is an issue it should be easy to fix and I'd prefer to squeak it into 1.10.

**Comment by chrisbalbach** [comment]
Kyle

Using os v1.9.0 release candidate - I could not get ANY openstudio generated file to work using the plant load profile object. I tried the simplest model possible - using one default plant load profile object, a single auto sized default constant speed pump and a single auto sized default chiller with a set point manager scheduled default object. Upon running this model in openstudio I encountered the error that I documented. When I exported this model to idf format and hand edited the field that openstudio was complaining about,  the idf file was able to execute. It failed to complete because of convergence issues but that is a different issue that involves using default values I believe.

I can send you the file(s) used in my tests when I get to my pc.

Two weeks ago I asked Amir (copied) to help check /validate the behavior of this object in energyplus. For example, is pump energy (heat) added to this plant load profile object load prior to conversion by equipment? I'm very interested in understanding how this object also works when combined with actual defined systems (in parallel) on the demand side. I have found very little evidence of other users working with this object and the engineering documentation does not quite explain the edge cases very well...

Let's work together to get this working in os v1.10. I have some very interesting use cases for it and I need to be able to successfully demo them using openstudio - not energyplus.

Thanks,

Chris



Sent from my iPhone

On Dec 1, 2015, at 2:34 PM, Kyle Benne <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @chrisbalbach<https://github.com/chrisbalbach> I think there could be more than one thing going on here. The error you pasted is from the plant operation schemes, which pertain to sequencing the supply side plant components. LoadProfilePlant is a demand component so I don't think it is related.

On the supply side, with respect to operation schemes, there has been large changes behind the scenes, in order to gain direct access to the operation schemes from OS Model. If you choose not to use these new features the same old operation scheme defaulting is still in place. Based on your error it is possible there is a regression with respect to the op scheme default logic, but I'm not yet sure. It could be other things such as no plant equipment at all, or maybe you have a heat pump involved, which had a bug i fixed here dbc4f20#diff-5983125171f9206c9c662c6635f69444<https://github.com/NREL/OpenStudio/commit/dbc4f2056a749a67471936eeda48ae4e454609a0#diff-5983125171f9206c9c662c6635f69444>.

With respect to the LoadProfilePlant object, I see two schedules, "Load", and "Flow Rate Fraction", I believe they are both being translated ok.

Can you send the model? Seems to me if there is an issue it should be easy to fix and I'd prefer to squeak it into 1.10.

-

**Comment by chrisbalbach** [comment]
That was 11 days ago with two weekends and Thanksgiving in between! Jeez! :)



Amir Roth, Ph.D.
DOE/EERE/BTO Technology Manager, Building Energy Modeling
http://www.energy.gov/eere/buildings/building-energy-modeling/
O: 202.287.1694

**Comment by kbenne** [comment]
I always add a test model for new features including this one. I'll take a look at my test model and your file tomorrow. We'll get this worked out.

On Dec 1, 2015, at 5:02 PM, Chris Balbach <notifications@github.com<mailto:notifications@github.com>> wrote:

That was 11 days ago with two weekends and Thanksgiving in between! Jeez! :)



Amir Roth, Ph.D.
DOE/EERE/BTO Technology Manager, Building Energy Modeling
http://www.energy.gov/eere/buildings/building-energy-modeling/
O: 202.287.1694

**Comment by chrisbalbach** [comment]
Kyle

See attached .osm file and idf file that was exported then hand modified..

Thanks,

_Chris

**Comment by kbenne** [comment]
@chrisbalbach #1989 should take care of things. I did notice that your model had a tiny load (1 W) defined by the plant load profile object which was not near enough load to soak up the heat being generated by your hard sized boiler. The result was run away plant temps. To confirm that the fix is working I took your model and autosized the boiler and gave the load profile a little more power, 500 W.
