### ISSUE TITLE
Materials Tab - Last to classes of material are three rows high so text gets cut off (Bugzilla #927)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#198]
On 2012-09-18 16:59:32, @DavidGoldwasser wrote:

> Trivial and not important for 0.9.0 but if it is just a line of code to change, could be worth it.

**Comment by evanweaver** [comment]
Fixed via Pivotal 90045936

**Comment by DavidGoldwasser** [comment]
Here is picture with construction set from our current library in fresh build of develop. Apparently since this was first written our construction names have gotten longer, or the horizontal space is shorter, now 4 lines. I know we can't jsut keep adding on more lines, but I think there is a way to improve it. While vertically centered is fine fro short names, a top justified with only the last line cut-off would be better for long names. Is there a way to know that it will wrap to 4 lines and then top justify vs. centering? Another option would allow the GUI to wrap text mid-word then three lines would be plenty even with these long names.

![3-11-2015 12-03-42 pm](https://cloud.githubusercontent.com/assets/4857055/6603364/4510bb36-c7e7-11e4-95b9-3621bd84a3af.png)

**Comment by evanweaver** [comment]
What I thought you were referring to (... Materials tab, last 2 objects).  Look at the lower lefthand corner of the image.
![image](https://cloud.githubusercontent.com/assets/4974134/6604317/2cc87c66-c7ed-11e4-8047-e1ac262ced4f.png)

**Comment by DavidGoldwasser** [comment]
Sorry, I got things mixed up. Yes, this issue was specifically about what is shown in your screenshot

**Comment by evanweaver** [comment]
Here is my fix:
![image](https://cloud.githubusercontent.com/assets/4974134/6604402/b1ccd358-c7ed-11e4-84a8-a62cedf7187b.png)

**Comment by evanweaver** [comment]
@DavidGoldwasser it's already been committed to my bug fix branch

**Comment by DavidGoldwasser** [comment]
@evanweaver looks good, but I don't see it on develop, I assume you will push from your local build. I still see issue on my build from this morning.

**Comment by evanweaver** [comment]
@DavidGoldwasser again, I have committed it to my bug fix branch

**Comment by DavidGoldwasser** [comment]
Sorry, didn't see pull request and didn't know you had a branch for bugs. I merged pull requests assigned to me into my local develop build. I'll close this if it is on branch that will be merged.
