### ISSUE TITLE
AddOutputVariable measure should support the "annual" reporting frequency

### ISSUE THREAD

**Issue by pachi** [NREL/OpenStudio#1983]
The extremely useful AddOutputVariable measure in the BCL could also have "annual" as reporting frequency.

This frequency is (implicitly) already supported, returning the values for the RunPeriod, but the .rb file needs to be modified to show up in the measure GUI, just by adding this line after line 31:

```
    reporting_frequency_chs << "annual"
```

**Comment by DavidGoldwasser** [comment]
I"ll fix this over the weekend. I think it will need to be "runperiod" instead of "annual". While I'm dabbling in this measure, any interest in having the "key" field exposed. It currently is hard coded to "*" but could let you pick a specific object. I could even let you enter comma separated values and then make an output variable for each one of them. EnergyPlus can't directly do this. You get one object or all. This would make getting output for 10 different surfaces less painful.

**Comment by pachi** [comment]
We tried with "annual"  and it worked, but "runperiod" looks like a better choose.

The idea of exposing the key field exposed looks very interesting and useful.
If you want more ideas, it just occurred to me that allowing regex expressions in places like the "key" field would be even more powerful, but maybe it's overkill and there's no need for that.

Also, have you thought about distributing more of these measures along with OpenStudio? This kind of measures help to overcome some limitations of OS (in relation to bare EnergyPlus) and are good programming examples.

Anyhow, thanks for your great work!

**Comment by DavidGoldwasser** [comment]
Updated measure here. Also exposed basic argument for key value.
https://bcl.nrel.gov/node/37843

**Comment by eringold** [comment]
@DavidGoldwasser check the measure in that link - it doesn't have the key value argument. Perhaps the wrong one got uploaded?

**Comment by DavidGoldwasser** [comment]
@eringold thanks for pointing that out. I'll re-open this while I look into it. I also updated the fan assist night vent, need to check if current changes went there.

**Comment by DavidGoldwasser** [comment]
Both measures have been updated now, same url. It may be a few hours before the app is aware of the update to download it through GUI.
