### ISSUE TITLE
Users disabling StandardReport measures to use IP reporting measure.

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2039]
I am not sure what the right solution to this is, but there is obviously a problem here as users are messing with the installation in order to run the IP reporting measure.

https://unmethours.com/question/11357/os-185-and-19-turn-off-built-in-openstudio-results-measure/?answer=14258#post-id-14258

In PAT 2.0 we might want to make it easier for users to simply remove the StandardReport measure.  We might also work with E+ team to handle dual units output or something like that.

**Comment by macumber** [comment]
This issue is just to host discussion so we can arrive at a solution.

@DavidGoldwasser @asparke2 @kbenne @brianlball @henryHorsey

**Comment by macumber** [comment]
Other option is to make StandardReport exit without failing if IP units are discovered.  This is a little weird but possibly justified since users can't remove the measure on their own.

**Comment by jmarrec** [comment]
Note that in my case I just wanted to be able to turn it off as it's considerably slowing overall simulation time while I'm troubleshooting (Love the design, but I'll save that for the end game)

**Comment by DavidGoldwasser** [comment]
I like the idea of treating the standard reporting measure kind of like the radiance measure, with one exception. When I make a new OSM file the standard reporting measure is in the workflow by default. But the user sees it in the workflow and has an option to remove it or to use the measure arguments to enable/disable specific sections.

I don't know there is a mechanism to do this now? But there should be a way to set  template characteristics outside of the OSM.

**Comment by macumber** [comment]
I think David's suggestion is the right approach for PAT 2.0 and OS App 2.0, don't think it is worth messing with for current version.

**Comment by DavidGoldwasser** [comment]
I agree we don't need a short term solution, if we can get it right for September, that is fine.

**Comment by ljbrackney** [comment]
I like David's suggestion also.  It starts to back away from the notion of a "magic measure" and gives the user more control.  It seems like it would be straightforward to populate a new model with that as a reporting measure that could be deleted by the user.

On Jan 22, 2016, at 9:50 AM, Dan Macumber <notifications@github.com<mailto:notifications@github.com>> wrote:


I think David's suggestion is the right approach for PAT 2.0 and OS App 2.0, don't think it is worth messing with for current version.

-

**Comment by macumber** [comment]
I do think reporting measures can continue to fail if they detect IP units and are not set up to handle them.  The user can just remove failing measures.  My question is if the simulation workflow should really halt when a reporting measure fails or if it should attempt to continue on?

**Comment by DavidGoldwasser** [comment]
I've tried to update the standard report measure to fail gracefully with internal error handling instead of throwing an error, so hopefully if people follow that pattern we will see less failures (I can also tighten up the standard report more), but I like the idea of running subsequent reporting measures after one fails. But if that is a big effort then maybe better to focus on measure quality.

**Comment by eringold** [comment]
Just want to chime in that I think it's fine for the results measure to be in the workflow by default, but should have user controls to turn sections (or the whole thing) off, for the same reasons @jmarrec mentioned (and also [here](http://openstudio.uservoice.com/forums/308629-openstudio/suggestions/10094883-add-user-controls-to-default-results-reporting)).

**Comment by MatthewSteen** [comment]
+1 for @jmarrec's comment of reporting measures adding to sim time. 
+1 for @DavidGoldwasser's idea of removing the OS measure from the installation. 

My preference would be to show the `eplustbl.htm` file in the Results Summary tab without any sort of OS reporting by default. However, I do think the unit preference from the app should be included in the forward translation so that it doesn't require an EP measure to view the Summary Tables in IP units.

**Comment by macumber** [comment]
@MatthewSteen the main reason we have not wanted to support IP units in E+ reporting is that our API methods and other reporting measures assume SI results.  If we allowed IP/SI results then all the API methods and reporting measures would have to check which units were used.  This could lead to reporting measures that only worked with SI or IP and you would get into a big mess.  Our thought was that if the standard report was comprehensive enough then the reporting measure could handle the unit preference.  

It sounds like the standard report measure is not complete enough (because you still want to use the E+ reports) and also it is too slow, is that right?  My preference (at this point) is to have an option in E+ which reports dual units in html (possibly writing both eplusout.html and eplusout_ip.html) while preserving SI units in the SQL file.  If E+ had dual unit outputs and allowed you to easily disable the standard reporting measure, would that meet your needs?

**Comment by ljbrackney** [comment]
I don't think we can just get rid of the standard reporting measure and make users install it.  That's great for power users, but would strand a huge number of neophytes who just want to install the app and get something out quickly. I still like David's suggestion of installing it as a regular reporting measure in blank models then letting people choose to delete it if runtime* is an issue.

Larry

* Have we profiled the reporting measure?

On Jan 24, 2016, at 3:45 PM, Dan Macumber <notifications@github.com<mailto:notifications@github.com>> wrote:


@MatthewSteen<https://github.com/MatthewSteen> the main reason we have not wanted to support IP units in E+ reporting is that our API methods and other reporting measures assume SI results. If we allowed IP/SI results then all the API methods and reporting measures would have to check which units were used. This could lead to reporting measures that only worked with SI or IP and you would get into a big mess. Our thought was that if the standard report was comprehensive enough then the reporting measure could handle the unit preference.

It sounds like the standard report measure is not complete enough (because you still want to use the E+ reports) and also it is too slow, is that right? My preference (at this point) is to have an option in E+ which reports dual units in html (possibly writing both eplusout.html and eplusout_ip.html) while preserving SI units in the SQL file. If E+ had dual unit outputs and allowed you to easily disable the standard reporting measure, would that meet your needs?

-

**Comment by macumber** [comment]
@MatthewSteen do you care if any of the other files (ESO, SQL, etc) are in IP or do you only care that the html is in IP?

**Comment by macumber** [comment]
From that uservoice link it seems that part of the issue is that the reporting measure currently adds a bunch of report variables to the simulation in order to create all of the sections.  These report variables add time (and output size) to the E+ simulation in addition to the time it takes to create the report.

**Comment by MatthewSteen** [comment]
@macumber I think that's where we're not hearing each other. My comments only apply to the HTML output and simply adding `InchPound` to the Unit Conversion field of the OutputControlTableStyle object, which doesn't affect the other EP files. Completely understand the undertaking converting these other files would be. 

@ljbrackney that's a good point and I agree that there should be a 'high level' output option for new users. This could perhaps be added to the Simulation Settings tab separate from the unit preference selection in the file menu.

**Comment by macumber** [comment]
The problem is that ip setting does affect the tabular reports in the sql file where many reporting measures and API methods pull data from.  I'm not sure if the ip switch affects time series data in the sql or not.

**Comment by MatthewSteen** [comment]
@macumber ah I see how that would be a problem if OS uses the TabularDataWithStrings part of the SQL file. I assumed OS was only using the other parts which should be unaffected by the InchPound field.

**Comment by DavidGoldwasser** [comment]
@ljbrackney my post about this wasn't really clear. What I want is for our installer and core code not to have any measures (standard report, radiance, etc). It should point to a BCL node, and when the installer runs, or when the app is launched the first time, it populates a the local BCL database. This would allow us to push update to these to users between releases. Current they are stuck with what is in the installer. 

I've tested measures that download other measures from BCL, and populate the local BCL, and the current API allows this to be done anonymously. So this wouldn't force users to make a BCL account to get these measures.

**Comment by DavidGoldwasser** [comment]
@macumber will C++ queries into the SQL data also be messed up by this. Does it check what units they are or does it assume IP?
https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-1.10.0-doc/utilities/html/classopenstudio_1_1_sql_file.html

**Comment by macumber** [comment]
Yes David, tabular data in the SQLFile is affected by this, that is why this is an issue.

**Comment by DavidGoldwasser** [comment]
FYI - I do have a check in current measure that throws warning if OS reported area doesn't match E+. That was made for other reasons such as stacked spaces, but would catch this. Problem is isn't really easy in APP to see info and warning messages.
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/pat_app/Measures/StandardReports/resources/os_lib_reporting.rb#L268-L273

**Comment by DavidGoldwasser** [comment]
Assigned to @macumber but don't expect to see this implemented until PAT 2.0

**Comment by JasonGlazer** [comment]
I'm working on an EnergyPlus task to provide tabular output report reporting in multiple units for a single simulation. My SOW reads:

> The Subcontractor shall add the capability to provide dual unit system reporting in EnergyPlus.
> Although the actual design details of the new capability is to be reviewed by NREL, the
> Subcontractor shall consider having EnergyPlus writing hypertext markup language (HTML)
> output files in both international system (SI) and inch-pound (IP) units, and providing structured
> query language (SQL) outputs in SI units. The implementation shall consider the following user impacting requirement options:
> • Allow users to specify separate units for the HTML and SQL reports.
> • Always provide the HTML output in SI and in IP units (therefore, no user input required)

What would you like to see done now?

**Comment by DavidGoldwasser** [comment]
@jmarrec I think this ticket, had been addressed when Pat 2.0 came out. You improved the workflow when you updated the OpenStudio Results measure to support SI and IP. My main request moving forward in EnergyPlus I think is for someone to request an IP HTML report but still maintain SI units for the SQL file (tabular and time series data) as that SDK is expecting data to be in SI units.

**Comment by MatthewSteen** [comment]
This issue seems pretty stale and can probably be closed. Here are some high level thoughts...

__OpenStudio__

1. I don't like that the OS Reporting measure adds OutputVariables to the sim by default. I think that the standard off the shelf configuration for a new user running a sim should be the bare minimum in reporting, output variables (none), and sim time. @DavidGoldwasser maybe consider changing what sections of the reporting measure on `true` by default to avoid the OutputVariables or splitting the measure in two (simple and detailed)?

__EnergyPlus__

2. Having the EP tabular outputs in _both_ IP and SI would be nice. These are often included in the documentation for code compliance, LEED, etc. and requires the user to re-run the model to get the results in another units system. 

3. I don't have a good understanding of what EP is doing for unit systems in the various files (ESO, SQL, HTML, etc.), but from a design perspective at a high level it seems like a single unit system would make sense, which I think is what it does generally (using SI).

**Comment by JasonGlazer** [comment]
@MatthewSteen currently the SQL and HTML are in the same units depending on the EnergyPlus OutputControl:Table:Style Unit Conversion field (choices are None, JtoKWH, JtoMJ, JtoGJ, InchPound). 

Am I understanding correctly, is just being able to generate the SQL in SI no matter what the OutputControl:Table:Style Unit Conversion field shows enough to satisfy the needs of OpenStudio?

In that case, would another OutputControl:Table:Style field like "Keep SQL in SI units" with a choice of  yes or no, work?

**Comment by MatthewSteen** [comment]
I'll let the OS developers answer your first question. 

From a user's perspective, it's nice to keep the file sizes as small as possible. So I wouldn't want to double the SQL file size by having both unit systems. In contrast, IES VE outputs _all_ variables for a model so the model files, in my opinion, are way too large. However, I realize the convenience of not having to formally request variables and re-sun a model.

**Comment by DavidGoldwasser** [comment]
@kbenne and @jmarrec feel free to jump in, but I think the answer to Jason for these questions is both yes. We just want to keep SQL in SI, and having a new field to do that would work.

`Am I understanding correctly, is just being able to generate the SQL in SI no matter what the OutputControl:Table:Style Unit Conversion field shows enough to satisfy the needs of OpenStudio?

In that case, would another OutputControl:Table:Style field like "Keep SQL in SI units" with a choice of yes or no, work?`

@MatthewSteen regarding the default arguments for sections of the report that use time services variables, can look at that, but unlike older uses where arguments were hidden, they are exposed, so you can turn them sections off before you run, and it will remember that for future runs. When you turn off a section it also turns off any output requests for that section.

**Comment by JasonGlazer** [comment]
@DavidGoldwasser @kbenne @jmarrec @MatthewSteen @eringold 

I updated my fix very slightly. Instead of changing the changing OutputControl:Table:Style EnergyPlus input object, I'm adding a field to the Output:SQLite EnergyPlus input object which probably makes more sense.  Please take a look at the EnergyPlus NFP below

https://github.com/NREL/EnergyPlus/blob/UpdateUnitAndFileControlTabRep/design/FY2020/NFP-DualUnitReporting.md

Please let me know if any of you have any comments or suggestions.

**Comment by JasonGlazer** [comment]
I just posted a small update to the NFP that clarifies that the new field is only related to unit conversion for the tabular report portion of the SQL file.

**Comment by JasonGlazer** [comment]
I haven't heard any comments on this. I just posted the NFP announcement on the EnergyPlus #announcements channel on Slack. Should I make a broader announcement to the OpenStudio folks? and if so, what is the preferred method?

**Comment by eringold** [comment]
@JasonGlazer based on your revised NFP, if Output:SQLite TabularUnitConversion is 'None' and OutputControl:Table:Style Unit Conversion is 'InchPound', then the HTML file will be in IP and the SQL will be in standard SI, correct?

**Comment by JasonGlazer** [comment]
Yes, you are correct @eringold 

I am wild about "None" to indicated standard SI but that is what is done with the OutputControl:Table:Style object. It does represent no unit conversion so that is why it is "None"

**Comment by eringold** [comment]
In that case I feel like 'None' should be the default for Output:SQLite. Since OpenStudio and other interfaces only want the SQL in SI, but users may want the HTML in IP, if the user looks to OutputControl:Table:Style to change the HTML table units, they may also be breaking the interface reporting, unless the interface always overrides the Output:SQLite default.

**Comment by JasonGlazer** [comment]
@eringold I think that would change the default behavior too much for users, that is why I recommended just having the default being "UseOutputControlTableStyle" which would follow what ever unit conversion that is specified in the OutputControl:Table:Style object which is exactly what is done now. It is not a big deal but it seems more transparent for users. OpenStudio could just always force the value to "None"

**Comment by JasonGlazer** [comment]
@DavidGoldwasser and @kbenne do you want to try this branch with OpenStudio and see if it is working with the different units in the SQLite file?

https://github.com/NREL/EnergyPlus/pull/8474

Also, does OpenStudio use the "tables" shown in the SQLite file other than TabularData (ComponentSizes, ConstructionLayers, Constructions, DaylightMapHourlyData, etc..)? And should those have unit conversions done to them?

**Comment by jmarrec** [comment]
When is E+ IOFreeze? Like I told Edwin, trying it out with this E+ branch isn't as trivial as just plugging the new E+ package in OpenStudio. We have to do the entire IDD transition with all changes since E+ 9.4.0, which is quite the effort.

**Comment by JasonGlazer** [comment]
Yes, I believe IO freeze is next week. 

@jmarrec what about my other question, do you know if the other tables in the SQLite file are they used by OpenStudio?

**Comment by jmarrec** [comment]
As far as I remember, openstudio uses tabulardatawithstrings (which is a view, but implies underlying tables...) for the reporting measure and the autosizedXXX method (to get the value of a field that is autosized after a run), and componentsizes in some cases as well.
There are also methods to get timeseries and daylightmaps that uses reportvariable and daylightmap.
Some tables in reporting measure are also getting stuff like window U value and co from the sql file, can't remember if it's from tabulardatawithstrings or directly from the construction tables.
I would try to grep on the codebase for select statements to make sure (on my phone now).

Generally speaking I think it would be very confusing to have some tables in SI and others in IP in the same sql file. It should be all or nothing

**Comment by jmarrec** [comment]
If that doesn't help or only partially, let me know @JasonGlazer and I'll try to provide better info in the AM tomorrow

**Comment by jmarrec** [comment]
This is very stale. The OpenStudio Results measure supports IP now.
