### ISSUE TITLE
Reorder design alternatives in PAT for reporting

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2044]
Reported by @egillmor  

DLM - I’m not sure what you mean here, are you talking about reordering the rows in the results tab of PAT?  You want to be able to change the order in which results are shown in the grid (so you can show the proposed next to the baseline for instance)?  Would you want to be able to manually order these, sort them (from highest to lowest energy savings), or hide particular results (but not necessarily delete the datapoints)?  Also, do you care about the order of results in the XML export?  These features may or may not be possible to implement in PAT 1.0 but we can get them on the radar for PAT 2.0 for sure.   

EG -  Yes.  Ideally the results AND the list of design alternatives should have to ability to be moved around.  I want to be able to reorder, delete, hide, add, etc. and do it however the heck I want, NOT be automated in any way.  Is has to do with the xml and how it looks in EDAPT.  I like to present things to clients in a particular order to make an effective presentation.  And if the report shows a different order from EDAPT, it confuses Xcel and they ask us to fix it.  Also, if I decide I want to add a design alternative, or maybe I forgot one (highly likely), I might not want it to show up at the end up the list.  Currently we can reorder measures (and I'm not sure what the point of that is), but not design alternatives.

**Comment by asparke2** [comment]
PAT 1.X issue, no longer relevant.

**Comment by aaron-boranian** [comment]
Allow reordering design alternatives

Problem: Right now you can’t reorder the design alternatives, which would be a nice feature in order to have a table that makes sense in the end. This is especially true when you have a lot of design alternatives and click “Create one for each” and end up with a lot of things that might actually not be in the right order.

Solution: allow reordering

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/13830972)
