### ISSUE TITLE
PAT datapoints with comma's in name fail to run

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2055]
Reported by @egillmor

**Comment by macumber** [comment]
![untitled](https://cloud.githubusercontent.com/assets/1327850/12722892/420983bc-c8c4-11e5-93a3-d556f689af5e.png)

**Comment by eringold** [comment]
Related to https://github.com/NREL/OpenStudio/issues/1597?

**Comment by macumber** [comment]
Maybe, there are [several comma related bugs](https://github.com/NREL/OpenStudio/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+comma)

**Comment by macumber** [comment]
I am not able to reproduce this either, @egillmor can you reproduce this bug with a simple project?

**Comment by egillmor** [comment]
Yes.  Create a run from an external file.  Add a user-defined measure name with commas in it.  Fails every time.

![image](https://cloud.githubusercontent.com/assets/16869106/13410400/cd7f1e8e-def4-11e5-9a9d-be3fdfe04d14.png)

**Comment by eringold** [comment]
I've found this happens because the name of the User Defined Measure is set as the name a Life Cycle Cost idf objects created in the run. Since the name has a comma, it messes up the idf syntax.

**Comment by macumber** [comment]
That is exactly what is happen @eringold , thanks!

**Comment by eringold** [comment]
@macumber we just ran into another problem, possibly related to this issue. A string with a newline character was copied into the User Defined Measure name field, which then becomes the name of a LifeCycleCost object. Something within EnergyPlus then replaces the newline with a comma, which caused the object to fail because where the first numeric field should be now has a alphanumeric string. Is it possible to add `\n` to your encoding check? 

PS i'm not sure how that character ended up in the string; possibly it came from excel.

**Comment by kbenne** [comment]
I have a corresponding pivotal issue on this and I see the branch has been merged. Can we close?

**Comment by macumber** [comment]
I think so, although it would be good for @asparke2, @DavidGoldwasser, @eringold or anyone else to test in 1.10.5 to confirm

**Comment by eringold** [comment]
Just tested with 1.10.5: Pat alternatives with user-defined measure names that include commas and newline characters run without issue. Seems to me that this can be closed.
