### ISSUE TITLE
change Fan Efficiency field to Fan Total Efficiency

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2059]
Can be confused with fan _impeller_ efficiency. EP uses Fan _Total_ Efficency for this field.

https://unmethours.com/question/14649/motor-efficiency-is-not-recognized/

**Comment by jmarrec** [comment]
+1

**Comment by DavidGoldwasser** [comment]
cc: @asparke2 would you want to just fix this, or would you want to allow user to inter impeller and motor efficiency, and then behind scenes we calculate total efficiency? That would of course move into being a feature vs. a bug fix.

**Comment by MatthewSteen** [comment]
@DavidGoldwasser @kbenne I'm happy to give this a try if the consensus is a simple name change, which is my preference over deviating from EP.

**Comment by kbenne** [comment]
I'm not in support of an outright name change. That would break any and all measures or other consumers of the API. We try to make a pretty strong commitment to keeping our API stable. I think it is one of the major selling points of the OS API in the first place. 

That said we can deprecate the current methods in favor of new synonym methods. 

Note that the reason OS uses a different name from E+ is because this is the name E+ originally used at the time the object was added to OS.

**Comment by kbenne** [comment]
+1 on @MatthewSteen giving it a go. I more than willing to help you get through the learning curve OS development.

**Comment by jmarrec** [comment]
If you don't mind I'd like to tag along. At the very least if you hold your conversation in a specific slack channel I could benefit from any advice Kyle gives to Matt.

Envoyé de mon iPhone

**Comment by MatthewSteen** [comment]
@DavidGoldwasser that would move away from how EP does things, so I personally wouldn't be in favor of that change.

kbenne I hadn't thought about (or appreciated!) the need for consistency in the API. Good point and background.

If there's a consensus among the developers that changing `fanEfficiency` to `fanTotalEfficiency` would be a worthwhile improvement I'm happy to give it a try.

**Comment by DavidGoldwasser** [comment]
@MatthewSteen I'm fine with that approach.

**Comment by jmarrec** [comment]
I'd like to revisit this, as I often have to explain this specific point to others or catch such mistakes in other people's models.

Couple of points:

* At least we should change the IDD field description so that users aren't confused. This would only change that description here:

![image](https://user-images.githubusercontent.com/5479063/42694100-7d371d0c-86b1-11e8-91c5-ee115aa4de0a.png)


* As far as the method name goes, we can just rename to `totalFanEfficiency` and keep `fanEfficiency` in the public API that forwards to the `totalFanEfficiency` with a deprecation message. It's not uncommon in the code base.

All in all that's an easy change, and
