### ISSUE TITLE
air loop diagram

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2098]
@kbenne I suspect this might have been introduced in your dual duct work, OS 1.10.4:

![image](https://cloud.githubusercontent.com/assets/8397034/13302163/b89c984a-db05-11e5-907c-39d9cae3f573.png)

**Comment by kbenne** [comment]
sure was. I have battled that problem once already while i was developing.

**Comment by MatthewSteen** [comment]
Also, when adding an empty air loop.

![image](https://cloud.githubusercontent.com/assets/8397034/13465006/e8bdd8fe-e050-11e5-9352-13470678882a.png)

**Comment by kbenne** [comment]
It does look a little odd, but that is how it is built when you add an empty dual duct. Maybe we need to change this since it seems to catch everyone I have demoed to so far. Drop a dual duct terminal on the demand side and things will make more sense. The API allows the supply and demand side to become dual duct independently.

**Comment by MatthewSteen** [comment]
My mistake, didn't notice that there's now an add empty air loop specifically for dual duct.
