### ISSUE TITLE
OS:ZoneAirContaminantBalance not translated

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2109]
It appears that this issue is back based on this [unmethours post](https://unmethours.com/question/15137/cannot-enable-co2-concentration-calculation-in-openstudio/) from Tiejun Wu. I confirmed the issue in 1.10.0. The OS:ZoneAirContaminantBalance object shows up in the .osm, but not in the exported IDF. Also, for this particular object, the string input field is no go; should really be a dropdown.

**Comment by macumber** [comment]
Moved from https://github.com/NREL/OpenStudio/issues/1730#issuecomment-190863873

**Comment by macumber** [comment]
I don't think there is a translation issue, just the GUI problem showing a text field instead of schedule drop down

**Comment by jmarrec** [comment]
Tested in OS 2.2.1. I can see the resulting object in the idf:

```
ZoneAirContaminantBalance,
  Yes;                                    !- Carbon Dioxide Concentration
```

Also confirmed that today the schedule still is a text field. The issue is ill-named.

@macumber can you rename this issue to "ZoneAirContaminantBalance Outdoor Carbon Dioxide Schedule Name should be a schedule selection box" or something like that?
