### ISSUE TITLE
add Unassigned choice to Spaces tab Space Type filter

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2112]
Like the Story and Thermal Zone filters have. 

Perhaps [here](https://github.com/NREL/OpenStudio/blob/a477c2f00aa05e37813d0aedab3ddbaf8d2881be/openstudiocore/src/openstudio_lib/SpacesSubtabGridView.cpp#L366) @evanweaver.

**Comment by jmarrec** [comment]
Fixed in #2815.

Here are 4 spaces, one of which doesn't have a space type assigned:

![2112_spacetype_filter_for_spaces_1](https://user-images.githubusercontent.com/5479063/31218606-29298dd6-a9bb-11e7-815b-3fc9268207c9.png)

I can now filter by "Unassigned" and it correctly returns the one space:

![2112_spacetype_filter_for_spaces_2](https://user-images.githubusercontent.com/5479063/31218620-329e825e-a9bb-11e7-9c57-474693ce4056.png)
