### ISSUE TITLE
Rename Fan Constant Volume object attribute "FanEfficiency" to "FanTotalEfficiency"

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#2167]
Careful comparison of Energy+.idd, EnergyPlus Engineering Reference and Input Output Reference documents reveals that the OS method "setFanEfficiency" maps 1:1 to the E+ object field "Fan Total Efficiency".

As such, the OS method naming is both inconsistent with Energy+ field names and also can easily be misconstrued by practicing energy modelers. 

Current naming of OSFanConstantVolume object attribute of "FanEfficiency" implies to this user that this is the "shaft to air" efficiency - regardless of the motive force operating the shaft. This efficiency can be easily determined from fan selection software or published fan performance data tables. However, correct application of this attribute requires it to be the product of "shaft-to-air" efficiency and "motor efficiency". 

The same issue appear to be relevant to OSFanOnOff and OSFanVariableVolume component objects as well.

**Comment by eringold** [comment]
@chrisbalbach same as https://github.com/NREL/OpenStudio/issues/2059?

**Comment by kbenne** [comment]
This is because E+ field names have moved since the object was introduced in OS. If we change the name we break our API and an unknown number of Measures.

Lately I have taken to at least commenting in the documentation when a field changes. Generally this is part of the process of doing an E+ upgrade to OpenStudio. That doesn't help from the user interface though. I think the ultimate solution is going to be two things. 1) introduce synonym methods where we can. 2) link to the documentation for that field from the UI.

**Comment by asparke2** [comment]
Closing this issue.  Current code follows the convention OS has established of not changing the API when E+ changes the IDD field names.
