### ISSUE TITLE
Translate all coils supported by the IDD in AirLoopHVACUnitarySystem

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2172]
In the [OpenStudio IDD](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/resources/model/OpenStudio.idd#L8927), the AirLoopHVACUnitarySystem supports the `Coil*DXMultiSpeed` and `Coil*DXVariableSpeed` objects, but the [Forward Translator](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp) does not support them.

This is something that @khaddad hit for the NECB work, and something that @joseph-robertson is going to hit very shortly for Residential work.

I assume that when this object was added to OS, those coil types were not supported by E+, and when the OS IDD got updated, the forward translator did not.

**Comment by shorowit** [comment]
This is pretty critical for our residential work. Any chance of getting a proposed schedule for implementation? What can we do to make this high priority?

**Comment by dstuder** [comment]
This is also important for some work I'm involved with on the commercial side. A proposed schedule would be awesome.

**Comment by joseph-robertson** [comment]
@kbenne I updated to 1.12, and tried:

```ruby
air_loop_unitary = OpenStudio::Model::AirLoopHVACUnitarySystem.new(model)
air_loop_unitary.setSupplyFan(fan)
air_loop_unitary.setHeatingCoil(htg_coil)
air_loop_unitary.setCoolingCoil(clg_coil)
air_loop_unitary.setSupplementalHeatingCoil(supp_htg_coil)
```
where
```ruby
htg_coil = OpenStudio::Model::CoilHeatingDXMultiSpeed.new(model)
clg_coil = OpenStudio::Model::CoilCoolingDXMultiSpeed.new(model)
```
and I get the following errors:
* "Error detected in Object=COIL:HEATING:DX:MULTISPEED, name=DX HEATING COIL Field [Air Inlet Node Name] is required but was blank."
* "Error detected in Object=COIL:HEATING:DX:MULTISPEED, name=DX HEATING COIL Field [Air Outlet Node Name] is required but was blank."

cc @shorowit

**Comment by dstuder** [comment]
OK, I just tried this with 1.12.1 and have some more info to add to the conversation. First, it looks like multispeed cooling coils get hooked-up correctly. The node-connection issue seems isolated to the multispeed heating coil object. This seems consistent with the commit from @kbenne. 

However, when trying to add multispeed coils to an AirloopHVAC:UnitarySystem object, a UnitarySystemPerformance:Multispeed object is required. Currently, this object is not supported in OS. While technically possible to add it after-the-fact using an E+ measure, one also needs access to the last two fields in the AirloopHVAC:UnitarySystem object (Design Specification Multispeed Object Type, and Design Specification Multispeed Object Name), both of which are not accessible currently. Since these appear at the end of the object, I don't believe using .setString(#,"text") is an option. Should I put in a feature request to make those two fields accessible and another to add the UnitarySystemPerformance:Multispeed object?

@shorowit

**Comment by mbadams5** [comment]
@dstuder FYI #2297

**Comment by dstuder** [comment]
@mbadams5 Thanks. Is there an open ticket to solve the node connection issues for the multispeed heating coils as well? I wasn't able to find one.

**Comment by ljbrackney** [comment]
Who is the customer for this work?  Need to know for prioritization of proper fix versus workaround.

**Comment by shorowit** [comment]
@ljbrackney This is very important for our BPA and DOE work.
