### ISSUE TITLE
ThermalStorage categorys dont show in "My Model" on HVAC Tab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2266]
This prevents ThermalStorageChilledWaterStratified and ThermalStorageIceDetailed objects from being attached to more than one plant loop using the GUI.

I wrote a temporary measure for Tau, so the timing of this fix isn't critical.
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/replace_water_heater_mixed_with_thermal_storage_chilled_water/measure.rb

![screenshot 2016-06-10 09 28 14](https://cloud.githubusercontent.com/assets/4857055/15969656/3116608a-2eee-11e6-83f6-503c917cd43f.png)

![screenshot 2016-06-10 09 28 47](https://cloud.githubusercontent.com/assets/4857055/15969660/34770aea-2eee-11e6-89bc-b571b22f5fc7.png)

**Comment by eringold** [comment]
I don't believe this applies to [ThermalStorageIceDetailed](http://bigladdersoftware.com/epx/docs/8-6/input-output-reference/group-plant-equipment.html#thermalstorageicedetailed) which has a single set of inlet/outlet node connections. 

See also https://github.com/NREL/OpenStudio/issues/2152

**Comment by jmarrec** [comment]
Fixed in #2815.

First I drag a `ThermalStorage::ChilledWater:Stratified` tank from library to a plant loop.

![2266_2152_thermalstorage_my_model_1](https://user-images.githubusercontent.com/5479063/31218282-244deb64-a9ba-11e7-96e5-e354fdb57f52.png)

I can see the tank I created in my model:

![2266_2152_thermalstorage_my_model_2](https://user-images.githubusercontent.com/5479063/31218391-726c07ae-a9ba-11e7-92b5-9ec303e8b49d.png)

And I can drag it to my other plant loop:

![2266_2152_thermalstorage_my_model_3](https://user-images.githubusercontent.com/5479063/31218402-78fab3ea-a9ba-11e7-8ab8-e6b10c37b39a.png)

**Comment by macumber** [comment]
@jmarrec Thermal Storage - Ice Storage is missing from My Model list, is that intended?

**Comment by jmarrec** [comment]
Yes @macumber Ice Storage has two nodes only ([I/O](https://bigladdersoftware.com/epx/docs/8-8/input-output-reference/group-plant-equipment.html#field-inlet-node-name-1-001)), just inlet and outlet, so once it's dragged into your model once, there isn't a reason to drag it a second time.
