### ISSUE TITLE
Develop PlantEquipmentOperationScheme logic for ThermalStorage and develop logic to make unknown objects use uncontrolled scheme.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2275]
Currently need to use measure to create PlantEquipmentOperationScheme logic to use ThermalStorage. Use case trying now has it on the supply side of one plant loop and the demand side of another.

**Comment by jmarrec** [comment]
Is this still relevant today now that the PlantEquipmentOperationSchemes can be created in the API?

Additionally, if I look at https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePlantEquipmentOperationSchemes.cpp#L325

it should get wrapped in a PlantEquipmentOperationHeatingLoad.

I guess better default for CompType could be made by checking what kind of plant loop the tank is on the supply side of instead of defaulting to Heating. Is that what you want @DavidGoldwasser ?

**Comment by DavidGoldwasser** [comment]
@jmarrec I think that was the case. I was trying to help someone add thermal storage at the time, and while thermal storage was in the GUI, there was a way to get the proper controls from the GUI. If defaults can handle it then no changes necessary in the GUI.

**Comment by jmarrec** [comment]
@kbenne please close per #2851
