### ISSUE TITLE
AirLoopHVAC:UnitarySystem Feature Request

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#2296]
I'd like to request the ability to manipulate the “Control Type” parameter in the AirLoopHVAC:UnitarySystem object. While the object itself is already wrapped, that specific parameter doesn’t appear to be. Thanks.

**Comment by jmarrec** [comment]
That shouldn't hard to change in the source code, and yes it's annoying. As a temporary workaround you can call setString... `unitary.setString 2, 'SetPoint'`

**Comment by kbenne** [comment]
If the unitary is wrapping a single coil then everything is pretty straightforward. It is as easy as @jmarrec points out. If there are multiple coils inside the unitary that you want to have on setpoint control then it is tricky because those nodes "inside" the unitary are not created until translation to idf. 

Still. I'm in favor of exposing the controlType parameter.

**Comment by jmarrec** [comment]
in #2815, I exposed the public `controlType()` (and related `setControlType()`, `isControlTypeDefaulted()` and `resetControlType()`), and wrote a Gtest for this.

I exposed the field in the OS App:

![2296_unitarysystem_controltype_1](https://user-images.githubusercontent.com/5479063/31218134-a49b9a1a-a9b9-11e7-9938-e37f002f5bbf.png)


Loading the model I saved in OS App, I can confirm it worked:

![2296_unitarysystem_controltype_2](https://user-images.githubusercontent.com/5479063/31218138-a9b0ae96-a9b9-11e7-976d-03db1dbe94ed.png)

**Comment by aaron-boranian** [comment]
Allow setpoint control within the AirLoopHVAC:UnitarySystem.

This would be helpful for DOAS systems where the airloop is serving multiple zones.

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9565998)
