### ISSUE TITLE
Missing Objects in EnergyPlus Forward Translator

### ISSUE THREAD

**Issue by chriswmackey** [NREL/OpenStudio#2304]
Greetings Beloved OpenStudio Team!

I believe that I have found three OpenStudio objects/attributes that are currently a part of the SDK and I can write them into OSM files using the SDK but they do not make it into the final IDF after I send the model through the forward translator.  As a result, I am inclined to think that they are missing from the EnergyPlus Forward Translator.  I could not find any other issue relating to these objects and the forward translator on this github so I am posting them here for your reference.

They are as follows:
1) Holidays - I noticed that there are now [RunPeriodControlSpecialDays](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-1.12.0-doc/model/html/classopenstudio_1_1model_1_1_run_period_control_special_days.html) objects in the SDK, which has allowed me to write holidays into the OSM.  However, none of these holidays seem to make it to the final IDF.

2) Number of Vertices in Surfaces - I see that the [Surface Class](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-1.12.0-doc/model/html/classopenstudio_1_1model_1_1_surface.html) includes a setter to   setNumberofVertices().  I am able to set the number of vertices in the OSM but this field does not seem to make it to the IDF.  As an optional input, I understand that the support for this parameter is not critical.  Still, I imagine that it might reduce the runtime if we tell E+ the number of vertices ahead of time.

3) Set the Start Day of the Week - I use the following to try to set the start day of the week in the OSM:

```
import OpenStudio
model = OpenStudio .Model()
yearDesc = OpenStudio.OpenStudioModelSimulation.getYearDescription(model)
yds = model.getObjectsByType(ops.IddObjectType("OS:YearDescription"))
yds[0].setString(2, 'Monday')
```

This changes the start day in the OSM file but invariably the IDF always starts with Thursday.

I am using C# bindings and I can send some examples over if you need them to recreate the issue.

Thanks, as always, for the wonderful software!
-Chris

**Comment by macumber** [comment]
1) Holidays are currently filtered out when translating from OSM to IDF.  This was to prevent confusion because holidays are not shown in the OS App GUI.  There is a special flag on the EnergyPlus ForwardTranslator, [setKeepRunControlSpecialDays](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator.hpp#L380).  If you are explicitly translating then this might help you.

**Comment by macumber** [comment]
2) I am not sure if there is a performance impact of this field in E+.  If there is then maybe we should start using it?  If you do any testing and see a performance impact I'd be interested to see it!

**Comment by macumber** [comment]
3) Your code seems like it should work, have you checked the return value of `yds[0].setString(2, 'Monday')` it will return false if it fails.  Also, have you tried doing:

```
yearDesc = OpenStudio.OpenStudioModelSimulation.getYearDescription(model)
yearDesc .setDayofWeekforStartDay("Monday")
```
It is better to use the OpenStudio Model methods instead of brute force setString because there can be logic built into the Model API that is bypassed with setString.  For example, [this logic](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/YearDescription.cpp#L177).  If you have a calendar year set then you can't specify the start day of week.

All of this date stuff is getting cleaned up next year since E+ is going to improve its own handling of dates, times, and years.

**Comment by chriswmackey** [comment]
@macumber ,

Thank you for the prompt reply and all makes sense.  My only lingering questions are with regard to the 3rd one.  Just to respond to all:

1) I figured that the Holidays issue was because they were recently added and had not made their way into the interface and (consequently) the IDF.  I will keep my workaround that writes them into the IDF after forward translation until there is full OpenStudio support for them.

2) I am not sure of any performance impacts of specifying the number of vertices and I will let you know if I get the chance to test it.   I understand it's not a critical feature and it should be a low priority. 

3) As for the Year Description, your suggested code runs without error and I can use that instead of the other code.  However, running either of these scripts does not change anything in the OSM file, it does not change the FirstDayOfYear when I open the file in the OpenStudio interface (it's always 'UseWeatherFile'), and the start day of week in the forwarded IDF is invariably 'Thursday' in the cases I have tested.  I am not sure what is going on here and let me know if you would like me to upload some examples.

Thanks again and stay awesome!
-Chris

**Comment by macumber** [comment]
It looks like YearDescription is not being exported to C#:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/ModelSimulation.i#L17

I have no idea why this is, maybe we can try removing this code?

**Comment by macumber** [comment]
https://unmethours.com/question/4770/how-to-set-day-of-week-for-start-day-using-c/

**Comment by chriswmackey** [comment]
@macumber ,

 Thank you, as always, for the response.  Now I remember that I got that code at the top of this issue from somewhere important :).  It would be great if we could avoid the need to use the setString() method but the bigger issue seems to be that even setString() does not ensure that the start day of the year is written into the IDF (although the method still runs without producing any SWIGTYPE errors).

Thanks again,
-Chris

**Comment by macumber** [comment]
The YearDescription object is being translated to E+ in the RunPeriod object, the code is here:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateRunPeriod.cpp

Basically, the YearDescription object is asked to make January 1, it will use the Calendar Year if set otherwise it will use the Day of Week for Start Day.  If you are using setString to set Day of Week for Start Day you may also have to reset Calendar Year to an empty string because Calendar Year always overrides Day of Week for Start Day.

The translator code that assumes the simulation starts on 1/1 is bad too, but we will address that when EnergyPlus updates its RunPeriod object in the next release.

**Comment by chriswmackey** [comment]
@macumber ,

I realized that I need to revise what I have been saying here.  The issue is not that the start day of the year does not make it into the final IDF.  It does make it there and it also makes it into the .osm and shows up in OpenStudio interface.  It's just that, when I use the setString() method, it triggers almost all of the schedules to be blank in the translated IDF as you see here:
![image](https://cloud.githubusercontent.com/assets/5567574/17306002/9970ebce-57fb-11e6-8dbe-c760c9462bcf.png)

As a result of the blank schedules, the IDF can't run through E+.  Let me know if you have any explanation for this.

Also, checked the .osm that is generated after using just the setString() method and the Calendar Year string is already a blank string.  So it appears everything is working except for the blank schedules.  Again, I apologize for not being more specific about the error earlier.  I think that I was just too anxious to lump several issues into one that I mis-reported it as not going into the IDF when it was.

-Chris

**Comment by macumber** [comment]
Oh geez, that is bad.  Let's make a separate issue for that, do you have an OSM you can send to help reproduce this?

**Comment by chriswmackey** [comment]
@macumber ,
I opened a [new issue](https://github.com/NREL/OpenStudio/issues/2322) and you can find a sample OSM with the error there.
-Chris

**Comment by chriswmackey** [comment]
@macumber ,
Sounds good and thanks for the support.
