### ISSUE TITLE
Enable autosizing of LowTemperatureRadiant:ConstantFlow inputs

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2344]
LowTemperatureRadiant:ConstantFlow inputs 'Hydronic Tubing Length' and 'Rated Flow Rate' are autosizeable per EnergyPlus idd, however the OpenStudio edit pane (as of v1.12.2) only takes numerical inputs for these fields, and does not have the option to autosize.

**Comment by macumber** [comment]
@kbenne should this be in 1.14?

**Comment by MatthewSteen** [comment]
The [Rated Flow Rate field should be autosized during forward translation](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACLowTempRadiantConstFlow.cpp#L160) rather than setting it to a non-existent double. The blank value in EnergyPlus is interpreted as zero flow leading to low energy consumption and high unmet load hours (i.e. it doesn't work). Tested it by changing the `RadLoTempCFloHeatCool_AddedAutosizing` example file fields to blank and comparing to the original.

```
  //field Rated Flow Rate
    if( (value = modelObject.ratedFlowRate()) )
    {
      idfObject.setString(ZoneHVAC_LowTemperatureRadiant_ConstantFlowFields::RatedFlowRate,"Autosize");
    }
```

**Comment by jmarrec** [comment]
Fixed today, via https://github.com/jmarrec/OpenStudio/commit/cc981cc9b0330000b31a325c282fe3ee6a4345cb in particular.
