### ISSUE TITLE
ChillerElectricEIR forward translation issue

### ISSUE THREAD

**Issue by mleach-noresco** [NREL/OpenStudio#2350]
Attn: @kbenne 

There is a method in the API to set condenser type (setCondenserType) but it isn't hooked up to anything.  Currently, the forward translator sets the field to WaterCooled if the chiller is connected to a condenser loop and to AirCooled otherwise.  There is also an EvaporativelyCooled option, which cannot currently be set.  This should be easily fixed by checking if the user set this field before doing the automated assignment described above.

Thanks,
Matt Leach
mleach@noresco.com

**Comment by macumber** [comment]
@kbenne should this be in 1.14?

**Comment by jmarrec** [comment]
Fixed in #2825.

Handle the "smart" logic of chiller condenserType in the model rather than the forward translator, in order to allow for "EvaporativelyCooled" option.

The behavior is as follows:

Defaulting when connecting/disconnecting from PlantLoop:

*  If you connect the chiller on a `secondaryPlantLoop` (demand side), then the `condenserType` automatically set to `WaterCooled`.
* If you disconnect the `secondaryPlantLoop`, it switches to `AirCooled"`

Error checking when calling `setCondenserType` directly:

* If you call the `setCondenserType(string condenserType)` method directly, if you specify `AirCooled` or `EvaporativelyCooled`, it will only work if no `secondaryPlantLoop` is attached.
* If you specify `WaterCooled`, it will only work if you actually have a `secondaryPlantLoop` attached.

**Comment by jmarrec** [comment]
@kbenne please close as #2825 got merged.

**Comment by macumber** [comment]
@kbenne can you close this?

**Comment by jmarrec** [comment]
@kbenne ?

**Comment by jmarrec** [comment]
@kbenne?
