### ISSUE TITLE
Mac specific issue with multiple versions of standards gem

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2352]
@macumber and @asparke2 I know we talked about this, but hit it again last night, and didn't see it documented anywhere.

The issue is that different versions of OpenStudio install different versions of the openstudio-standards gem on the system ruby. They don't play nicely together, and measures such as the create DOE prototype measure fail. My work around has been to manually uninstall all versions of the gem prior to installing a new version of Openstudio.

I see three possible solutions
1. Have the installer un-install all versions of the gem for me
2. Have the app more aware of what gem version it needs to use, and call that specific
3. Don't use system ruby, use unique ruby install for each OpenStudio installation. 

Any thoughts?

**Comment by macumber** [comment]
I don't think any version of OpenStudio installs gems into your system ruby, are you sure that is the case?

@kbenne

**Comment by macumber** [comment]
Each version of OpenStudio 1.x should install it's own version of Ruby with the gems installed to that only, the OpenStudio App will use the bundled copy of Ruby.  External gems can be required using the environment variables

OpenStudio 2.x embeds gems into the CLI itself, 2.x cannot currently require external gems

**Comment by asparke2** [comment]
The correct answer is 3....  However, the bigger issue here is that the Mac App isn't using the built-in Ruby, it is using the system Ruby.  In fact, the built-in Ruby that we ship with Mac won't even load the OS bindings.  This has apparently been true for quite some time, but has been masked because Scan for Tools always found the system Ruby and things worked. When we discovered this during the process of adding the standards gem, the decision was made to instead do a workaround and add this https://github.com/NREL/OpenStudio/blob/develop/DarwinPostFlight.sh.in#L10 to the installer to make the Mac system Ruby know about the standards gem, with the thought that this would only be a temporary thing until 2.0 came out.

The way that Ruby works, it will load the highest known version of a gem.  1.12.0 installed gem v 0.1.3, and 1.12.? installed gem v 0.1.4.  In this case, 1.12.? should work fine, but if you go back to 1.12.0 it will load gem 0.1.4 (added by the newer OS installer), and this will not work.

What we want to do about this I don't know, but the right option (fixing the Ruby bindings and the Mac Scan for Tools) didn't fly for some reason last time, so don't imagine it will fly now either.

**Comment by macumber** [comment]
Ah, so this is an issue for Mac only?

**Comment by asparke2** [comment]
Yeah, and only is an issue if you try to use an older version after installing a new one.

**Comment by asparke2** [comment]
Closing this.  Not relevant as of 2.0.0
