### ISSUE TITLE
Incorrect Zone Volume in Outdoor Air - OpenStudio report

### ISSUE THREAD

**Issue by geraldopithon** [NREL/OpenStudio#2360]
OS 1.11 
In Outdoor Air - OpenStudio report, the Zone Volume is different from Outdoor Air Summary - EnergyPlus report. I think the OpenStudio report is wrong.

![energyplus report - bug](https://cloud.githubusercontent.com/assets/21069897/18889933/8e026d88-84d5-11e6-81ca-07683f38c379.JPG)
![openstudio report - bug](https://cloud.githubusercontent.com/assets/21069897/18889934/8e05a62e-84d5-11e6-86d1-ba10351b90f4.JPG)

**Comment by MatthewSteen** [comment]
#127 - https://github.com/NREL/OpenStudio/issues/127

**Comment by DavidGoldwasser** [comment]
@MatthewSteen #127 is more about the raw volume calculation method being different that may affect complex geometry. The issue here is that the E+ tabular output has been switched to IP units vs. the expected SI units. The ACH values shown were not affected because there is no unit conversion, but the volume was. OpenStudio thinks the volume of the first zone is 17,970 m^3, in which case the IP value would be 364,636 ft^3.

**Comment by DavidGoldwasser** [comment]
Added this while making some other minor fixes to standard report. 1.13.1 and later will refuse to run the standard report if units are wrong.

![screenshot 2016-10-04 14 21 16](https://cloud.githubusercontent.com/assets/4857055/19090980/0858aa94-8a3e-11e6-95ac-d25191c95d1e.png)

cc: @macumber @asparke2
