### ISSUE TITLE
OpenStudio Measure test templates don't work in 2.x

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2368]

**Comment by shorowit** [comment]
Following.

**Comment by DavidGoldwasser** [comment]
I'm going to make few fixes to this on a branch. One of the fixes affects the use of the measure in the GUI vs. the tests.

- [ ] put copy of epw in tests folder and point to that instead of WeaterData (which doesn't exist on mac)
- [ ] remove reference to web_asset_path in report.html.in
- [ ] move model_in_path inside of individual tests since reporting measure tests often test differnt models. Changing epw is more of an edge case so that can stay outside of the tests.

- [ ] fix xml generaiton. Measure type is incorrectly showing as ModelMeasure instead of ReportingMeasure. Also the taxonomy  (Envelope.Form) isn't the correct default for reporting measures, it seems to be pulling from ModelMeasure default. GUI doesn't show it Envelope.Form.

**Comment by macumber** [comment]
@DavidGoldwasser can you verify if this is still open?

**Comment by DavidGoldwasser** [comment]
XML of new reporting measures (measure type and taxonomy) look good now and function in GUI.
