### ISSUE TITLE
OpenStudio 2 on Windows Installation Issues

### ISSUE THREAD

**Issue by mostaphaRoudsari** [NREL/OpenStudio#2420]
1. I get this warning for installing OpenStudio on Windows 8 and Windows 10.
![image](https://cloud.githubusercontent.com/assets/2915573/21534864/35cae6aa-cd3b-11e6-856f-1401c2442b16.png)

2. Not sure if this is intentional but the folder naming has changed for version 2.0.0. It used to be `OpenStudio 1.X.X` but now the default is `openstudio-2.0.0`. Also it installs to Program Files (x86) by default but I saw that is already included in known issue.

**Comment by macumber** [comment]
re 1: I was not aware of any signing we need to do for Windows 8 or 10, @axelstudios @kbenne FYI

re 2: I agree, I think the install path should be OpenStudio 2.0.0, I'll note that on the ticket about the install location

**Comment by ljbrackney** [comment]
This isn't a firewall issue on localhost is it?

On Dec 29, 2016, at 4:26 PM, Dan Macumber <notifications@github.com<mailto:notifications@github.com>> wrote:


re 1: I was not aware of any signing we need to do for Windows 8 or 10, @axelstudios<https://github.com/axelstudios> @kbenne<https://github.com/kbenne> FYI

re 2: I agree, I think the install path should be OpenStudio 2.0.0, I'll note that on the ticket about the install location

-

**Comment by mostaphaRoudsari** [comment]
@ljbrackney I think it has to do with the Unknown Publisher. I can install older versions of OpenStudio without this warning.

**Comment by ljbrackney** [comment]
This error was at install or run time?  If at run time, there were some major changes in 2.0 - some that need access to ports in the localhost that can require elevated permissions.  Most of those involve PAT, but I think the app may as well.

On Dec 29, 2016, at 6:24 PM, Mostapha Sadeghipour Roudsari <notifications@github.com<mailto:notifications@github.com>> wrote:


@ljbrackney<https://github.com/ljbrackney> I think it has to do with the Unknown Publisher. I can install older versions of OpenStudio without this warning.

-

**Comment by mostaphaRoudsari** [comment]
At the install time. I saw the run time issues already included in the release notes.

**Comment by chriswmackey** [comment]
@ljbrackney , @macumber , and @mostaphaRoudsari ,

I was able to install and run the [pre-release of OpenStudio 2.0.0](https://github.com/NREL/OpenStudio/releases/tag/v2.0.0) on my Windows 8.1 system without getting this issue.  However, I also have a new Windows 10 system that has this very annoying "Smartscreen" functionality, which believes that I am a 5 year-old and disables every other app that I install because it does not recognize the publisher.  I immediately disabled the terrible smartscreen using the method [here](http://winaero.com/blog/how-to-disable-windows-smartscreen-in-windows-10/).  I imagine that there are many others who do not want Microsoft to hold our hands while we use our computers and will also disable this.  However, I don't know if all other users of Windows 10 are going to be of this mindset.

It seems the only way to stop the smartscreen message from popping up for people who don't disable it is make NREL a registered publisher for the application and to have this publisher name included in the exe somewhere.

In the meantime, I recommend disabling Smartscreen @mostaphaRoudsari .

**Comment by kbenne** [comment]
@mostaphaRoudsari the install path is now (unfortunately) directly at C:\ and there are no spaces in the prefix. This is a requirement of PAT.

On the SmartScreen thing, the mystery to me is why you haven't seen this with other builds. We are going to post the latest this Friday and I'm hoping you can retest.

**Comment by asparke2** [comment]
@mostaphaRoudsari can you reconfirm or close this issue using OS 2.1.0 or higher installer?  None of us have Windows 10 here.

**Comment by mostaphaRoudsari** [comment]
Hi all, Sorry for the late reply. I didn't get the SmartScreen for OS 2.1.0 but another similar error.
I think the main difference between version 2.x and 1.x is the publisher.

![image](https://user-images.githubusercontent.com/2915573/26986282-cf113d9c-4d14-11e7-811f-663c0c5ae6f6.png)

**Comment by chriswmackey** [comment]
@asparke2 and @kbenne ,
I just wanted to second @mostaphaRoudsari 's explanation here and note that i's still possible to install OpenStudio 2.1 on Windows 10 if one disables Windows Smart Screen.  However, users will get this Smart Screen warning as long as the publisher continues to be "Humanity" instead of the "National Renewable Energy Laboratory."  This is because Windows recognizes the "National Renewable Energy Laboratory" as a registered publisher of safe software but it does not recognize "Humanity."

**Comment by kbenne** [comment]
Thank you for the investigation. I'll see if I can set the publisher. We are using a new packaging technology that in some cases is less capable, and in other cases just different.

**Comment by chriswmackey** [comment]
@kbenne ,
By the closing of this issue, am I correct in understanding that the new releases of OpenStudio will have NREL as the publisher instead of the current "Humanity"?
![image](https://user-images.githubusercontent.com/5567574/37247547-af8a7a30-248a-11e8-8950-1745e6d1a267.png)
