### ISSUE TITLE
Purge unused not working in Stories subtab

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2463]
OSApp v2.0, Windows. 

In 'Stories' sub-tab of 'Facility' tab, there is a purge unused button. It remains unusable by default, even when un-referenced stories exist in the model. The button _does_ become enabled when a building story row is selected with the check-box. However, when the button is clicked, **all** stories are removed.

**Comment by jmarrec** [comment]
Fixed in #2815.

Here are four spaces, notice that only "Building Story 1" and "Building Story 2" are used.

![2463_purge_stories_1](https://user-images.githubusercontent.com/5479063/31218762-9e78fc2a-a9bb-11e7-8e7e-112cadfdf4f6.png)

And here is the Building Story tab, you can see I have "Building Story 3" too which is unused, and the purge button is active.

![2463_purge_stories_2](https://user-images.githubusercontent.com/5479063/31218878-e67254c2-a9bb-11e7-9895-4c22c0c25daf.png)

After clicking the button, the unused building story (no spaces attached) has been purged:

![2463_purge_stories_3](https://user-images.githubusercontent.com/5479063/31218891-f4034402-a9bb-11e7-90e5-63ca39d14ee7.png)
