### ISSUE TITLE
Can't start Server when I install PAT at default location

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2492]
Last tested with 2.0.3. @kbenne not sure if any changes in 2.0.4.

Here is rails log
`/usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Permission denied @ dir_s_mkdir - /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/server/tmp (Errno::EACCES)
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:210:in `each'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/server.rb:134:in `block in create_tmp_directories'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/server.rb:133:in `each'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/server.rb:133:in `create_tmp_directories'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/server.rb:77:in `start'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
=> Booting WEBrick
=> Rails 4.2.0 application starting in local on http://localhost:8080
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting`

Error is avoided if I install here instead of default location. 
/Users/dgoldwas/Applications/openstudio-2.0.3

I don't think other internal Mac users have been seeing this.

**Comment by kbenne** [comment]
yeah i've been working with Ry on this. It looks like the root cause is out of our control, and I am going to need to change permissions so Pat can write files in its install directory.

**Comment by ljbrackney** [comment]
I always install in /Applications so I've never seen this behavior.

On Mar 1, 2017, at 7:37 AM, David Goldwasser <notifications@github.com<mailto:notifications@github.com>> wrote:


Last tested with 2.0.3. @kbenne<https://github.com/kbenne> not sure if any changes in 2.0.4.

Here is rails log
/usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:252:inmkdir': Permission denied @ dir_s_mkdir - /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/server/tmp (Errno::EACCES)
from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:252:in fu_mkdir' from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:226:inblock (2 levels) in mkdir_p'
from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:224:in reverse_each' from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:224:inblock in mkdir_p'
from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:210:in each' from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/fileutils.rb:210:inmkdir_p'
from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/server.rb:134:in block in create_tmp_directories' from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/server.rb:133:ineach'
from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/server.rb:133:in create_tmp_directories' from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/server.rb:77:instart'
from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in block in server' from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:intap'
from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in server' from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:inrun_command!'
from /usr/local/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/railties-4.2.0/lib/rails/commands.rb:17:in <top (required)>' from bin/rails:4:inrequire'
from bin/rails:4:in <main>' => Booting WEBrick => Rails 4.2.0 application starting in local on http://localhost:8080 => Runrails server -hfor more startup options => Ctrl-C to shutdown server Exiting

Error is avoided if I install here instead of default location.
/Users/dgoldwas/Applications/openstudio-2.0.3

I don't think other internal Mac users have been seeing this.

-

**Comment by kbenne** [comment]
Well that is useful information. I was pretty confident this would impact /Applications install too.

**Comment by DavidGoldwasser** [comment]
@ljbrackney I'll try your install location and see if #2493 goes away.

**Comment by kbenne** [comment]
@DavidGoldwasser I think I have nuked the issue with this...

https://github.com/NREL/OpenStudio/commit/ebe0c8a18285abfa8f3b21f0f0a578b09ec3c717

basically make pat os server install writable by anyone.
