### ISSUE TITLE
SketchUp Import Schedules - Hardcode path prevents accessing schedules in app

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#2502]
I'm having a hard time exactly pinpoint when this error does and does not occur. 

It happens to me in OpenStudio v.1.14 and v2.0.1 when I make geometry, use a template generator or load an existing model, and then try to load in schedules from another model using "Extensions -> OpenStudio -> Import -> Import Schedules".  The exception is thrown when I import schedules, save, the model, and open the model in the app, and try to access the schedules.  It generates this error:
![image](https://cloud.githubusercontent.com/assets/2249271/23563892/8609c95c-fffd-11e6-8f9f-0a34b9dce69c.png)
![image](https://cloud.githubusercontent.com/assets/2249271/23568236/78ade64c-000e-11e7-8a81-e252d1de454f.png)

**Comment by DavidGoldwasser** [comment]
What happens if instead you try to import the schedules from the OpenStudio Applicaiton. You can do this by using "Load Library" in the file menu, then the content of that file will show up in "Library" section at the right, and can be dragged into to schedule drop zones in the app. Doing that will clone it into the model. If you plan to use schedules in multiple places best option is to drag into schedules tab, then when applying it to objects, drag it from "My Model", otherwise you end up with duplicate copies of the cloned (imported) schedule.

**Comment by mdahlhausen** [comment]
Loading schedules in the OpenStudio App with "Load Library" works fine.  It is a Sketchup Plugin Error - The "Import Schedules" method in the SketchUp plugin breaks things most of the times I try to use it.  I'm thinking it has something to do with the hardcoded paths I'm seeing in the errors above?

**Comment by tijcolem** [comment]
This issue has been moved to the OpenStudio Sketchup Repository - https://github.com/openstudiocoalition/openstudio-sketchup-plugin/issues/23
