### ISSUE TITLE
Database backup on server returns an error

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2523]
Please make it work gooder.

**Comment by rHorsey** [comment]
FYI @ljbrackney this milestone should be 2.1.1

**Comment by ljbrackney** [comment]
mongodump.tar.gz downloads from the server have been working for a bit, but I tried uploading a tarball to both 24b and AWS without success.  The upload itself appears to work, but I believe it fails upon extraction or processing thereafter.

**Comment by rHorsey** [comment]
I redeployed 24b yesterday and upload / download works fine there. I believe you're hitting the same limitations imposed by compose as we're seeing.... in pivotal tickets, gah. On AWS we deploy with swarm, and we really should on bball as well. I'm working to transition us over to that locally. It's tested and implemented, but the takeaways aren't disseminated yet. The network becomes far more stable when we run everything through swarmkit, which saves us a lot of pain here. Have you seen this since 2.1.1 on AWS? If so, them this needs to stay open.

**Comment by ljbrackney** [comment]
I'm still using 2.1.0 so I can test/respond to user queries.  Perhaps someone on 2.1.1 could try a mongodump save/restore on AWS?

  - larry

**Comment by rHorsey** [comment]
@ljbrackney I'll test this next time I spin up a 2.1.1. The new (correct OpenStudio version) 2.1.1 AMI has a lot of fixes in it, which should catch what we were seeing locally, at least.

**Comment by macumber** [comment]
@ljbrackney can you test and close once 2.2.0 is out?

**Comment by ljbrackney** [comment]
Yes

**Comment by rHorsey** [comment]
This is working for me now. Can someone confirm?

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#250
