### ISSUE TITLE
Links to older SDK documentation

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2556]
It would be really helpful to have links to the SDK documentation for older versions of OpenStudio on the [documentation website](https://openstudio-sdk-documentation.s3.amazonaws.com/index.html). At the moment, it's really hard to find.

E.g., 
[1.14.0](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-1.14.0-doc/model/html/index.html)
[1.13.1](https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-1.13.1-doc/model/html/index.html)
etc.

**Comment by macumber** [comment]
If anyone wants to take a crack at updating that page and sending us an updated html we can take a look at it and post it

**Comment by jmarrec** [comment]
[index.txt](https://github.com/NREL/OpenStudio/files/903152/index.txt)

Done. I grepped all release tags from the github repo, and added a section on the index.html called "Documentation for older versions" that has a `<ul>` list, styled to display 6 columns, with all links to past versions.

**Comment by jmarrec** [comment]
Oops wait I put it on https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-2.1.0-doc/model/html/index.html without thinking. Been told it should be there: https://s3.amazonaws.com/openstudio-sdk-documentation/cpp/OpenStudio-2.1.0-doc/model/html/index.html

Gimme a minute

**Comment by jmarrec** [comment]
Here's the new version: [google drive](https://drive.google.com/open?id=0B6iX99bTtTWxRERXRWVURkdDZWc)

Added a third column to https://s3.amazonaws.com/openstudio-sdk-documentation/index.html with a dropdown to select the version, and then there's some jQuery to dynamically change the links in said column. When a new release appears, you just have to add a new `<option>vX.Y.Z</option>`.

![screen shot 2017-04-06 at 19 13 22](https://cloud.githubusercontent.com/assets/5479063/24770115/1d9329c8-1b09-11e7-8b40-cdbcab91478c.png)


Caveat: it assumes the namespaces have been the same since the beginning, apparently some like `measures` didn't exist until 2.0.0.

**Comment by macumber** [comment]
Fixed by @jmarrec and posted live!

**Comment by jmarrec** [comment]
For "fun" I created another version that doesn't require updating going forward. The HTML portion is empty save for some html tags since all is dynamic.

It queries the github api to get the latest releases and creates the entire table dynamically using jQuery. I also added ajax calls when you select a version using the dropdown to not provide links if they don't exist (example: "measure" namespace didn't exist before 2.0.0).
I added links to github release notes for each in the table head.

I doubt this is going to generate that much interest, but I posted a live version here if you want to check it out out of curiosity: http://test.effibem.com/. To test the url checker, use "1.13.1", you should only have one link for "radiance" since this is the only url that I added as a test.
