### ISSUE TITLE
Symlinked CLI cannot find EnergyPlus on Mac

### ISSUE THREAD

**Issue by nmerket** [NREL/OpenStudio#2561]
I am trying to use the OpenStudio CLI and it complains of not being able to find EnergyPlus unless I set the `ENEREYPLUS_EXE_PATH` environment variable. This only happens when I use the CLI that is symlinked into `/usr/local/bin/openstudio`. When I use the one in `/Applications/OpenStudio-2.1.0/bin/openstudio` it is able to find EnergyPlus just fine. 

If I run the following ruby script using the CLI (test.rb).

```ruby
puts "ENERGYPLUS_EXE_PATH = '#{ENV['ENERGYPLUS_EXE_PATH']}'"
ENV['ENERGYPLUS_EXE_PATH'] = nil
puts "ENERGYPLUS_EXE_PATH = '#{ENV['ENERGYPLUS_EXE_PATH']}'"
puts OpenStudio::openStudioLongVersion
puts OpenStudio::getOpenStudioModule
puts OpenStudio::getOpenStudioModuleDirectory
puts OpenStudio::getEnergyPlusExecutable
puts OpenStudio::getEnergyPlusDirectory
```

From the symlinked cli `openstudio execute_ruby_script test.rb`

```
ENERGYPLUS_EXE_PATH = '/Applications/OpenStudio-2.1.0/EnergyPlus/energyplus-8.7.0'
ENERGYPLUS_EXE_PATH = ''
2.1.0.fae436fc10
/usr/local/bin/openstudio
/usr/local/bin


```

From the full-path cli `/Applications/OpenStudio-2.1.0/bin/openstudio execute_ruby_script test.rb`

```
ENERGYPLUS_EXE_PATH = '/Applications/OpenStudio-2.1.0/EnergyPlus/energyplus-8.7.0'
ENERGYPLUS_EXE_PATH = ''
2.1.0.fae436fc10
/Applications/OpenStudio-2.1.0/bin/openstudio
/Applications/OpenStudio-2.1.0/bin
/Applications/OpenStudio-2.1.0/bin/../EnergyPlus/energyplus
/Applications/OpenStudio-2.1.0/bin/../EnergyPlus

```

@macumber

**Comment by jmarrec** [comment]
In the [CLI Doc](http://nrel.github.io/OpenStudio-user-documentation/reference/command_line_interface/) there is a section about "Environment Variables", reading it I have added this to my `~/.bash_profile`:

    export RUBYLIB=/Applications/OpenStudio-2.2.0/Ruby
    export ENERGYPLUS_EXE_PATH=/Applications/OpenStudio-2.2.0/EnergyPlus/energyplus-8.7.0

Isn't that enough? 



Then again, it shouldn't be to hard to check if it's a symlink and follow that. The problem is [moduleIsRunningFromBuildDirectory](https://github.com/NREL/OpenStudio/blob/201348982fdd4bc2cb40bc6628afe39d194d4ae0/openstudiocore/src/utilities/core/ApplicationPathHelpers.cxx.in#L214) which doesn't follow the symlink.


This is perhaps related to https://github.com/NREL/OpenStudio/issues/2616 too.

**Comment by jmarrec** [comment]
Confirmed that Kyle's fix in https://github.com/NREL/OpenStudio/commit/85247380ca682fabed2ea8921910f17ef83f2619 works:

Ran user script with 2.6.0:
```
ENERGYPLUS_EXE_PATH = ''
2.6.0.8c81faf8bc
/Applications/OpenStudio-2.6.0/bin/openstudio
/Applications/OpenStudio-2.6.0/bin
/Applications/OpenStudio-2.6.0/bin/../EnergyPlus/energyplus
/Applications/OpenStudio-2.6.0/bin/../EnergyPlus
```
