### ISSUE TITLE
PAT Project Measures Get Out of State

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2586]
It's fairly easy to get the installed project measures out of state with the UI/JSON through Save As or Cancel Save on Exit.  Process:

1) Open Project
2) Delete one or more measures
3) Save as or quit without saving
4) Reopen project later
5) PAT tab 1 indicates all measures are there, but they are no longer in the measures directory
6) Run results in data point failures with no useful feedback in the UI.  User must navigate down to temp/datapoint error logs to find that the measure wasn't uploaded.

The debug process is far too esoteric.  At a minimum, PAT should preflight check contents of the project folders against the PAT json and pop open a dialog saying the content isn't there.  Better would be to have a more robust save as/cancel save system that puts deleted content (most likely measures) in a parking lot directory for later restoration, but that's obviously more complicated.

**Comment by evanweaver** [comment]
After reviewing options with Kat, the following approach will be employed: When deleting a measure, a dialog will be displayed with the text "Are you sure you want to delete this measure? Deleting this measure will result in the saving of this project". The rationale for this approach is that it is robust and simple (ie. cheap). The other alternative we felt was appropriate, was much more involved and actually more akin to a new feature, rather than a bug fix. This alternative approach would be to sidecar any measure deletion from disk until the saving of the project (either on closing or explicitly by the user), but the synchronization with the JSON file appeared to be prohibitively expensive.

**Comment by ljbrackney** [comment]
Tested.
