### ISSUE TITLE
Failing to upload model in OpenStudio

### ISSUE THREAD

**Issue by Yalelush** [NREL/OpenStudio#2603]
Hi,
Upon trying to upload a simple model from Sketchup to OpenStudio, we encountered an error.
We used the diagnostic tool on user scripts, however we received the following message:
```

>>diagnostic test start

File - C:/Users/...try8-0.osm
Running OSM Diagnostic Script
Error occurred while running user script:
Optional not initialized (RuntimeError)

["C:/openstudio-2.1.0/SketchUpPlugin/openstudio/sketchup_plugin/user_scripts/Reports/OSM_Diagnostic_Script.rb:85:in `get'", "C:/openstudio-2.1.0/SketchUpPlugin/openstudio/sketchup_plugin/user_scripts/Reports/OSM_Diagnostic_Script.rb:85:in `run'", "C:/openstudio-2.1.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/PluginUserScriptRunner.rb:385:in `run_user_script'", "C:/openstudio-2.1.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/MenuManager.rb:943:in `block in add_user_script'", "SketchUp:1:in `call'"]
User script OSM Diagnostic Script completed with errors

>>diagnostic test start

File - C:/Users/..../try8-0.skp
Running OSM Diagnostic Script
Error occurred while running user script:
Optional not initialized (RuntimeError)

["C:/openstudio-2.1.0/SketchUpPlugin/openstudio/sketchup_plugin/user_scripts/Reports/OSM_Diagnostic_Script.rb:85:in `get'", "C:/openstudio-2.1.0/SketchUpPlugin/openstudio/sketchup_plugin/user_scripts/Reports/OSM_Diagnostic_Script.rb:85:in `run'", "C:/openstudio-2.1.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/PluginUserScriptRunner.rb:385:in `run_user_script'", "C:/openstudio-2.1.0/SketchUpPlugin/openstudio/sketchup_plugin/lib/MenuManager.rb:943:in `block in add_user_script'", "SketchUp:1:in `call'"]
User script OSM Diagnostic Script completed with errors

```
We would appreciate your help in understanding these errors and how to fix them.
We're using SketchupMake2017 and Openstudio 2.1.0.

Thanks!

**Comment by asparke2** [comment]
@DavidGoldwasser at minimum there is an untrapped call to `.get` in the diagnostic script.

@Yalelush we will need the .osm to reproduce the error and see what's going on.  Could you please upload here or send to us?  You can change the extension to .txt to upload here.

**Comment by Yalelush** [comment]
Thanks, I attached the file in text format.

[try12.txt](https://github.com/NREL/OpenStudio/files/1022990/try12.txt)

**Comment by DavidGoldwasser** [comment]
@Yalelush what happens if you try to manually open the OSM file in the OpenStudio application. For me (On mac with OpenStudio 2.1.1)  it opens in the OpenStudio application, in the SketchUp plugin, and the diagnostic script runs fine. I'm wondering if there is something windows or path specific in the diagnostic script error you are seeing.

> >>diagnostic test start

File - /Users/dgoldwas/Downloads/try12.osm
Model has 766 objects
Model has 0 thermal zones
Model has 1 spaces
Model has 6 base surfaces
Model has 0 sub surfaces
Model has 0 shading surfaces
Model has 0 interior partition surfaces

Removing catchall objects (objects unknown to your version of OpenStudio)
none

Removing objects that fail draft validity test
none

Surfaces with less than three vertices
none

SubSurfaces with less than three vertices
none

Surfaces with more than 25 vertices
none

Surfaces with area less than 0.1 m^2
none

Surfaces with area less than 0.1 m^2
none

Surfaces and SubSurfaces which have similar geometry within same surface group
none

Surfaces and SubSurfaces which have duplicate vertices
none

Removing sizing:zone objects that are not connected to any thermal zone
no orphaned sizing:zone objects were found

Removing ZoneHVAC:EquipmentList objects that are not connected to any thermal zone
no orphaned ZoneHVAC:EquipmentList objects were found

Removing PortList objects that are not connected to any equipment
no orphaned PortList objects were found

Removing LifeCycleCost objects that are not connected to any model object
no orphaned LifeCycleCost objects were found

>>diagnostic test complete
Running OSM Diagnostic Script
User script OSM Diagnostic Script completed

**Comment by Yalelush** [comment]
Hi David,
When trying to open the OSM file straight from OpenStudio, I received a message that this file cannot be opened.
"Failed to open file at .....[destination]"
What else can be done?
Thanks for the quick replies!
Yael

**Comment by jmarrec** [comment]
This issue has become very stale, so I'm closing it. If you encounter this problem again with a recent version of openstudio (eg 2.9.1), please let us know and I'll reopen!
