### ISSUE TITLE
App locks up on Results Tab in Windows 10

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2604]
https://unmethours.com/question/24372/openstudio-211-results-tab-unavailable/

User reports that report.html is created and viewable within the model folder, but attempts to view in the results tab locks the app.

**Comment by shorowit** [comment]
Just tried it on one of my models, and the results tab works fine using OS 2.1.1 on Windows 10. So might be specific to their model?

**Comment by ljbrackney** [comment]
Anyone else with Windows 10 experiencing this?  User reports that the HTML generates and displays correctly in browser but crashes the App for him.  Other users in his organization report a blank screen (but no crash) when navigating to the results tab.

**Comment by ljbrackney** [comment]
Info from User:

After upgrading to OpenStudio 2.1.0, followed by 2.1.1, I am no longer able to open the "Results Summary" tab in the OS interface on Windows 10 Pro whether I have a model open or not. I am able to run models successfully and view the results in the model folder, but the program locks up after clicking on the "Results Summary" tab. I have tried this with and without the "OpenStudio Results" measure and it does not seem to make a difference. I can access all the files I need, but it is inconvenient to have to dig them up in the folder structure. A coworker is running from the same OpenStudio install file on the same version of Windows and does not have the same issue. I am running on a Dell M3800 laptop, which has had graphics processor issues in the past, but upgrading drivers did not fix the issue.

![febe04ec-3add-11e7-8830-d73cc6088282](https://cloud.githubusercontent.com/assets/2230150/26160609/f665b744-3ade-11e7-8c09-1efc5f006e71.png)

**Comment by johnsontimp** [comment]
To update this issue, I found that the results tab works if I open the model from the Sketchup plugin. If I try to open it directly in the OpenStudio app, the results tab does not work.

**Comment by johnsontimp** [comment]
One more update on this issue. When opening through Sketchup, I can run simulations, but I have found all the objects in the zone and systems level tabs are missing. Those will load if I open the model directly in OpenStudio, but then I can't see the results tab. I have switched back to the 1.X versions of OpenStudio.

**Comment by macumber** [comment]
Believe this also affects the geometry tab, @shorowit just reported some intermittent issues

**Comment by johnsontimp** [comment]
Thanks to Andrew Parker, I was able to fix the issues with the results tab by overriding the 3D settings in my NVIDIA control panel to use the high-performance NVIDIA processor only rather than using the integrated graphics that somehow splits between NVIDIA and Intel graphics. This fixes the results tab but does not allow me to see the geometry preview.

**Comment by macumber** [comment]
Thanks @johnsontimp, just to make sure I understand correctly, you can see the geometry tab and can navigate to it, but when you are there you do not see a 3D model of your OSM?  What do you see?

I was able to install OpenStudio on a Windows 10 virtual machine but could not reproduce these issues.  That would make sense this really is a graphics card related issue.

**Comment by johnsontimp** [comment]
That is correct. When I click the geometry tab, it seems to go there and the refresh bar fills up like it is working, but when the bar is 100%, the screen is still blank. All I see is white. I don't get any error messages in the OpenStudio app. It may be worth checking with Andrew for troubleshooting. It sounds like the reason he knew what to do was because he has the same Dell M3800 laptop.

**Comment by macumber** [comment]
I'm going to try to enable some more detailed logging to see if that helps print out useful information, thanks for your help on this!

**Comment by johnsontimp** [comment]
Thanks to you and your team for being so responsive to these bugs. Let me know if you want to set up a Webex or something to see what is happening on my machine.

**Comment by macumber** [comment]
Seems like this is resolved?

**Comment by eringold** [comment]
Interestingly, I was having problems with the app (v2.3.0) locking up in the results tab on Windows 10, latest build. The results tab would load fine and I could navigate the OS Results report, but when I tried clicking back to other tabs everything would freeze, even to the extent where resizing the app window would stretch and distort everything in the view. I also have dual NVIDIA and integrated graphics on this Dell laptop, and had OS set to use the NVIDIA processor. However, when I switched the setting to have OS use the integrated graphics card, the issue was resolved.
