### ISSUE TITLE
Large Uploads to Server (i.e. lots of weather files) Seem to Timeout

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2606]
Reported by Scott: Error running ResStock national project

**Comment by rHorsey** [comment]
I've spent about 10 hours on this, and I'm nowhere. If you need more than 100MB of zip uploaded to the server, chances are that using worker or server initialization and finalization scripts makes more sense, for the sake of far more reliable hosting and streaming options; once I have the server/worker init/final scripts working I'll change the severity to Major, at least until the cause is identified.

**Comment by rHorsey** [comment]
Reducing to major bug. A workaround using worker-init scripts is currently implemented for deployment in 2.2.1

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#249
