### ISSUE TITLE
PAT starts more runs than cores

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2675]
I have a dual core i7 (2 cores, 4 threads). PAT displays that it started 16 runs when only 3 energyplus instances can be run at any time (the 4th thread is used by ruby)

![screen shot 2017-06-27 at 10 09 26 am](https://user-images.githubusercontent.com/5479063/27577432-ef31ba4c-5b20-11e7-80b2-e3544fe2a708.png)

**Comment by rHorsey** [comment]
Thanks @jmarrec for making an issue for this! I've seen this before on our still unstable large-scale (more than 200 thread) server deployments, but just tonight on one of our CI boxes. (https://travis-ci.org/NREL/OpenStudio-server/jobs/247794187) I'll try and take a look at this next week. I'm still not clear on what the impact of this is; I expected it to be catastrophic, but on our large deployments I think things finish as expected. Is that also your experience when seeing this bug?

**Comment by jmarrec** [comment]
In my case, I'm pretty sure the problem was from https://github.com/NREL/OpenStudio/issues/2673

**Comment by pachi** [comment]
Is this really wrong? The energyplus runs are indeed bounded by CPU use, but the overall OpenStudio run uses much more time doing IO, so this excess of parallelism should improve throughput as more CPU work can be done while waiting for IO.
In our experiments we use at least N+1 or N+2 project runs, where N is the number of CPU processes.

**Comment by jmarrec** [comment]
This is really wrong yes because in my case it launched 16 energyplus runs. 16 on a two core four thread machine. And energyplus, not ruby or something.
And the settings defined (default) are 3 threads for e+ and one for misc (server gem etc) on my machine so it shouldn't happen 

Envoyé de mon iPhone

**Comment by tabuimara** [comment]
I have the same issue , and the analysis process never completed since the update 2.2.0

**Comment by rHorsey** [comment]
The root cause of this issue has been identified as a limitation in the interconnection between mongo and delayed_jobs given the current use. We cannot reproduce this locally following 2.2.1, however we can reproduce this on AWS. It seems to be due to physical hardware limitations, indicating that local servers may be inadvisable on computers with less than 4 virtual CPUs. On cloud deployments, this issue will be patched as of the 2.3.1 release. To fully fix the issue requires provisioning a redis instance and moving from delayed_jobs to resque on AWS deployments, and will be implemented in December. Once 2.3.1 is released, this will be re-tagged as a minor bug, until the queuing system is overhauled.

**Comment by rHorsey** [comment]
This issue was moved to NREL/OpenStudio-server#244
