### ISSUE TITLE
Import Library while in Geometry Editor doesn't work

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2735]
Import library before creating geometry works fine.  Importing a library once you're in the editor doesn't work.

**Comment by macumber** [comment]
Is this a functionality you think we need?  I am already calling import library to get resources in the current osm into the initial floorplan.  Then each time you go back to the floorplan editor it should re-merge resources in the osm into the floorplan.  This lets you use the app's library features.  Do we really need to load external floorplans as libraries too?  I'd suggest hiding this button along with open and save

**Comment by ljbrackney** [comment]
I think you need this functionality for two reasons:

1) The import library function is in a menu outside of the geometry editor and always available.  This implies that if you select it that it has taken effect in the app.  You and I understand that the editor is not strictly "within the app," but that is a detail that the average user won't care about - nor should they have to.
2) When I get to the point of assigning space types and constructions in the editor - it's quite possible that I will realize at that moment that I want to import a library.  The obvious thing to do at that point?  See reason 1.

I know that's not want you want to hear, but it will quickly become a complaint for users.

**Comment by macumber** [comment]
There might still be confusion here, the import library button in the editor imports resources from another floorplan.json, it does not load resources from an osm.  I don't really want to highlight the floorplan.json format so that is why I'm not hot on this approach.  

For 1, we can disable some of the menu commands that don't make sense/aren't supported on this tab.

For 2, the intended action would be to go back to the space types tab and import the right space types.  This is annoying but shouldn't be worse than changing between any other tabs, problems would be if the merging/re-loading functionalities don't work.

**Comment by ljbrackney** [comment]
I'm not talking about the import button in the editor. I'm aware of what that button does, and we may want to get rid of that button from the UI.  That's an additional source of confusion that I wasn't thinking of when I opened this ticket.

I'm specifically talking about the Load Library option from the File pulldown menu.  I folks are using the tab-based workflow, they SHOULD have already loaded in their default construction and space type sets before they get to the geometry editor.  I'm just foreseeing a source of confusion.

**Comment by macumber** [comment]
Yeah, I think we should disable some of the app menus on that tab, including the import osm library.
