### ISSUE TITLE
Space load instances have non-editable fields in inspector

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2757]
Need to fully create fields so these are editable

**Comment by DavidGoldwasser** [comment]
@macumber Just out of interest, what is not editable? Is this about End-Use Subcategory, or are you wanting to change out definitions in the GUI without making a new load instance?

**Comment by macumber** [comment]
Lots of stuff is not editable, subcategory is one.  Need to create all the fields in model object ctor.

**Comment by DavidGoldwasser** [comment]
Ah, I see for specific instances types like people. Some or not editable and others like work efficiency schedule are missing.

**Comment by jmarrec** [comment]
Fixed in #2826 

I had originally set all fields in Ctor (most often there are 3: Schedule, Multiplier and EndUseSubCategory), and realized later that:
1. Setting only the last is enough to see them
2. Setting some of them, like schedule, is a bad idea because then it won't inherit from the grid.

So I reverted back to only setting the last one (in general EndUseSubCategory, people is Mutliplier for eg).

I also wrote a ruby script in order to populate the same last fields for all the Library OSMs too (I uploaded it with the PR in case...)

![electricequipment](https://user-images.githubusercontent.com/5479063/31820818-4761ab46-b5a3-11e7-9efc-4ac01248966d.png)

![gasequipment](https://user-images.githubusercontent.com/5479063/31820819-47784054-b5a3-11e7-9bfb-ef1d78c217f0.png)

![internalmass](https://user-images.githubusercontent.com/5479063/31820820-478e6f14-b5a3-11e7-85fd-6a0cf1088621.png)

![lights](https://user-images.githubusercontent.com/5479063/31820821-47abcb4a-b5a3-11e7-9e99-0fa43fd917d7.png)

![luminaire](https://user-images.githubusercontent.com/5479063/31820822-47cc04a0-b5a3-11e7-83a5-d77e2519f293.png)

![otherequipment_withfueltypeexposed](https://user-images.githubusercontent.com/5479063/31820823-481fe638-b5a3-11e7-8eff-6489ee753a60.png)

![steamequipment](https://user-images.githubusercontent.com/5479063/31820824-483c8932-b5a3-11e7-9912-a0b824abac67.png)
