### ISSUE TITLE
"Download All" in PAT only downloads 150 datapoints

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio#2773]
Truncation causes "Download All" to only download 150 datapoints instead of all of them.

**Comment by shorowit** [comment]
I just did another test run of 200 datapoints and ended up with 158 (?) datapoint directories in localResults. Also, I can confirm this bug occurs in the official PAT 2.2.1.

**Comment by rHorsey** [comment]
This isn't really a bug, it's a feature. The functionality that previously existed was unintended, and we're not sure how it worked at all. To do this responsibly is going to require a fair bit of effort and is moderately risky, due to the control logic surrounding that controller in PAT. @kflemin will start in on this once 2.3.0 is out and we have regular iteration builds rolling again.

**Comment by rHorsey** [comment]
This isn't really a bug, it's a feature. The functionality that previously existed was unintended, and we're not sure how it worked at all. To do this responsibly is going to require a fair bit of effort and is moderately risky, due to the control logic surrounding that controller in PAT. @kflemin will start in on this once 2.3.0 is out and we have regular iteration builds rolling again.

**Comment by kflemin** [comment]
This issue was moved to NREL/OpenStudio-PAT#40
