### ISSUE TITLE
Luminaire won't allow input higher than 1.0 for Lighting Power

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2778]
https://unmethours.com/question/26532/unable-to-edit-luminaire-definitions-in-os/

GUI only lets you enter values from 0.0 to 1.0. Should be able to enter any positive number. I haven't confirmed if this is GUI issue or affects model API as well.

**Comment by jmarrec** [comment]
Fixed in #2815.

Here is the default luminaire:

![2778_2710_luminaire_inputs_1_default](https://user-images.githubusercontent.com/5479063/31218481-bf773a96-a9ba-11e7-9f9c-33e5271529db.png)

And now with user input, I can edit all "fraction" fields, and I can also input a Lighting Power that is greater than 1.

![2778_2710_luminaire_inputs_2_user_input](https://user-images.githubusercontent.com/5479063/31218485-c6989ab8-a9ba-11e7-88ad-18a19d804cf6.png)

**Comment by macumber** [comment]
This looks good, noticed that we can have sum of the fractions add up to > 1.  I'll file that as a separate issue https://github.com/NREL/OpenStudio/issues/2867
