### ISSUE TITLE
Purge Unused Objects in Space Tab deletes all spaces

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2839]
Even if spaces are assigned to thermal zones and have hard assigned loads, they are all still deleted.
https://unmethours.com/question/27767/any-way-to-delete-multiple-spaces-at-one-time/?answer=27777#post-id-27777

The icon is disabled until one or more spaces are selected. At that point both the delete (red x) and purge (recycle can) are enabled. If purge is enabled it shouldn't require any spaces to be selected. Then it should have some criteria on what is "unused" maybe that means it doesn't have any thermal zones assigned, any surfaces, or both?. I'm fine either disabling this or updating behavior.

Delete function behaves as expected.

**Comment by jmarrec** [comment]
Fixed in #2815 .
The purge button is now enabled whether a space is selected or not.

On purge, only spaces that have neither a ThermalZone assigned no Surfaces are removed.

Will be easy to change the logic, the commit I've done shows the location where to implement the new logic and gives a good example of what it looks like.
