### ISSUE TITLE
gbXML import mistakes

### ISSUE THREAD

**Issue by ngerasim** [NREL/OpenStudio#2841]
Please see the detailed report [here](https://unmethours.com/question/27690/os-doesnt-assign-construction-to-reversed-surfaces/). The test gbXML in the attachment
[TestCube.zip](https://github.com/NREL/OpenStudio/files/1457877/TestCube.zip)

**Comment by macumber** [comment]
Additional things to check https://unmethours.com/question/27690/os-doesnt-assign-construction-to-reversed-surfaces/ https://unmethours.com/question/28251/revit-gbxml-to-openstudio/ https://unmethours.com/question/18258/problems-converting-gbxml-to-idf/

**Comment by jasondegraw** [comment]
The reported issues here are:

 - [ ] OS does not recognize underground walls. (#3121)
 - [ ] In SketchUp there are no constructions assigned to generated reversed surfaces
 - [ ] Some of surfaces have constructions with unreadable names. This one is essentially expected behavior, the gbXML file has multiple constructions with the same name.
 - [ ] In OS application horizontal surfaces are recognized incorrectly, and as a consequence, constructions for horizontal surfaces are also wrong. (#2992)
 - [ ] For adjacent spaces, constructions for some reversed surfaces are not assigned
