### ISSUE TITLE
Fix qt warnings in app

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2934]
Currently a large number of warnings are output to the console on Mac, on Windows these can be seen by running the app with `C:\openstudio-version\bin\OpenStudioApp.exe > out.txt 2>&1`

**Comment by jmarrec** [comment]
In Debug mode, there's this Qt warning that will pop up 16 times each time you switch to a tab that has an OSGridController in it:

```
Warning: QLayout: Attempting to add QLayout "" to openstudio::OSGridView "", which already has a layout ((null):0, (null))
```

It's something people seem to often run into since you'll find similar posts on the web, for eg [here](https://stackoverflow.com/questions/25450598/qlayout-attempting-to-add-qlayout-to-qwidget-which-already-has-a-layout/25451334#25451334)

Stepping through a debbuger, the line were all these warnings are send to the console is [here](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/shared_gui_components/OSViewSwitcher.cpp#L76)

**Comment by jmarrec** [comment]
This question and answer is most interesting if we want to change the layout of a widget that already has one: https://stackoverflow.com/questions/10416582/replacing-layout-on-a-qwidget-with-another-layout
