### ISSUE TITLE
Can't show E+ stdout when running from CLI

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2941]
@mostaphaRoudsari @chriswmackey have requested this

**Comment by chriswmackey** [comment]
Thanks for adding this @macumber .

I'll add that @kbenne showed me a way of trying to get the stdout on unmethours:
https://unmethours.com/question/26817/viewing-the-energyplus-simulation-log-within-openstudio-cli-terminals/

I think that I was close to getting it to work on my machine but it became apparent to me that this was not going to be a solution that I could easily push out to the Honeybee community.  Also, the critical reason why I was trying to get it to work was so that Honeybee users could track the progress of their simulation while it's running (something that many people have told me they like).  So having it integrated into the CLI would be very helpful and could enable me to turn all of the Honeybee workflows over to using the CLI.

**Comment by jmarrec** [comment]
This requires modification to the openstudio-workflow-gem to capture stdout, same underlying fix as for #873 (which is specific to OS App)

**Comment by macumber** [comment]
@jmarrec is this tagged for OS 3.1.0?  Is there any design on how this would work?  Would OS just forward E+ std out or would it use the E+ progress API?

**Comment by jmarrec** [comment]
This seems to be assigned to @kbenne at the moment.

I have not thought about this one since E+ gained the `api/runtime.h` header and the `registerProgressCallback` and `registerStdOutCallback`. Before that, I would have just assumed it would simply forward the stdout.

Using the API is probably a good idea, but that would mean revamp the entire way of running energyplus in the workflow-gem.

The workflow-gem already has an optional `ouput_adapter` in its `call_energyplus` method, so I assumed then it would use that:

https://github.com/NREL/OpenStudio-workflow-gem/blob/3b5918b6a0d8891e245762600735abe729abe81b/lib/openstudio/workflow/util/energyplus.rb#L155-L166

**Comment by jmarrec** [comment]
I added support for this in https://github.com/NREL/OpenStudio/pull/4504.
