### ISSUE TITLE
Apply measures only option broken

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2942]
@mostaphaRoudsari @chriswmackey have requested this

**Comment by chriswmackey** [comment]
Thanks for posting this. Let me know if you need an example to recreate the issue.

**Comment by chriswmackey** [comment]
I realized what the issue is.  I didn't know that I was supposed to pass both `-m` and `-w `in order to run a workflow that only applies measures.  Once I pass both of arguments (and not just `-m`), the "apply measures only" feature works without issues.

I apologize for the confusion, and looking back on the CLI documentation, I see that the example there has both the `-measures_only` and the `-workflow` arguments specified:
http://nrel.github.io/OpenStudio-user-documentation/reference/command_line_interface/
I guess that I must have overlooked it when I was using the abbreviated form of the arguments (`-m` and `-w`).

**Comment by chriswmackey** [comment]
Please feel free to close out this issue now.
