### ISSUE TITLE
FanVariableVolume availability schedule name changes unexpectedly

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3124]
In 2.5.0 the `Availability Schedule Name` field for a variable volume fan on an air loop will change unexpectedly after adding a new schedule to the model with a higher sorting priority than the default `Always On Discrete` schedule name. Steps to reproduce. 

1. Create AirLoopHVAC, add FanVariableVolume
2. Note default `Availability Schedule Name` = "Always On Discrete"
3. Create new schedule with a name that has a higher sorting priority, e.g. "00000 test"
4. Fan's availability schedule names change to new schedule

I suspect it has something to do with the move to using the `Always On Discrete hvac_library` schedule.

**Before**

![image](https://user-images.githubusercontent.com/8397034/39716398-7e697ed4-51ed-11e8-93e0-7365f5e9e8b1.png)

**After**

![image](https://user-images.githubusercontent.com/8397034/39716436-981ac248-51ed-11e8-844d-a363291b0e12.png)

**Comment by jmarrec** [comment]
This does it when you use "Fan Variable Volume 2" since this one refers to a Schedule named "Always On Discrete" but with no Type=Discrete, which is required to identify the actual `model.alwaysOnDiscreteSchedule`.
If you use "Fan VarSpd", which has a "Always On Discrete hvac_library" schedule, it doesn't exhibit this behavior

In fact, if you reproduce Matt's step, and save the model without touching anything else, and load that in ruby, and try to get the fan's availability schedule:

```
m2.getFanVariableVolumes[0].availabilitySchedule
[openstudio.model.FanVariableVolume] <1> Required availability schedule not set, using 'Always On' schedule
```

**Comment by jmarrec** [comment]
Geez, took me a while (and a debugger) to figure out that the real problem is the `hvac_library.osm` itself.

The availability Schedule is mandatory, but it's not set for the "Fan Variable Volume 2", see https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/openstudio_app/Resources/default/hvac_library.osm#L10658

That's the only problem there is!

**Comment by jmarrec** [comment]
Related to #2252

**Comment by MatthewSteen** [comment]
I'm experiencing this again with `AirTerminalSingleDuctSeriesPIUReheat` objects. After creating them with the API, the `FanConstantVolume` schedule is set to `Always On Discrete`, but after adding a new schedule with a numeric prefix to the model in the app, the fan schedule changes.

![image](https://user-images.githubusercontent.com/8397034/51940675-e8a76e00-23cf-11e9-8c03-3cecb69041c0.png)

**Comment by jmarrec** [comment]
Matt can you give a MCVE for this?
Or you can email me your file privately so I can try to reproduce, thanks!
