### ISSUE TITLE
Problems with getFoo paths on linux

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3169]
When using Ubuntu 16.04 (via WSL) and the [2.6.0 linux pre-release](https://github.com/NREL/OpenStudio/releases/tag/v2.6.0), I get empty and/or inconsistent paths returned from OpenStudio depending on how I call the CLI.

Example 1: **getEnergyPlusDirectory** test.rb:
```
require 'openstudio'
puts OpenStudio.getEnergyPlusDirectory
```

Run it two different ways and the first doesn't return a path.
```
shorowit@SHOROWIT-30399S:~$ openstudio test.rb

shorowit@SHOROWIT-30399S:~$ /usr/local/bin/openstudio test.rb
/usr/local/openstudio-2.6.0/bin/../EnergyPlus
```

Example 2: **getOpenStudioCLI** test.rb:
```
require 'openstudio'
puts OpenStudio.getOpenStudioCLI
```

Run it two different ways and you get two different answers:
```
shorowit@SHOROWIT-30399S:~$ openstudio test.rb
/usr/local/bin/openstudio
shorowit@SHOROWIT-30399S:~$ /usr/local/bin/openstudio test.rb
/usr/local/openstudio-2.6.0/bin/openstudio
```

**Comment by jmarrec** [comment]
This is likely a symlink problem.

---- 

As a reminder:

I changed CMake recently for Ubuntu, and openstudio will now install in `/usr/local/bin/openstudio-2.6.0`

 `/usr/local/bin/openstudio-2.6.0/bin/openstudio` (the CLI) is then symlinked into `/usr/local/bin/openstudio` (and `/usr/local/bin/openstudio-2.6.0` to handle the case where you have several versions installed) so that this is discoverable (=in your $PATH).

**Comment by macumber** [comment]
I think this commit will fix it, https://github.com/NREL/OpenStudio/pull/3168, but it is not tested yet.  @shorowit how critical is it that this be in 2.6.0, we really do not want to have to roll new packages at this point.


@nllong @anyaelena FYI

**Comment by shorowit** [comment]
I think I'm successfully working around it.
