### ISSUE TITLE
Update Standards Tags for Standards Gem

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3199]

**Comment by jmarrec** [comment]
I'm having trouble remembering what this issue was really about... Could you refresh my memory so I can double check?

If this is linked to parsing the JSON files to suggest Standards Template/Building Type/Space Type (see picture) then yes, it was done.

![image](https://user-images.githubusercontent.com/5479063/53494807-da1ba780-3a9e-11e9-973b-a17d6bc08a3c.png)

**Comment by macumber** [comment]
I believe this was about updating the list of keys you see in drop downs, I believe you did that work so can close this
