### ISSUE TITLE
Serious bug in MasslessOpaqueMaterial (Bugzilla #1225)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#320]
On 2013-04-15 15:14:59, @macumber wrote:

> MasslessOpaqueMaterial does not have data fields to support conductivity, etc that are required in base class.  It is debatable whether these methods should be in the base class.  However, this implementation is definitely not correct (field indices from wrong object are used):
> 
>   double MasslessOpaqueMaterial_Impl::conductivity() const {
>     OptionalDouble od = getDouble(OS_MaterialFields::Conductivity,true);
>     if (!od) {
>       LOG_AND_THROW("Thermal conductivity is not set for MasslessOpaqueMaterial "
>           << briefDescription() << ".");
>     }
>     return *od;
>   }

**Comment by DavidGoldwasser** [comment]
@macumber does someone just hit this if they have a massless material and try to set conductivity?

Here is an example of how it is typically used in our measures. If I'm looping through construction layers I typically confirm what type of material it is before doing anything to it.
https://github.com/NREL/OpenStudio-measures/blob/a9e00dbe625a4895780303b42cd751e99618572a/NREL%20working%20measures/AedgK12ExteriorWallConstruction/resources/OsLib_Constructions.rb#L67-L74

Would Air Gap material have the same issue?

**Comment by macumber** [comment]
It happens if they try to get conductivity, if they are not catching errors they will get a crash

**Comment by DavidGoldwasser** [comment]
If you were to fix it what would the fix be? If you also add conductivity as a field, that would be odd, possible conflicting values. Deleting resistance would be an issue, because it would break current measures. It is possible removing it from base class may also break things. Another words measures may get a material and ask are you massless or air gap, if not then material.getConductivity? (not sure if that is done anywhere?)

**Comment by macumber** [comment]
You can't really get conductivity because you don't know how think the layer is.  The right answer is probably to remove the method in the base class or make it return optional.

**Comment by macumber** [comment]
We should probably look at what E+ reports for these materials, if E+ does not report a conductivity then we should remove it from the base class

**Comment by DavidGoldwasser** [comment]
Makes sense, I could get conductance but not conductivity.

**Comment by jmarrec** [comment]
thermalConductivity corrrectly does a LOG_AND_THROW. conductivity is still wrong.
I would say just remove conductivity() altogether, since it's always been completely wrong and there's a `thermalConductivity()` that matches other method naming conventions.

Also, there's a lot of uncessary shadowing happening between (Material > ) OpaqueMaterial > MasslessOpaqueMaterial, especially on the public side (The Impl side seems ok, the use of 'virtual' is actually fine).

Eg: OpaqueMaterial.hpp has `double thermalResistance() const`, but so does MasslessOpaqueMaterial which is shadowing the parent one while doing the same thing: forwarding to the Impl (which is correctly defined as `virtual double thermalResistance() const = 0;` in OpaqueMaterial.hpp).

**Comment by joseph-robertson** [comment]
So what is the final decision here? To not inherit the OpaqueMaterial base class? And then remove all methods related to any fields in OS:Material that aren't in OS:Material:NoMass?

**Comment by jmarrec** [comment]
My two cents, which seem to agree with Dan's comments above: I wouldn't change the inheritance tree, just revamp a bit to be consistent and review the use of virtual methods, and remove methods in the base class if they don't necessary have a valid implementation in the child classes.

eg: `OpaqueMaterial_Impl::thermalConductivity` (`virtual double thermalConductivity() const = 0;`) should be removed, as `MasslessOpaqueMaterial` and `AirGap` can't implement it.. `StandardOpaqueMaterial` and `RoofVegetation` should be responsible for defining it and in a consistent manner.

The benefit of defining a pure virtual method in the base class is to 1) Force child classes to implement it (the point is moot here), and 2) somewhat enforce that you use a consistent naming of methods (and 3) make it an abstract class and ensure it can't be instantiated)
The drawback here is that two classes (`MassLessOpaqueMaterial` and `AirGap`) have a method that does nothing but a `LOG_AND_THROW`...  I think the drawback outweighs the benefit by a lot, so it's better to remove the pure virtual method, and manually make sure that the two classes that should define it use the same signature.

**Comment by jmarrec** [comment]
@joseph-robertson 

Following the discussion on #320, I now realize something:

There is `OS:Material:NoMass` in the IDD. `MasslessOpaqueMaterial` correctly uses  `OS_Material_NoMassFields` for most getters and setters. **But you will find a few methods including `conductivity` that wrongly uses `OS_MaterialFields` and that's why it returns bogus. These are probably error from copy-pasting another file (`StandardOpaqueMaterial`) where they were defined**

I suppose the course of action for this specific issue is:

### Mandatory change to fix this issue
* `MasslessOpaqueMaterial` should use `OS:Material:NoMass` fields only, remove all methods that cannot be implemented as a result like `conductivity` `density`, `specificHeat`, `density` which aren't in OpaqueMaterial.hpp to begin with and are probably copy paste errors from another file

### Additional changes?

`OpaqueMaterial` defines some methods as returning `double` when implementation isn't possible in all child classes. This forces the child classes to issue a `LOG_AND_THROW`, (which is probably fine). Either:
* Keep this behavior, but do ensure that all child classes do that LOG_AND_THROW (are these all tested?)
* Change them to return OptionalDouble instead

* heatCapacity isn't actually implemented in either StandardOpaqueMaterial not RoofVegetation where they should be.

For reference, by method, italics = calculatabled (and formula from fields)

| Method              | Material                            | Material:RoofVegation                  | Material:NoMass                                | Material:AirGap          |
|---------------------|-------------------------------------|----------------------------------------|------------------------------------------------|--------------------------|
| thermalConductivity | Conductivity                        | Conductivity of Dry Soil               |                                                |                          |
| thermalConductance  | *Conductivity / Thickness*          | *Conductivity of Dry Soil / Thickness* |                                                | *1 / Thermal Resistance* |
| thermalResistivity  | *1 / Conductivity*                  | 1 / Conductivity of Dry Soil           |                                                |                          |
| thermalResistance   | *Thickness / Conductivity*          | *Thickness / Conductivity of Dry Soil* |                                                | Thermal Resistance       |
| thickness           | Thickness                           | Thickness                              |                                                |                          |
| thermalAbsorptance  | Thermal Absorptance                 | Thermal Absorptance                    | Thermal Absorptance                            |                          |
| solarAbsorptance    | Solar Absorptance                   | Solar Absorptance                      | Solar Absorptance                              |                          |
| visibleAbsorptance  | Visible Absorptance                 | Visible Absorptance                    | Visible Absorptance                            |                          |
| thermalReflectance  | *1 / Thermal Absorptance*           | *1 / Thermal Absorptance*              | *1 / Thermal Absorptance*                      |                          |
| solarReflectance    | *1 / Solar Absorptance*             | *1 / Solar Absorptance*                | *1 / Solar Absorptance*                        |                          |
| visibleReflectance  | *1 / Visible Absorptance*           | *1 / Visible Absorptance*              | *1 / Visible Absorptance*                      |                          |
| heatCapacity        | *Thickness x Density x Specific Heat* |                                        | *Thickness x Density x Specific Heat of Dry Soil* |                          |
| roughness           | Roughness                           | Roughness                              | Roughness                                      |                          |
