### ISSUE TITLE
orphan ZoneHVACEquipmentList objects from model.getBuilding.remove

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#3268]
When model.getBuilding.remove is called, it deletes thermal zones but leaves their ZoneHVACEquipmentList objects.  These objects now have no thermal zone handle, and that causes their obj.thermalZone method to fail. Occurs in at least 2.5.1 and greater.

**Comment by DavidGoldwasser** [comment]
@kbenne while measure writers can get around this I think it is important to keep the OSM's clean so I tagged it as major. I assume should be pretty easy fix to get into 2.7.0?

Dan thinks zone.remove might have the same behavior but I haven't tested that. The remove_orphan_and_unused_resources measures doesn't currently clean this up but could be updated to do so. https://github.com/NREL/OpenStudio-measures/blob/develop/nrel_published/remove_orphan_objects_and_unused_resources/measure.rb

**Comment by jmarrec** [comment]
zone.remove should do it right: https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/ThermalZone.cpp#L1822

I'm on it

**Comment by jmarrec** [comment]
The "problem" is that ZoneHVACEquipmentList isn't a child of ThermalZone. So when you delete the building, when it was children recursively, it can't find it. I tested by making it a children, and building.remove leaves no orphan ones anymore.

The reason it's not a child is likely because that would bring it in the OS App when you click on a thermalZone (eg on a ThermalZone in the AirLoopHVAC view).

Now that https://github.com/NREL/OpenStudio/pull/3262 is there, perhaps it'd be good to expose *somewhere* the "setLoadDistribution" field.

Thoughts @kbenne
