### ISSUE TITLE
Import ScheduleFile from IDF

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3347]

**Comment by ChenWenQian** [comment]
hi, I'd like to import a schedule from my own csv file (i.e. 10-min schedule), So , I created an object Schedule:File in IDF editor,  I imported the idf file containing the Schedule:File, but I can't find it in the osm model. Does openstduio 2.7 support that?   
Or can you give me any other suggestions? I tried to use the measure 'Add Interval Schedule From File', but it failed. Firstly, I changed the 'measure.rb' file to support 10-min interval, but I can't find any schedule object in the osm file. Secondly, I used the 15min_value. csv file from the 'test' folder, the same results occurred.  So, I don't know where is the problems. 
Great thanks if you could help me.

**Comment by joseph-robertson** [comment]
Appears someone has written `ReverseTranslateScheduleFile.cpp`. I will check that it's working and that there are sufficient tests.

**Comment by joseph-robertson** [comment]
I imported the idf created from the test below into OSApp. It imports successfully, and the saved osm  correctly contains the reverse translated `Schedule:File` object. When I open the saved osm in OSApp, the Schedules tab does not show the Schedule File (under either My Model or Library). Perhaps that is what this issue is referring to- that it'd be nice to show the imported `Schedule:File` in OSApp?

https://github.com/NREL/OpenStudio-resources/blob/develop/model/simulationtests/schedule_file.rb

@ChenWenQian

**Comment by tijcolem** [comment]
closing as this has been addressed and will be released in 2.9.0
