### ISSUE TITLE
OpenStudio hangs on some geometry operations

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3359]
Occurs in some of the intersect tests and the create_bar measures.  Did not resolve when updating boost to 1.68, seems to be a little worse.

**Comment by macumber** [comment]
@DavidGoldwasser reported as well

**Comment by DavidGoldwasser** [comment]
You can reproduce this with CLI using this measure test, which is currently commented out.
https://github.com/NREL/OpenStudio-measures/blob/develop/nrel_dev/create_bar_from_building_type_ratios/tests/create_bar_from_building_type_ratios_test.rb#L259

EnergyStar TenantSpace also hit this.

**Comment by DavidGoldwasser** [comment]
@macumber here is OSW using arguments from skipped measure test that locks up. I confirmed this in OSW on Mac.

`{
  "seed_file": null,
  "weather_file": "USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw",
  "measure_paths": [
    "../../../../nrel_dev/"
  ],
  "file_paths": [
    "../../../weather",
    "../../../seeds",
    "../../../seed"
  ],
  "run_directory": "./run",
  "steps": [
    {
      "measure_dir_name": "create_bar_from_building_type_ratios",
      "arguments": {
        "bldg_type_a": "MediumOffice",
        "total_bldg_floor_area": 40000.0,
        "num_stories_above_grade": 4.5,
        "bar_division_method": "Single Space Type - Core and Perimeter"
      },
      "name": "create_bar_from_building_type_ratios"
    }
  ],
  "name": "create_bar_skipped_test_inputs",
  "description": "intersect surfaces lockup workflow"
}`

If you check out this branch you can run the OSW in the integration_testing_directory.
https://github.com/NREL/OpenStudio-measures/blob/os_issue_3359/tests/integration_testing/workflows/190219_intersect/data_point.osw

**Comment by DavidGoldwasser** [comment]
if `make_mid_story_surfaces_adiabatic` argument is added to OSW with value of `true` then intersection doesn't happen and measure runs fine. The default value for this in measure.rb is `false`. I have been testing on 2.7.2 o mac. I'll test in 2.7.0 and 2.7.1 to confirm behavior. For me this happens with both the measure test (when not skipped) and the OSW. When running for projects on server it was on Unix.

**Comment by DavidGoldwasser** [comment]
@macumber Locked up 2 out of 4 times on 2.7.0 and 2 out of 4 times on 2.7.1. I'll try a few more times on 2.7.2 to see if I can get it not to always lock up if I try a few more times.

**Comment by macumber** [comment]
Here is a test script I wrote, I am getting 4/4 success rates....

[test.rb.txt](https://github.com/NREL/OpenStudio/files/2882372/test.rb.txt)

**Comment by DavidGoldwasser** [comment]
Results from my macbook with 50 tries.
n = 50, success = 18

**Comment by macumber** [comment]
I think this may be the culprit:

https://www.reddit.com/r/Python/comments/1vbie0/subprocesspipe_will_hang_indefinitely_if_stdout/

**Comment by macumber** [comment]
Nevermind, it is just this line:

https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/model/Space.cpp#L2355

**Comment by DavidGoldwasser** [comment]
@macumber ok, here is some more information.

The initial OSW just runs the create_bar_from_building_type_ratios and does intersection within that.
https://github.com/NREL/OpenStudio-measures/blob/os_issue_3359/tests/integration_testing/workflows/190219_intersect/data_point.osw

I decided to skip intersection in that measure, and add dedicated surface_matching_diagnostic measure downstream.  I was seeing similar failure rates.
https://github.com/NREL/OpenStudio-measures/blob/os_issue_3359/tests/integration_testing/workflows/190219_intersect/data_point_alt_b.osw

That measure makes an array of pairs of spaces, and then intersects those spaces. Since I couldn't get log of which space pair was failing, I decided to take the OSM that comes out of create_bar (pre intersected) and make it seed for unit test in surface_matching_diagnostic.
https://github.com/NREL/OpenStudio-measures/blob/os_issue_3359/tests/integration_testing/workflows/190219_intersect/data_point_alt_b2.osw
 No big surprise, this didn't fail at all. The surprise is that the measure test didn't fail either. I expected it to lock up like CLI behavior. 

So I'm thinking something is different inside vs. outside of CLI. But no, that wasn't the case. I made another OSW. This one takes in the bar.osm as a seed model and only runs surface_matching_diagnostic diagnostic. It passed 50 out of 50.
https://github.com/NREL/OpenStudio-measures/blob/os_issue_3359/tests/integration_testing/workflows/190219_intersect/data_point_alt_c.osw

So how is running measure `a`. saving the model as seed for new osw that runs measure `b` any different than running measure `a` and `b` combined in one OSW.

**Comment by macumber** [comment]
Fixed this issue and added unit tests in https://github.com/NREL/OpenStudio/pull/3431.  The current fix relies on sorting of spaces and surfaces by area and is likely to not work in other circumstances.  If we discover those cases we can add additional tests and resolve at a deeper level.  

Currently, the Space::intersectSurfaces may result in missing surface area from the final result.  This is not good for automated analyses.  We may want to add exceptions or some other error to indicate that the intersection failed.
