### ISSUE TITLE
Searching BCL from OS app doesn't find measure

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3392]
I am trying to find [this measure](https://bcl.nrel.gov/node/83281) from the BCL.

If I search the BCL itself, it finds two measures and one of them is the measure of interest.
![image](https://user-images.githubusercontent.com/5861765/50484442-bdcf9180-09ad-11e9-8055-aa67071d9639.png)

However, if I search for "inject" from the OS App, I only find one measure and it's not the one above.
![image](https://user-images.githubusercontent.com/5861765/50484453-c88a2680-09ad-11e9-9b4c-6c3890eca56a.png)
If I traverse through the categories, I can find the measure. So the issue isn't that the measure is not available.

**Comment by jmarrec** [comment]
@shorowit That's because it'll only search under the category you have selected, that is "Envelope", while the inject_idf_object is under 'Whole Building".

![image](https://user-images.githubusercontent.com/5479063/53498579-df7cf000-3aa6-11e9-9f2d-87a20b963c44.png)

I think this works as intended and issue should be closed

**Comment by shorowit** [comment]
Ah, ok. I think it would be preferable to have it search the entire BCL (since there's no way to do that if the search is specific to the selected category), but I guess it's working as expected.

**Comment by jmarrec** [comment]
@shorowit Feel free to reopen and relabel as " Allow searching entire BCL from OS App and not just within categories" and label this as an Enhancement request if that's something you do want to see happen.
