### ISSUE TITLE
Fix unit test failures on develop and develop3

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3514]

**Comment by macumber** [comment]
@tijcolem can you list the test failures on each platform for these branches and indicate if they are regular or intermittent

**Comment by tijcolem** [comment]
Unit tests for develop are now down to just 2 reoccurring issues for Windows. Once these are addressed we'll have 100% passing on develop.  Will copy changes from develop to develop3 (in particular changes made for BCL tests to work)

	2378 - EnergyPlusFixture.ErrorFile_WarningsAndSevere (Failed)
	2379 - EnergyPlusFixture.ErrorFile_WarningsAndCrash (Failed)

**Comment by jmarrec** [comment]
cf bundle specific issue #3733 

Here is the list of tests that are failing. X indicates a failure on that platform.

Based on https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-develop-nightly/detail/openstudio-develop-nightly/261/pipeline/7

| Test                                                               | Ubuntu | macOS | Windows |
|--------------------------------------------------------------------|--------|-------|---------|
| BCLFixture.RemoteBCLTest2                                          |        | X     |         |
| BCLFixture.BCLMeasure                                              | X      | X     | X       |
| ModelFixture.Space_intersectSurfaces_degenerate1                   | X      | X     | X       |
| ModelFixture.Space_intersectSurfaces_degenerate2                   | X      | X     | X       |
| ModelFixture.Space_intersectSurfaces_degenerate3                   | X      | X     | X       |
| ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SimAUD_Paper     | X      | X     | X       |
| ModelFixture.ZonePropertyUserViewFactorsBySurfaceName_AddAndRemove | X      | X     | X       |
| CLITest-test_bundle-bundle                                         | X      | X     | X       |
| CLITest-test_bundle-bundle_git                                     | X      | X     | X       |
| CLITest-test_embedded_ruby-json                                    | X      | X     | X       |
| CLITest-test_encodings-encoding                                    | X      | X     | X       |
| CLITest-test_encodings-encoding2                                   | X      | X     | X       |
| EnergyPlusFixture.ErrorFile_WarningsAndSevere                      |        |       | X       |
| EnergyPlusFixture.ErrorFile_WarningsAndCrash                       |        |       | X       |

**Comment by jmarrec** [comment]
I have absolutely no clue why `EnergyPlusFixture.ErrorFile_WarningsAndSevere` and `EnergyPlusFixture.ErrorFile_WarningsAndCrash` are failing on CI. I tested locally on Windows 10, it works fine. I reviewed the test too, don't see anything wrong. Tried to see if another test could be overwriting it, didn't find anything either.

```
2289/2799 Testing: EnergyPlusFixture.ErrorFile_WarningsAndSevere
2289/2799 Test: EnergyPlusFixture.ErrorFile_WarningsAndSevere
Command: "D:/jenkins/openstudio/develop/build/Products/Release/openstudio_energyplus_tests.exe" "--gtest_filter=EnergyPlusFixture.ErrorFile_WarningsAndSevere"
Directory: D:/jenkins/openstudio/develop/build/src/energyplus
"EnergyPlusFixture.ErrorFile_WarningsAndSevere" start time: Jan 10 17:28 Coordinated Universal Time
Output:
----------------------------------------------------------
Running main() from gmock_main.cc
Note: Google Test filter = EnergyPlusFixture.ErrorFile_WarningsAndSevere
[ RUN      ] EnergyPlusFixture.ErrorFile_WarningsAndSevere
D:\jenkins\openstudio\develop\src\energyplus\Test\ErrorFile_GTest.cpp(92): error: Expected equality of these values:
  static_cast<unsigned>(46)
    Which is: 46
  errorFile.warnings().size()
    Which is: 6
[  FAILED  ] EnergyPlusFixture.ErrorFile_WarningsAndSevere (9 ms)
[----------] 1 test from EnergyPlusFixture (9 ms total)
```

**Comment by jmarrec** [comment]
Encodings is a change in default encoding.

2.9.1

```
$ /usr/local/openstudio-2.9.1/bin/openstudio -e "m = OpenStudio::Model::Model.new; puts m.getVersion.getString(1).get.encoding"
UTF-8
```

3.x

```
$ Products/openstudio -e "m = OpenStudio::Model::Model.new; puts m.getVersion.getString(1).get.encoding"
ASCII-8BIT
```

Does that ring a bell @kbenne?

**Comment by jmarrec** [comment]
**ModelFixture.ThreeJSReverseTranslator_FloorplanJS_SimAUD_Paper**

This is s geometry precision thing: Error: Initial area of surface 'Face 188' 522.58 does not equal post intersection area 522.58

Tolerance is 0.01, diff comes up to sligthly more than that...

**Comment by jmarrec** [comment]
**Space_intersectSurfaces_degenerateX**

I am investigating the intersection failures, specifically  `ModelFixture.Space_intersectSurfaces_degenerate1`:

[openstudio.model.Surface] <-1> Intersection of 'topLeft Floor 0' with 'bottomTop RoofCeiling 0' results in (topLeft Floor 0), (bottomTop RoofCeiling 0), [Surface 1], [Surface 2]
[openstudio.model.Surface] <-1> Intersection of 'Surface 1' with 'bottomBottom RoofCeiling 0' results in (Surface 1), (bottomBottom RoofCeiling 0), [Surface 3], [Surface 4]
# This line: only in 3.x
[utilities.geometry.intersect] <-1> Cannot compute area of face difference, result will not include this polygon, []

Here's the diff in the resulting Surface 1 (left is 291 official, right is current develop (3.x))

![image](https://user-images.githubusercontent.com/5479063/72361219-65228200-36f1-11ea-954d-0756d411ba10.png)

And here is the 3.x model, before and after the intersect(spaces) call, for surface 'bottomTop RoofCeiling 0'. Here too the precision is changed

![image](https://user-images.githubusercontent.com/5479063/72361255-73709e00-36f1-11ea-9be0-70117b36ae9a.png)

By comparison in 2.9.1, the extra vertex is removed but the others untouched (no change of precision)

![image](https://user-images.githubusercontent.com/5479063/72361271-7b304280-36f1-11ea-9c65-fd8d82627acf.png)


This looks like it's probably a change in boost::geometry going from 1.55 to 1.71 since these started failing as soon as we started develop3... I haven't found a suitable resolution.

**Comment by tijcolem** [comment]
resolved via #3877.

**Comment by jmarrec** [comment]
Can we really call it resolved @tijcolem ? We still disabled 5 tests via a Ctest exclude regex.

https://github.com/NREL/OpenStudio/issues/3514#issuecomment-574176231
https://github.com/NREL/OpenStudio/issues/3514#issuecomment-574252184

**Comment by jmarrec** [comment]
I'd like to bump this higher on the list of priorities. This annoys me to have failing tests without an exclude regex.

**Comment by jmarrec** [comment]
@tijcolem So today, once #4221 is merged in, we have two tests failing on all platforms.: `CLITest-test_encodings-encoding`, `CLITest-test_encodings-encoding2`, not sure how to address that or what to do with it.



And this annoying windows-only issue where assert_raises segfaults for some reason: `RubyTest-Date_Test-ymd_constructor`
