### ISSUE TITLE
AccessViolationException while converting FloorPlanJS object to ThreeScene object using OpenStudio sdk

### ISSUE THREAD

**Issue by jcseruet** [NREL/OpenStudio#3527]
I am trying create a three scene file from a floorspace file using OpenStudio SDK 2.7.0 (C#) and getting this error _"Attempted to read or write protected memory. This is often an indication that other memory is corrupt"_ while converting FloorPlanJS object to ThreeScene object. 

Here are the steps I have followed:

1. Read floorspace file using standard file reader.
2. Convert floor space json string to FloorPlanJS object.
3. Convert FloorPlanJS object to ThreeScene object.

Here is the code snippet:

		//Read floorspace file using standard file reader
                var floorspacejson = File.ReadAllText(floorspacePath);
		//Convert floor space json string to FloorPlanJS object
                var floorplanJSObject = OpenStudio.FloorplanJS.load(floorspacejson).get();
                if (floorplanJSObject == null)
                {
			//null check
                }
		//Convert FloorPlanJS object to ThreeScene object
                var threeSceneObject = floorplanJSObject.toThreeScene(false);

In step 3 (last line of the code), above mentioned exception is thrown. I have tested the same code with other floorspace file and they worked fine.

Could anyone please give some clues about what might be causing this? Here is the link for the floorspace file that I have used. 

https://drive.google.com/file/d/19EckcjKF8oCTGP1GG-djd5y4AKP1yXLd/view?usp=sharing

**Comment by macumber** [comment]
I validated your file against the [FloorspaceJS JSON schema](https://github.com/NREL/floorspace.js/blob/develop/schema/geometry_schema.json) and it appears valid.  

[FloorplanJS::load](https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/utilities/geometry/FloorplanJS.hpp#L140) returns an OptionalFloorplanJS. The crash occurs because you are calling get on an uninitialized optional.  You should check if the optional value is initialized before calling get.  The null checks you have won't work because an optional value is not null even if it is not initialized. 

I don't know why the translator might be returning an uninitialized FloorplanJS.  To diagnose, I would suggest setting the log level to Debug and looking for any messages in the console.  In C++ the code is:

`openstudio::Logger::instance().standardOutLogger().setLogLevel(Debug); // Debug = -3`

**Comment by macumber** [comment]
FYI, equivalent code to do this is in the FloorspaceJS [import_floorplan measure](https://github.com/NREL/floorspace.js/blob/develop/measures/import_floorplan/measure.rb#L61)

**Comment by macumber** [comment]
When I run the following code in Ruby:

```
require 'openstudio'

OpenStudio::Logger::instance().standardOutLogger().setLogLevel(OpenStudio::Debug)

json = nil
File.open('floorplan.json', 'r') do |file|
  json = file.read
end

floorplan = OpenStudio::FloorplanJS::load(json)
if floorplan.empty?
  puts "Cannot load floorplan from '#{floorplan_path}'."
  return false
end

scene = floorplan.get.toThreeScene(true)

rt = OpenStudio::Model::ThreeJSReverseTranslator.new

new_model = rt.modelFromThreeJS(scene)

handle_mapping = rt.handleMapping()

if new_model.empty?
  puts "Cannot convert floorplan to model."
end
```

I get an error `test.rb:16:in `toThreeScene': Key 'type' is of wrong type (RuntimeError)`.  I think this is being thrown at [this line](https://github.com/NREL/OpenStudio/blob/e077c7edfa6c94bb37aeb0e31f40b69ed2740223/openstudiocore/src/utilities/geometry/FloorplanJS.cpp#L311).  The `type` key isn't documented in the schema but it appears you need a value of 'space', 'shading', or '' for each space.  Can you try adding that key and see if it fixes the error?

I filed [this bug](https://github.com/NREL/floorspace.js/issues/357) to fix the schema.

**Comment by macumber** [comment]
Closing here
