### ISSUE TITLE
plant loop supply side equipment order

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3600]
The app's behavior for plant loop supply side equipment should follow the Thermal Zone tab's where objects appear in the order that they're added to the drop zone because it determines the order in EnergyPlus' `PlantEquipmentList` object. This is not the behavior for some objects as of 2.8.0. For example, when the desired order is a HX first and a chiller second, the chiller jumps to the top. Also happens for DistrictCooling and CoolingTower objects, but doesn't appear to affect heating equipment, e.g. HX then BoilerHotWater.

1. create new plant loop 
2. add a HeatExchangerFluidToFluid
3. add a ChillerElectricEIR

**Comment by jmarrec** [comment]
I agree with you @MatthewSteen, it's confusing. Rest assured that this is nothing but a display thing though, stuff will still end up in the PlantEquipmentList in the order you added it.

I tracked it down, and it appears that the branches are sorted, which makes sense for the demand side, especially of an AirLoopHVAC because it will sort that by the ThermalZone Name. In the case of our plant Loop, it will sort the supply side parallel branches according to the name of the 2nd component ([1] as zero-index) on the branch, or in clearer words: it takes the name of the comoonent after the first node. To test that out:


1. create new plant loop
2. add a HeatExchangerFluidToFluid: This one is named `Fluid-toFluid HX`
3. add a ChillerElectricEIR: This one is named `Chiller - Air Cooled` so it ends up before the HX
4. Rename the chiller to `zChiller - Air Cooled`. Change tab, go back to PlantLoop: Now it displays below the HX

![image](https://user-images.githubusercontent.com/5479063/61286490-3ddf0c80-a7c3-11e9-8dea-ad53a15e60f3.png)

(a Boiler is named `HW Boiler` so it goes below the HX)
