### ISSUE TITLE
Create list of deprecated methods for changelog

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3618]

**Comment by jmarrec** [comment]
| namespace | class_name                    | method                                           | Deprecated Since                                                                             | Replace With                                                                           |
|-----------|-------------------------------|--------------------------------------------------|----------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------|
| measure   | OSMeasure                     | registerWithSketchUp                             | As far as git goes                                                                           | None                                                                                   |
| measure   | OSMeasure                     | registerWithApplication                          | As far as git goes                                                                           | None                                                                                   |
| model     | AvailabilityManagerNightCycle | controlThermalZone                               | [2.3.1](https://github.com/NREL/OpenStudio/commit/3578590b7e63a68bedb7e43bef21f50552e0c6b7)  | controlThermalZones                                                                    |
| model     | AvailabilityManagerNightCycle | setControlThermalZone                            | [2.3.1](https://github.com/NREL/OpenStudio/commit/3578590b7e63a68bedb7e43bef21f50552e0c6b8)  | setControlThermalZones                                                                 |
| model     | AvailabilityManagerNightCycle | resetControlThermalZone                          | [2.3.1](https://github.com/NREL/OpenStudio/commit/3578590b7e63a68bedb7e43bef21f50552e0c6b9)  | resetControlThermalZones                                                               |
| model     | AirLoopHVAC                   | availabilityManager                              | [2.3.1](https://github.com/NREL/OpenStudio/commit/3578590b7e63a68bedb7e43bef21f50552e0c6b10) | availabilityManagers                                                                   |
| model     | AirLoopHVAC                   | setAvailabilityManager                           | [2.3.1](https://github.com/NREL/OpenStudio/commit/3578590b7e63a68bedb7e43bef21f50552e0c6b11) | addAvailabilityManager, setAvailabilityManagers                                        |
| model     | AirLoopHVAC                   | resetAvailabilityManager                         | [2.3.1](https://github.com/NREL/OpenStudio/commit/3578590b7e63a68bedb7e43bef21f50552e0c6b12) | resetAvailabilityManagers                                                              |
| model     | PlantLoop                     | availabilityManager                              | [2.3.1](https://github.com/NREL/OpenStudio/commit/3578590b7e63a68bedb7e43bef21f50552e0c6b13) | availabilityManagers                                                                   |
| model     | PlantLoop                     | setAvailabilityManager                           | [2.3.1](https://github.com/NREL/OpenStudio/commit/3578590b7e63a68bedb7e43bef21f50552e0c6b14) | addAvailabilityManager, setAvailabilityManagers                                        |
| model     | PlantLoop                     | resetAvailabilityManager                         | [2.3.1](https://github.com/NREL/OpenStudio/commit/3578590b7e63a68bedb7e43bef21f50552e0c6b15) | resetAvailabilityManagers                                                              |
| model     | Node                          | addSetpointManager                               | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541961) | SetpointManagerXXX::addToNode                                                          |
| model     | Node                          | addSetpointManagerWarmest                        | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541962) | SetpointManagerWarmest::addToNode                                                      |
| model     | Node                          | getSetpointManagerSingleZoneReheat               | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541963) | Node::setpointManagers                                                                 |
| model     | Node                          | getSetpointManagerMixedAir                       | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541964) | Node::setpointManagers                                                                 |
| model     | Node                          | setpointManagerScheduled                         | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541965) | Node::setpointManagers                                                                 |
| model     | Node                          | setpointManagerFollowOutdoorAirTemperature       | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541966) | Node::setpointManagers                                                                 |
| model     | Node                          | setpointManagerOutdoorAirReset                   | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541967) | Node::setpointManagers                                                                 |
| model     | Node                          | setpointManagerWarmest                           | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541968) | Node::setpointManagers                                                                 |
| model     | Node                          | removeSetpointManagerSingleZoneReheat            | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541969) | SetpointManagerSingleZoneReheat::remove                                                |
| model     | Node                          | removeSetpointManagerWarmest                     | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541970) | SetpointManagerWarmest::remove                                                         |
| model     | Node                          | removeSetpointManagerOutdoorAirReset             | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541971) | SetpointManagerOutdoorAirReset::remove                                                 |
| model     | Node                          | removeSetpointManagerFollowOutdoorAirTemperature | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541972) | SetpointManagerFollowOutdoorAirTemperature::remove                                     |
| model     | Node                          | removeSetpointManagerScheduled                   | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541973) | SetpointManagerScheduled::remove                                                       |
| model     | Node                          | removeSetpointManagerMixedAir                    | [1.13.0](https://github.com/NREL/OpenStudio/commit/40c19546076be456f110ca542cd70ce711541974) | SetpointManagerMixedAir::remove                                                        |
| model     | ZoneVentilationDesignFlowRate | setDesignFlowRateCalculationMethod               | [2.3.1](https://github.com/NREL/OpenStudio/commit/9ee9be2d0da3ed954a1e98cc3ab39ec7debffa92)  | Done when calling setDesignFlowRate, setFlowRateperZoneFloorArea, setAirChangesperHour |
