### ISSUE TITLE
Access model in arguments for Reporting Measures

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3623]
Currently, the arguments methods have the following signatures:

Model Measure
[virtual std::vector<OSArgument> arguments(const openstudio::model::Model& model) const;](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/measure/ModelMeasure.hpp#L63)

EnergyPlus Measure
[virtual std::vector<OSArgument> arguments(const openstudio::Workspace& workspace) const;](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/measure/EnergyPlusMeasure.hpp#L62)

Reporting Measure
[virtual std::vector<OSArgument> arguments() const;](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/measure/ReportingMeasure.hpp#L61)

The arguments method is called right before each measure is applied
https://github.com/NREL/OpenStudio-workflow-gem/blob/develop/lib/openstudio/workflow/util/measure.rb#L356

**Comment by macumber** [comment]
Propose adding runner as an optional second input to all arguments methods.  This would allow users to get the last OSM in EnergyPlus Measures, and last OSM or IDF in Reporting Measures.  You could also log error messages in the method, not sure where those would go in the out.osw.

**Comment by jmarrec** [comment]
The Reporting Measures one is fixed by https://github.com/NREL/OpenStudio/pull/3796

https://github.com/NREL/OpenStudio/blob/585e24973c863e2762788a90eb28fe556bb4479d/src/measure/ReportingMeasure.hpp#L65

Do we really want to add it to EnergyPlusMeasure.hpp? I

https://github.com/NREL/OpenStudio/blob/585e24973c863e2762788a90eb28fe556bb4479d/src/measure/EnergyPlusMeasure.hpp#L62

I think it's probably not a terribly good idea. EnergyPlus Measures can applied one after another, so manipulating a model that potentially is wildly different than the current workspace is likely to cause issue and lead to serious confusion by users. so I'm going to close that issue, but if you feel strongly the other way around, I suggest opening a separate and appropriately-titled issue (this issue title is specific to ReportingMeasures).
