### ISSUE TITLE
Construction with internal source does not update (Bugzilla #1301)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#364]
On 2013-06-26 15:27:54, @macumber wrote:

> Enter an invalid value into one of the fields (e.g. source layer after) such as 1000 or "hello", the set will fail and the field will eventually reset but should happen immediately.  Should not be able to enter "hello" in the first place.

**Comment by jmarrec** [comment]
Fixed. Reset happens whenever I leave the field or hit enter.

**Comment by evanweaver** [comment]
As tested, reset of "bad" data happens when field is exited. As for "Should not be able to enter "hello" in the first place.", this is not currently possible because of this change  https://github.com/NREL/OpenStudio/blame/develop/openstudiocore/src/shared_gui_components/OSDoubleEdit.cpp#L54 which occured in this commit https://github.com/NREL/OpenStudio/issues/1519 which fixes this bug https://github.com/NREL/OpenStudio/pull/2408.
