### ISSUE TITLE
Tab 1 - Names field is right vs. left justified when too long (Bugzilla #1306)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#367]
On 2013-06-28 10:44:10, @DavidGoldwasser wrote:

> When there is a really long name the start of the name is truncated.

**Comment by evanweaver** [comment]
@DavidGoldwasser shall we close this bug?

**Comment by DavidGoldwasser** [comment]
We still have the name right justified when everything else is left justified, and a long name doesn't wrap. While minor should still stay open.

**Comment by evanweaver** [comment]
@marj-schott thoughts?

**Comment by marj-schott** [comment]
@DavidGoldwasser I think it is not a good idea to make this different in one spot of the application. The user can adjust the panel to make it larger. Most users will have a larger screen then the application is designed for anyway and will have room to drag it out.

**Comment by DavidGoldwasser** [comment]
Ok, I give up, but just to clarify, I'm ok with the name being truncated, It just makes sense since it is left justified under normal circumstances, that the end of the name be truncated, vs. the beginning. And I think this should be the global behavior everywhere so we don't have a number like 320.22222 being displayed as 22222 instead of as 320.22. We ran across this in demo someone gave in iteration just last week.
