### ISSUE TITLE
AvailabilityManager:NightCycle applicability schedule fields

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#3702]
This is a two part issue.

A major bug:
When translating from .osm to .idf, the applicability schedule field is blank

And a minor bug:
[The translator](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAvailabilityManagerNightCycle.cpp#L68-L71) always assumes an always on discrete schedule regardless of  the user input in the OS App.

**Comment by luisclv** [comment]
May be related to #3568. In my case, if I set manually the schedule the translation is ok.

**Comment by jmarrec** [comment]
I don't see how the pplicability schedule field can be blank since it's set to AlwaysOnDiscrete in the FT (the links you gave). Can you explain the "major bug" @mdahlhausen please?

----

Also, regarding comments in #3568:

> Currently, the SDK does not provide access to changing items available in the openstudio and energyplus IDD. The most critical methods missing are methods that set the availability and fan schedules, therefore, measures cannot correctly implement the object.
> We could start with a setApplicabilitySchedule and a setFanSchedule method.

I agree setApplicabilitySchedule could be implemented.

For setFanSchedule, this would be breaking API. This is perhaps confusing but here's what's happening:
* You define the AirLoopHVAC's availability Schedule. This is what you see in the "Control" panel in the OS app as "Time of Operation"

![image](https://user-images.githubusercontent.com/5479063/66384811-b7038f80-e9bf-11e9-92b9-af0f4a12880e.png)

* This AirLoopHVAC availability Schedule is used as both:
   * The Fan Schedule for the supply fan that's on the AirLoopHVAC ("Availability Schedule Name")
       * If you have a Fan:VariableVolume on your AirLoopHVAC for eg, whatever you manually set as Fan Schedule will be overriden (therefore ignored). I know it's confusing, cf #3627. We do need to have the FanVariableVolume::setAvailabilitySchedule method because if this fan is used somewhere else than an AirLoopHVAC (ZoneHVACComponent...) then it's useful.
   * The Fan Schedule of the AVMNightCycle object if it exists.

Does that make sense? See proof below


-------

*Demonstration:**

```ruby
include OpenStudio::Model

m = Model.new
a = AirLoopHVAC.new(m)
sch = ScheduleRuleset.new(m, 1.0)
sch.setName("AirLoopHVAC Operation Schedule")
a.setAvailabilitySchedule(sch)

a.setNightCycleControlType("CycleOnAny")

fan = FanVariableVolume.new(m)
fan.addToNode(a.supplyOutletNode)
# This schedule will be overriden (and is useless in this context)
sch_fan = ScheduleRuleset.new(m, 1)
sch_fan.setName("Schedule Fan")
fan.setAvailabilitySchedule(sch_fan)

ft = OpenStudio::EnergyPlus::ForwardTranslator.new 
w = ft.translateModel(m)
puts w
```

```

AvailabilityManager:NightCycle,
  Availability Manager Night Cycle 1,     !- Name
  Always On Discrete,                     !- Applicability Schedule Name
  AirLoopHVAC Operation Schedule,         !- Fan Schedule Name
  CycleOnAny,                             !- Control Type
  1,                                      !- Thermostat Tolerance {deltaC}
  FixedRunTime,                           !- Cycling Run Time Control Type
  3600;                                   !- Cycling Run Time {s}


Fan:VariableVolume,
  Fan Variable Volume 1,                  !- Name
  AirLoopHVAC Operation Schedule,         !- Availability Schedule Name
   [...]
```

**Comment by mdahlhausen** [comment]
@jmarrec Thanks for looking into this more.  I can't explain the blank applicability schedule field.  It's come up in several user models, and I've been able to re-create it in models they've shared after deleting and reapplying the controls.  

_**I can also replicate this in an empty model, adding an air loop, and adding night cycle on control.**_

**Comment by jmarrec** [comment]
@mdahlhausen which version of OS are you using? I did a test today in ruby with develop (plus extended the FT gtest later) and couldn't replicate. I want to make sure #3711 did fix it.

**Comment by mdahlhausen** [comment]
@jmarrec that was with v2.8.1

**Comment by jmarrec** [comment]
@mdahlhausen I have just repeated the steps you gave me, I cannot reproduce it.

I've also tried the same via ruby.

```
include OpenStudio::Model
m = Model.new
a = AirLoopHVAC.new(m)
a.setNightCycleControlType("CycleOnAny")

ft = OpenStudio::EnergyPlus::ForwardTranslator.new
w = ft.translateModel(m)
```

```
puts w.getObjectsByType("AvailabilityManager:NightCycle".to_IddObjectType)
AvailabilityManager:NightCycle,
  Availability Manager Night Cycle 1,     !- Name
  Always On Discrete,                     !- Applicability Schedule Name
  Always On Discrete,                     !- Fan Schedule Name
  CycleOnAny,                             !- Control Type
  1,                                      !- Thermostat Tolerance {deltaC}
  FixedRunTime,                           !- Cycling Run Time Control Type
  3600;                                   !- Cycling Run Time {s}
```

**Comment by mdahlhausen** [comment]
@jmarrec It's fixed in 2.9.0.  I guess we can consider it resolved.

**Comment by mdahlhausen** [comment]
[Some users are seeing this in OS v2.9.0](https://unmethours.com/question/38974/night-cycle-error-in-openstudio/).  Issue #3730 is either the same or a similar issue.

**Comment by luisclv** [comment]
@mdahlhausen Issue #3730 is exactly what happens to me when I use the `Create Baseline Building` measure. I did not file it cause after reading this thread, I noticed that as you mention, the translation always [sets the Schedule ](https://github.com/NREL/OpenStudio/blob/b865c8d760527a29be72b08af016c33b6b87bab9/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAvailabilityManagerNightCycle.cpp#L68-L71)to `Always on`. I filed #3568 because previously (maybe 2.5.0 or 2.7.1) because I experienced the behavior described in #3730. Then I tried to change it with some ruby code, but couldn't find methods to do it.
