### ISSUE TITLE
IntegratedCollectorStorage object being incorrectly added to the PlantEquipmentList

### ISSUE THREAD

**Issue by jmaguire1** [NREL/OpenStudio#3761]
When trying to add an integrated collector storage solar collector, the plant equipment list is being generated with the collector, but it doesn't seem to be pulling in the equipment name correctly. Flat plate collectors seem to be working fine, this issue is specific to ICS collectors. Attached is an OSM created by our measures with the ICS that doesn't run in EnergyPlus; manually adding the collector name does allow the simulation to run.

[run.zip](https://github.com/NREL/OpenStudio/files/3844036/run.zip)

**Comment by shorowit** [comment]
@joseph-robertson @jmarrec

**Comment by jmarrec** [comment]
This is an IDD problem. I'm surprised that the FlatPlate is working.

To be able to place something on a PlantEquipmentList, that something has to be marked with `\reference validPlantEquipmentNames` (and Types). I had ran into a similar issue with ThermalStorage:Ice:Detailed a while ago:

```
ThermalStorage:Ice:Detailed,
  A1 , \field Name
       \required-field
       \reference IceThermalStorageEquipment
       \reference-class-name validBranchEquipmentTypes
       \reference validBranchEquipmentNames
================================ ADDED ======
       \reference-class-name validPlantEquipmentTypes  ! Need to be able to place it on PlantEquipmentList
       \reference validPlantEquipmentNames  ! Need to be able to place it on PlantEquipmentList
```

I'll extend the test on OpenStudio-resources, I realized the `SolarCollectorntegralCollectorStorage` and the `SolarCollectorFlatPlatePhotovoltaicThermal` aren't being tested for.

**Comment by MatthewSteen** [comment]
@jmarrec I don't believe OS allows a WaterHeater to be on the supply side of two plant loops (same for HeatExchangerFluidToFluid), so that's something that will need to be fixed and will also be helpful for heat recovery chillers.

**Comment by jmarrec** [comment]
@MatthewSteen Top of my head, I would say that E+ disallows a HX:FluidToFluid on two supply side, but I could be wrong there. I seem to recall having to model (in pure E+) this and not managing to do it with a HX and resorting to using a WaterHeaterMixed instead.

I don't think I ever tried to put a ChillerElectricEIR on two supply side... Are you talking about the Heat Recovery Inlet.Outlet Node Names? Then that's easy, it's a tertiary loop. I thoughtI opened an issue about it, but perhaps I didn't. A similar one I opened is https://github.com/NREL/OpenStudio/issues/3111. It's something I already implemented for CentralHeatPumpSystem including in OS App (connect to one supply side => primary, a demand side => secondary, a second supply side => tertiary)

It would be quite some work to allow a WaterHeaterMixed to connect to two supply side, but yes a separate "Enhancement request" issue is a good idea since this one is now closed....

I say quite some work because it inherits (justifiably) from WaterToWaterComponent which is meant to have one supply side and one demand side. It's entirely doable (and not terrible in term of coding), it's just from a UX perspective it would require careful thinking. For eg, you'd probably end up having to say that if you try to addToNode(supplySideNode) but it already is connected to the supply side of another plant loop; then you connect the "demand" (source side for WaterHeater) nodes instead. But that gets tricky / weird to use (especially in the context of OS App), and would throw people off since they are used to see it being disconnected from the previous one.
