### ISSUE TITLE
Order of Output:Meter:MeterFileOnly objects in IDF are not deterministic

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#3770]
Similar issue to https://github.com/NREL/OpenStudio/issues/3669, but occurs for `Output:Meter:MeterFileOnly` objects in the IDF when using `OpenStudio::Model::OutputMeter`.

@jmarrec

**Comment by jmarrec** [comment]
It took me a while to see what was going on but I think I got it now.

**I got thrown off by the fact that the ModelObject OutputMeter actually has a name field.**

```ruby
o = OutputMeter.new(m)
o.setName("Electricity:Facility")
o.name
=> "Electricity:Facility"
```

**Now convert that to a WorkspaceObject and hop! no name:**

```ruby
wo = m.getObjectsByType("OS_Output_Meter".to_IddObjectType)[0]
wo.name.get
RuntimeError: Optional not initialized
from (pry):95:in `get'
```

## Why?

Looking at the OpenStudio.idd, this is because the "Name" field isn't marked as `\type alpha` but as `\type external-list`

```
OS:Output:Meter,
       \memo each OS:Output:Meter command picks meters to be put onto the standard output file (.eso) and
       \memo meter file (.mtr). Not all meters are reported in every simulation. A list of
       \memo a list of meters that can be reported are available after a run on
       \memo the meter dictionary file (.mdd).
       \format singleLine
       \min-fields 1
  A1, \field Handle
       \type handle
       \required-field
  A2, \field Name
       \note Form is EnergyUseType:..., e.g. Electricity:* for all Electricity meters
       \note or EndUse:..., e.g. GeneralLights:* for all General Lights
       \type external-list
       \required-field
       \external-list autoRDDmeter
``` 

It is therefore not recognized has a name field in [IddField_Impl::isNameField()](https://github.com/NREL/OpenStudio/blob/52c211fd8bd9384b6490ba09b80a9d1b5b25cbcb/openstudiocore/src/utilities/idd/IddField.cpp#L202:L205)

```
[109] (main)> i = wo.iddObject.getField(1).get
=> #<OpenStudio::IddField:0x00564fffb5ed70 @__swigtype__="_p_openstudio__IddField">
[110] (main)> i.isNameField
=> false
[111] (main)> i.properties.type.valueName
=> "ExternalListType"
```

----

## What is external-list for?

As far as I can tell we aren't ever using the `external-list` things, which are used in E+ for the IDF Editor.

Taken from E+.idd:

```
!
!  \external-list   The values for this field should be selected from a special
!                   list generated outside of the IDD file. The choices for the
!                   special lists are:
!                        autoRDDvariable
!                        autoRDDmeter
!                        autoRDDvariableMeter
!                   When one of these are selected the options for the field
!                   are taken from the RDD or MDD file or both.
```

## Other cases of external-list

I have seen a few occurrences where some field that are external-list in Energy+.idd are actually different in OpenStudio.idd. These are the `OS:ElectricLoadCenter:XXX` objects, and they aren't the Name field itself.

E+:

```
       \type external-list
       \external-list autoRDDmeter
```

OS:

```
       \type alpha
       \memo type external-list
       \memo external-list autoRDDmeter
```

----

## Two solutions

1. Modify `IddField_Impl::isNameField()` to accept `ExternalListType` as well
2. Replace all occurences of `\type external-list` by `\type alpha` and move the external list stuff to a `\memo` like in the ECLD objects

Thoughts @kbenne?


---- 
Side Note: I'm not sure I really like the fact that there is shadowing in `std::string OutputMeter::name()` (shadowing `boost::optional<std::string> IdfObject::name()`

**Comment by jmarrec** [comment]
https://github.com/NREL/OpenStudio/pull/3774
