### ISSUE TITLE
No 'Constant Temperature' Schedule is registered for class SurfacePropertyOtherSideCoefficients 

### ISSUE THREAD

**Issue by agonzalezesteve** [NREL/OpenStudio#3848]
Trying to fix the temperature of a surface depending on a given schedule I got the following error:
`No 'Constant Temperature' Schedule is registered for class SurfacePropertyOtherSideCoefficients `

To reproduce:
`require 'openstudio'`
`model = OpenStudio::Model::Model.new `
`other_side_coefficient = OpenStudio::Model::SurfacePropertyOtherSideCoefficients.new(model)`
`other_side_coefficient.setConstantTemperatureSchedule(model.alwaysOnDiscreteSchedule)`

**Comment by eringold** [comment]
@agonzalezesteve 

I suspect because if you want to apply a constant temperature you can use the [Constant Temperature](https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-advanced-surface-concepts.html#field-constant-temperature) field.  `model.alwaysOnDiscrete` creates a Schedule:Constant, which is always just a single value (and you would be applying a surface temperature of 1C). 

To apply a scheduled temperature to SurfacePropertyOtherSideCoefficients you should apply a schedule with values that change, which wouldn't be a Schedule:Constant.

**Comment by eringold** [comment]
Hm, I spoke too soon. The same error occurs if you try to set a Schedule:Compact or Schedule:Ruleset. I think something's wrong with the `setSchedule` call here:

https://github.com/NREL/OpenStudio/blob/develop/src/model/SurfacePropertyOtherSideCoefficients.cpp#L271-L277

@jmarrec ?

**Comment by jmarrec** [comment]
Missing an entry in scheduletyperegistry, which handles checking scheduletypelimits 

https://github.com/NREL/OpenStudio/blob/635174fff495d437a6556b31831d797805060205/src/model/ScheduleTypeRegistry.cpp#L317

**Comment by jmarrec** [comment]
I'll fix it during the night or tomorrow morning

**Comment by jmarrec** [comment]
Should be fixed by #3849 thought I haven't tested (will rely on CI to build and test for me).

**Comment by jmarrec** [comment]
For a bad **workaround**:

`other_side_coefficient.setPointer(9, model.alwaysOnDiscreteSchedule.handle)`

Or you might as well go full-on bananas and use setString directly:

`other_side_coefficient.setString(9, model.alwaysOnDiscreteSchedule.handle.to_s)`

Never use setString/setPointer/setDouble/setInt directly on model objects, you loose all the built-in smart logic and checks we put in place. But if you get into a situation where you have no choice until a fix is release, then use at your own risk...
