### ISSUE TITLE
Store CI build status in public location

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#3994]
Enhancement Request
--------------
Store CI build status in public location

## Detailed Description
External collaborators make pull requests to the repository and CI runs on these.  If CI fails, the external collaborator can not see details to help them fix the pull request.

**Comment by macumber** [comment]
Also worth noting that external collaborators cannot apply labels to issues so they are not able to trigger CI.

**Comment by macumber** [comment]
I looks like you might be able to automatically apply labels based off of keywords in the PR template.  That would be useful if for instance an external collaborator could click a checkbox in the PR template which would apply the Ready for CI label,

**Comment by tijcolem** [comment]
This is more or less a security issue. At least here at NREL.  We have build logs now being pushed to an s3 bucket. @macumber I messaged you privately and can provide access to this so you can see log results. 

As far as the labels are concerned, looks like a user needs to have write access to the repo in order to apply labels  - https://docs.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests.  There may be other options (like the template), but for now, I think a collaborator that has write access will need to apply the label.

**Comment by tijcolem** [comment]
Since we are actively pushing to s3 and it's viewable externally, I'm going to close this issue.  We'll have a better longer-term solution to view logs but for now this will have to do.
