### ISSUE TITLE
Can't download components from BCL (using OpenStudio Application 1.0)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4014]
Issue overview
--------------
Reported by user here
https://unmethours.com/question/45690/cannot-download-components-from-bcl-in-openstudio-application-if-downloaded-direct-from-website-how-can-i-import-them-into-the-application/

I was able to reproduce on my computer for same material they mentioned, as well as a few others.

## Current Behavior
There is another issue where search doesn't work for some users. I was able to search for brick and select the material and click download. The download progress bar doesn't stop but I thought that was just GUI glitch. The component is shown as already downloaded with grey checkmark but isn't in BCL directory. User can't try to download again since it shows as already having it. I did same with a few more materials, so isn't unique to this.

view of app after attempt to download material, not progress bar doesn't stop moving, but checkmark changes form black to grey (which typically indicates download is complete)
![Screen Shot 2020-07-08 at 9 40 56 AM](https://user-images.githubusercontent.com/4857055/86940671-58ab3f00-c100-11ea-9800-4ac1e70bbca9.png)

View of app and file manager after 3 materials. Note the one object in directory is OpenStudio Results measure.
![Screen Shot 2020-07-08 at 9 43 17 AM](https://user-images.githubusercontent.com/4857055/86940739-65c82e00-c100-11ea-9f76-904319789701.png)

## Expected Behavior
Download to BCL directory and show in GUI at end of "Library" for materials

## Steps to Reproduce

Try to download using OpenStudio Application

## Possible Solution

Work around is to download with web browser (which other user was able to do) and then to load OSM as library.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Mac 10.15.3
 - Version of OpenStudio (if using an intermediate build, include SHA): OpenStudio Application 1.0

**Comment by DavidGoldwasser** [comment]
cc @tijcolem @kflemin @nllong

**Comment by tijcolem** [comment]
Can we confirm if this is in the SDK. If it's in the App we should move to https://github.com/openstudiocoalition/OpenStudioApplication

**Comment by DavidGoldwasser** [comment]
@joseph-robertson has been seeing this in the SDK using `OpenStudio::RemoteBCL.new`

**Comment by joseph-robertson** [comment]
I recall manually browsing to bcl.nrel.gov, and downloads were hanging...

**Comment by DavidGoldwasser** [comment]
This was reported again on UH and I can reproduce it with 1.0.1 app. @kflemin know measure download works now, could there be something different for components?

https://unmethours.com/question/47673/bcl-server-is-down/?answer=47692#post-id-47692 (look at comment under my answer, not the original post)

**Comment by jmarrec** [comment]
This is internal to the SDK I think. Here is some ruby code to test it. I'm testing it with 3.1.0 (because of #4282 can't do with develop)

```
[1] utilities(main)> remote.downloadComponent
[1] utilities(main)> remote = OpenStudio::RemoteBCL.new
=> #<OpenStudio::RemoteBCL:0x000055bb415be850 @__swigtype__="_p_openstudio__RemoteBCL">
[2] utilities(main)> results = remote.searchComponentLibrary("asbestos", "Material")
re=> [#<OpenStudio::BCLSearchResult:0x000055bb4163f338 @__swigtype__="_p_openstudio__BCLSearchResult">,
 #<OpenStudio::BCLSearchResult:0x000055bb4163f180 @__swigtype__="_p_openstudio__BCLSearchResult">,
 #<OpenStudio::BCLSearchResult:0x000055bb4163f040 @__swigtype__="_p_openstudio__BCLSearchResult">,
 #<OpenStudio::BCLSearchResult:0x000055bb4163ef28 @__swigtype__="_p_openstudio__BCLSearchResult">]
[3] utilities(main)> result.uid
NameError: undefined local variable or method `result' for main:Object
from (pry):3:in `__pry__'
[4] utilities(main)> result = results[0]
=> #<OpenStudio::BCLSearchResult:0x000055bb4163f338 @__swigtype__="_p_openstudio__BCLSearchResult">
[5] utilities(main)> remote.downloadComponent(result.uid)
=> true
[6] utilities(main)> component = remote.waitForComponentDownload()

# At this point, it hangs for 60secs

=> #<OpenStudio::OptionalBCLComponent:0x000055bb4089c258 @__swigtype__="_p_boost__optionalT_openstudio__BCLComponent_t">
```


[7] utilities(main)> component.get
RuntimeError: Optional not initialized
from (pry):7:in `get'
[8] utilities(main)> result.name
=> "Asbestos-cement Board- 1/4 in."
[9] utilities(main)> result.description
=> "Material from a data set created from ASHRAE HOF 2005 and ASHRAE 90.1-2004 Appendix A"
[10] utilities(main)> result.uid
=> "67656770-7926-0130-b66f-0026b9d40ccf"
```

Try again? it segfault

```
[9] utilities(main)> remote.downloadComponent(results.uid)
Trace/breakpoint trap (core dumped)
```

**Comment by jmarrec** [comment]
```
[7] OS-build-release(main)> t = Time.now; remote.getComponent(result.uid); t_end = Time.now;
[8] OS-build-release(main)> t_end - t
=> 60.395126426
```

I also cannot download from the BCL website either: https://bcl.nrel.gov/search/site/asbestos?f%5B0%5D=bundle%3Anrel_component

this seems to be a BCL server issue.

**Comment by jmarrec** [comment]
Both components and measures use the exact function to download it.

Example of getting a component (fails):

https://bcl.nrel.gov/api/component/download?uids=67656770-7926-0130-b66f-0026b9d40ccf

Example of getting a Measure (works)

https://bcl.nrel.gov/api/component/download?uids=5f126600-ca2f-4611-9121-6dfea2de49d6


For some reason the Component side of the BCL is super slower (that's is not a SDK thing). It just times out because of this:

https://github.com/NREL/OpenStudio/blob/eadff9598068b16479b1f5a223ee0611458d2fc6/src/utilities/bcl/RemoteBCL.cpp#L58-L68

I didn't see it originally because I thought the default was 2 min, not 1:

https://github.com/NREL/OpenStudio/blob/eadff9598068b16479b1f5a223ee0611458d2fc6/src/utilities/bcl/RemoteBCL.hpp#L181-L195

**Comment by jmarrec** [comment]
I increased the timeout to 120 seconds, and now it works;

[1] OpenStudio(main)> remote = OpenStudio::RemoteBCL.new; results = remote.searchComponentLibrary("asbestos", "Material"); result = results[0]
ù=> #<OpenStudio::BCLSearchResult:0x0000563455fb64b0 @__swigtype__="_p_openstudio__BCLSearchResult">
[2] OpenStudio(main)> t = Time.now; comp = remote.getComponent(result.uid); t_end = Time.now; puts "Elapsed time: #{t_end - t} seconds"
Elapsed time: 66.234140103 seconds
=> nil


It shouldn't crash though, I'll invesrtigate that.
