### ISSUE TITLE
Nightly build packages overwrite previous sha

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4070]
## Current Behavior
It appears that nightly builds overwrite previous packages if the sha does not change for several days.

## Expected Behavior
Nightly builds should be written to a different path or file name so they don't overwrite existing packages

### Context
OS App pulls down OS packages but cannot confirm these because the MD5 sum changes for the same package

**Comment by macumber** [comment]
@jmarrec fyi

**Comment by tijcolem** [comment]
The nightly build is on a cron to run daily regardless of a commit so that is why it's overwriting the s3 packages. This was set-up primarily due to conan dependencies that can cause issues and break the build and it's nice to be able to detect this early on.  This is less of an issue now as @jmarrec versioned our conan deps to our own remote but I think it's still good to run these nightly, at least for now.  

That said, I don't think CI needs to push the packages to s3 if there is already a matching version and commit sha. I'll make these changes to prevent that.

**Comment by tijcolem** [comment]
This is now enabled for the nightly builds. 

e.g. Output on Jenkins. 
<img width="1254" alt="Screen Shot 2020-09-09 at 3 03 18 PM" src="https://user-images.githubusercontent.com/7087120/92654970-dda40780-f2ad-11ea-9be6-52a4814992a8.png">
