### ISSUE TITLE
Expose the ability to change units of E+ output report OutputControl:Table:Style

### ISSUE THREAD

**Issue by arif-hanif** [NREL/OpenStudio#4117]
Enhancement Request
--------------
Currently openstudio does not map output control table style to idf, you have the ability to add summary reports but not change the units.

Provide the ability to add idf object to set the units of the tables.

**Comment by DavidGoldwasser** [comment]
@arif-hanif If you want to change the EnergyPlus SQL results to IP, there isn an [EnergyPlus measure for that on BCL](https://bcl.nrel.gov/node/82781).

However doing that will make the OpenStudio results skip because it doesn't see the units it expects in the results. That is documented a bit on [this UH post](https://unmethours.com/question/41162/energyplus-measure-set-output-table-to-ip-units/).

As a note if you want to change units in OpenStudio Results HTML report, there is a user argument for that, but for both SI and SI reporting, OpenStudio expects the SQL results to be SI. You can use the measure mentioned above to directly change EnergyPlus units to IP, and just not run OpenStudio Results. That should work fine.

Is your request to be able to change EnergyPlus units and still change EnergyPlus reporting units? That would require a large effort as many reporting measure that use SQL output or measures that do sizing runs are existing SI units. It would however be pretty easy to extend OpenStudio Results measure with additional tables, or make a new reporting measures that mimics the EnergyPlus tables you want to see.

**Comment by arif-hanif** [comment]
I was hoping for the sql file output to be in IP without a method by just passing in the output table units. it seems like this is a bigger issue with how open studio is wired.

**Comment by tijcolem** [comment]
@DavidGoldwasser Thanks for explaining the issue. I think there is too much risk to do this in SDK and should be handled via the measure that David talked about above.
