### ISSUE TITLE
ForwardTranslator.translateModel succeeds despite errors

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4170]
Issue overview
--------------
When calling `ForwardTranslator.translateModel`, there can be situations where the FT produces errors but still returns a workspace object. I can understand this happening for _warnings_, but did not expect this for _errors_. I would suggest that `translateModel` should return a null object if it encounters any errors, as this would indicate a problem that needs to be fixed.

Here's an OSM that will generate FT errors:
[in.osm.txt](https://github.com/NREL/OpenStudio/files/5725376/in.osm.txt)

And some sample code to illustrate:
```
require 'openstudio'
translator = OpenStudio::OSVersion::VersionTranslator.new
path = OpenStudio::Path.new("path/to/in.osm")
model = translator.loadModel(path).get
forward_translator = OpenStudio::EnergyPlus::ForwardTranslator.new
workspace = forward_translator.translateModel(model)
puts forward_translator.errors.size # <-- prints 5
puts workspace.to_s.size # <-- prints 989370; workspace exists despite 5 errors
```

Tested w/ OpenStudio 3.1.0.

**Comment by jmarrec** [comment]
```
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'surface WN-Bsmt window Rear-6 Reversed', and 'surface WN-Bsmt window Rear-6'
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'surface WN-Bsmt window Left-5 Reversed', and 'surface WN-Bsmt window Left-5'
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'FW-Bsmt window Rear-8 Reversed', and 'FW-Bsmt window Rear-8'
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'FW-Front buffered-2 Reversed', and 'FW-Front buffered-2'
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'FW-Bsmt window Left-7 Reversed', and 'FW-Bsmt window Left-7'
```

https://github.com/NREL/OpenStudio/blob/1e4f9fda38c9a4917b3a4a196a6c9f80d469502c/src/energyplus/ForwardTranslator.cpp#L3962-L3968

It defaults to using the construction of the first surface in that case. Which I guess is fine to some extent. Yet this is definitely something the user will need to take a look at, so issuing an `Error` message makes sense.

Technically, the Error log level isn't necessarily followed by an abort. This is similar to a `Severe` in E+ lingo. We do have a `Fatal` log level for that purpose. But generally speaking, `Error` messages in the FT are often followed by the object not being translated (eg: a HW coil not linked to a loop for eg). You can't really expect to not translate the surfaces here. And I personally would rather have an IDF produced here rather than stop everything, if not for debugging purposes.

https://github.com/NREL/OpenStudio/blob/1e4f9fda38c9a4917b3a4a196a6c9f80d469502c/src/utilities/core/LogMessage.hpp#L43-L59

My vote would be to leave this be. 

<details>
<summary>More log of the FT for the specific model (1 = Error, 0 = Warn, -1 = Info)</summary>
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'surface WN-Bsmt window Rear-6 Reversed', and 'surface WN-Bsmt window Rear-6'
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'surface WN-Bsmt window Left-5 Reversed', and 'surface WN-Bsmt window Left-5'
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'FW-Bsmt window Rear-8 Reversed', and 'FW-Bsmt window Rear-8'
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'FW-Front buffered-2 Reversed', and 'FW-Front buffered-2'
[openstudio.energyplus.ForwardTranslator] <1> Could not resolve matched surface construction conflicts between surfaces 'FW-Bsmt window Left-7 Reversed', and 'FW-Bsmt window Left-7'
[openstudio.energyplus.ForwardTranslator] <-1> SubSurface 'WN-Bsmt window Left-5' has a construction and 'WN-Bsmt window Left-5 Reversed' does not, using 'WN-Bsmt window Left-5''s construction.
[openstudio.energyplus.ForwardTranslator] <-1> SubSurface 'WN-Bsmt window Rear-6' has a construction and 'WN-Bsmt window Rear-6 Reversed' does not, using 'WN-Bsmt window Rear-6''s construction.
[openstudio.energyplus.ForwardTranslator] <-1> SubSurface 'DR-Garage-2' has a construction and 'DR-Garage-2 Reversed' does not, using 'DR-Garage-2''s construction.
[openstudio.energyplus.ForwardTranslator] <-1> SpaceType Plenum Space Type has no children, it will not be translated
[openstudio.energyplus.ForwardTranslator] <-1> SpaceType Space Type 1 has no children, it will not be translated
[openstudio.energyplus.ForwardTranslator] <-1> SpaceType Space Type 2 has no children, it will not be translated
[openstudio.energyplus.ForwardTranslator] <-1> SpaceType Space Type 3 has no children, it will not be translated
[openstudio.model.EnergyManagementSystemSensor] <-1>  does not have an Output Variable attached.
[openstudio.model.EnergyManagementSystemSensor] <-1>  does not have an Output Meter attached.
[openstudio.model.EnergyManagementSystemSensor] <-1>  does not have an Output Variable attached.
[openstudio.model.EnergyManagementSystemSensor] <-1>  does not have an Output Meter attached.
[openstudio.model.EnergyManagementSystemSensor] <-1>  does not have an Output Variable attached.
[openstudio.model.EnergyManagementSystemSensor] <-1>  does not have an Output Meter attached.
[openstudio.model.EnergyManagementSystemSensor] <-1>  does not have an Output Variable attached.
[...]
</details>

**Comment by jmarrec** [comment]
@shorowit Are you still dissatisfied enough to keep this open or does my explanation clears it out (if so, please close)
