### ISSUE TITLE
OpenStudio is enforcing some curve type limits that are too restrictive

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#4289]
This bug report originated from @TiejunWu and I am pasting in full because I think it very clearly explains the issue and there is no use reformulating an already well defined issue. This is a high priority. 

> I met some problem when I tried to use look up table for DX Coil performance in OpenStudio. Several of the functions like “setTotalCoolingCapacityFunctionOfTemperatureCurve”, returned a false when I tried to use a 2-D look up table as the parameter.
>  
> Then I looked into the OpenStudio source code here:
>  
> https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXSingleSpeed.cpp#L234-L247
>  
> Looks like in this function there is a check on the parameter “curve”, if will just return false if the parameter cannot be casted to be a Biquadratic curve.
>  
> However, such a check does not exist for the function setEnergyInputRatioFunctionOfTemperatureCurve. And I found that when I set a 2D lookup table to this function, it returned a true.
>  
> https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXSingleSpeed.cpp#L285-L298
>  
> When I model a DX coil directly in EnergyPlus, there is no such restrictions, I can use  2D lookup tables for Capacity as a function of temperature curve, Energy Input Ratio  Function of Temperature Curve and use 1D lookup table for Capacity Function of Flow Fraction Curve and Energy Input Ratio Function of Flow Fraction Curve, etc.
>  
> Can these checks be modified or removed for future versions of OpenStudio SDK so that lookup tables can be used to specify DX coil performance? Potentially we have to do so for all the DX coils.

**Comment by kbenne** [comment]
@lgentile and @tijcolem I would like to discuss the possibility of getting this into the release.

**Comment by TiejunWu** [comment]
I checked the relevant DX coil codes and here is a list of functions that may need to be modified to allow lookup tables to be used:

**1.  CoilCoolingDXSingleSpeed.cpp**

- **Function** setTotalCoolingCapacityFunctionOfTemperatureCurve (should allow a 2D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXSingleSpeed.cpp#L234

- **Function** setTotalCoolingCapacityFunctionOfFlowFractionCurve  (should allow a 1D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXSingleSpeed.cpp#L255

- **Function**  setEnergyInputRatioFunctionOfTemperatureCurve  (should allow a 2D lookup table, currently this is allowed, but its probably due to a typo in the check function, it only checks if the parameter can be casted to a Curve)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXSingleSpeed.cpp#L285

- **Function** setEnergyInputRatioFunctionOfFlowFractionCurve (should allow a 1D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXSingleSpeed.cpp#L306

**Function** setPartLoadFractionCorrelationCurve (should allow a 1D lookup table)
https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXSingleSpeed.cpp#L336



**2. CoilCoolingDXTwoSpeed.cpp**

- **Function** setTotalCoolingCapacityFunctionOfTemperatureCurve (should allow 2D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXTwoSpeed.cpp#L248

- **Function** setTotalCoolingCapacityFunctionOfFlowFractionCurve (should allow 1D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXTwoSpeed.cpp#L271

- **Function** setEnergyInputRatioFunctionOfTemperatureCurve (should allow 2D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXTwoSpeed.cpp#L296

- **Function** setEnergyInputRatioFunctionOfFlowFractionCurve (should allow 1D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXTwoSpeed.cpp#L319

- **Function** setPartLoadFractionCorrelationCurve (should allow 1D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXTwoSpeed.cpp#L344

- **Function** setLowSpeedTotalCoolingCapacityFunctionOfTemperatureCurve (should allow 2D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXTwoSpeed.cpp#L421

- **Fucntion** setLowSpeedEnergyInputRatioFunctionOfTemperatureCurve (should allow 2D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilCoolingDXTwoSpeed.cpp#L444

 **3. CoilHeatingDXSingleSpeed**

- **Function**  setTotalHeatingCapacityFunctionofTemperatureCurve (should allow 1D or 2D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilHeatingDXSingleSpeed.cpp#L461

- **Function** setTotalHeatingCapacityFunctionofFlowFractionCurve  (should allow 1D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilHeatingDXSingleSpeed.cpp#L483

- **Function** setEnergyInputRatioFunctionofTemperatureCurve (should allow 1D or 2D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilHeatingDXSingleSpeed.cpp#L503

- **Function** setEnergyInputRatioFunctionofFlowFractionCurve (should allow 1D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilHeatingDXSingleSpeed.cpp#L525

- **Function** setPartLoadFractionCorrelationCurve  (should allow 1D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilHeatingDXSingleSpeed.cpp#L545


- **Function** setDefrostEnergyInputRatioFunctionofTemperatureCurve  (should allow 2D lookup table)

https://github.com/NREL/OpenStudio/blob/f2930bbeb1031b731747c3393343f741b0fc11fa/src/model/CoilHeatingDXSingleSpeed.cpp#L566

I checked other DX coil codes like MultiSpeed and VariableSpeed coils, they do not seem to have a check of the curve types. So I assume they would allow any type of Curve to be used as the parameter,

**Comment by jmarrec** [comment]
@kbenne I think it's safe to remove these checks. We should just rely on the IDD references as needed... This was a good idea when this was implemented like 7 years ago, but nowadays with lookup tables and co it's impractical. Most (if not all of) E+ objects nowadays just use Uni/BivariateFunctions (and tri, quad, quint where appropriate...).

Anyways, these checks were a nice touch to prevent user from using curves that E+ would later reject in the source code, but 1) it shouldn't be the case anymore (E+ was made more agnostic to specific curves and will accept objects with right number of independant variables), and 2) it's actually hurting people trying to do things they should be allowed to do.

We could clean up our OpenStudio.idd to simplify/standardize around Uni/BivariateFucntions like E+ does in a second effort after the release.

**Comment by kbenne** [comment]
@jmarrec I agree. Time for these to go.
