### ISSUE TITLE
hidden files unexpectedly showing up in measure.xml file

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4373]
Issue overview
--------------
Measure.xml for new measure (made around 3.1) has .gitkeep in measure.xml. 

## Current Behavior
When I had delete that file and run measure manager gain it adds it back. 

## Expected Behavior
Should not add this file

### Environment

Mac using 3.2.1 installer

### Context
This was impacting my ability to upload measures to BCL.

**Comment by DavidGoldwasser** [comment]
Run `openstudio measure -u` on this measure and it adds it back, at least on my Mac, may not happen on another operating system.
https://github.com/NREL/openstudio-calibration-gem/commit/9480c96a3632f16d8839ef6bf505e671c5a28542

**Comment by tijcolem** [comment]
@DavidGoldwasser  Is this .gitkeep file in the measure really needed?  See dir: https://github.com/NREL/openstudio-calibration-gem/tree/develop/lib/measures/inspect_and_edit_parametric_schedules/docs

It appears measure manager is producing the correct set of files and tagging them as this file does indeed exist.  Since this is a hidden file and prefixed with a ".",   and is not getting packaged up correctly in the compressed file that uploads to BCL, we'll have to determine the call that compresses and make sure it includes hidden files. That is of course if the file is needed.
