### ISSUE TITLE
splitSurfaceForSubSurfaces at times creating more than 1000 of errors in file when splitting surface for door in WWR measure

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4374]
Issue overview
--------------
It is documented well in this issue, which also links to two UnmetHour posts
https://github.com/NREL/openstudio-model-articulation-gem/issues/76

## Expected Behavior
Should cleanly split door as shown in measure test

## Steps to Reproduce
Can run wwr measure with default arguments on prototype secondary school

## Possible Solution
Work around for now is for user to not split at door, but that isn't good. Need to make method in OS more robust. 

### Environment

Mac OpenStudio 3.2.1 via OpenStudio Application

### Context
This is very problematic.

**Comment by ggartside** [comment]
@DavidGoldwasser  Can you expand a bit on the repro steps?

Where do I find the WWR measure?
How did you get he secondary school ref building into open studio? did you import the IDF file?
Why do you split the surfaces? What purpose does this serve?

**Comment by ggartside** [comment]
@macumber Maybe you can help, I'm looking at splitSurfaceForSubSurfaces. After the masks have been created the method iterates over the masks and does an intersection with the mask and the original surface polygon which will return 2 polygons, the common area and the remainder. Then the next mask is then intersected but this should only intersect with the polygon that was not the common area from the previous intersection as the sub surfaces do not overlap. 

But looking at the code from this method

`      for (const Point3dVector& mask : joinedMasks) {
        std::vector<Point3dVector> tmpFaces;
        unsigned numIntersects = 0;
        for (const Point3dVector& face : newFaces) {
          // each mask should intersect one and only one newFace
          boost::optional<IntersectionResult> intersection = openstudio::intersect(faceVertices, mask, tol);
          if (intersection) {
            numIntersects += 1;
            tmpFaces.push_back(intersection->polygon1());
            for (const Point3dVector& tmpFace : intersection->newPolygons1()) {
              tmpFaces.push_back(tmpFace);
            }
          } else {
            tmpFaces.push_back(face);
          }
        }

        if (numIntersects != 1) {
          LOG(Warn, "Expected each mask to intersect one and only one face");
        }

        newFaces = tmpFaces;
      }`

So the method iterates over newFaces (now there are two) and calls intersection with the ** faceVertices, i.e. the original surface vertices** and the mask so here there will be two intersections because it is doing the same intersection twice.

I think the intent of this method is to subdivide the Surface into a number of surfaces that each contain only one sub surface and I think this line

`boost::optional<IntersectionResult> intersection = openstudio::intersect(faceVertices, mask, tol);`

should be

`boost::optional<IntersectionResult> intersection = openstudio::intersect(face, mask, tol);`

can you confirm?

**Comment by macumber** [comment]
Haha that method is way too confusing.  I think you might be right about what is happening there.  I guess the only way is to try it out and see how it works...

**Comment by macumber** [comment]
Do you see a bunch of warning messages in the log saying "Expected each mask to intersect one and only one face"?

**Comment by ggartside** [comment]
Yes a bunch of those messages
