### ISSUE TITLE
Crash in floorplanToThreeJS

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#4384]
Issue overview
--------------
Static analysis fix in https://github.com/NREL/OpenStudio/commit/20750c86aa75f9b33195bf0584feea3e25768138#diff-e7f60390b7a35595826d546094f1d55f5b81e7fbc56bae88fdcbdff62729eec3L922 created a bug where we changed the `faceVertices` loop variable.

## Current Behavior
floorplanToThreeJS can crash

## Expected Behavior
floorplanToThreeJS should not crash

## Steps to Reproduce
Convert the attached Floorplan JSON file to ThreeJS in non-openstudio format

**Comment by macumber** [comment]
[Floorplan.json.txt](https://github.com/NREL/OpenStudio/files/6911462/Floorplan.json.txt)

```
require 'openstudio'

puts "1"
t1 = OpenStudio::floorplanToThreeJS('Floorplan.json', true)
puts "ok"

puts "2"
t2 = OpenStudio::floorplanToThreeJS('Floorplan.json', false)
puts "ok"
```

**Comment by jmarrec** [comment]
It's hard to fix the actual diff in the link commit, but this is it, in src/utilities/geometry/FloorplanJS.cpp

![image](https://user-images.githubusercontent.com/5479063/128136413-81eecf77-b2f3-424c-ac23-57acd3bab151.png)

Instead of shadowing the outer variable (which cppcheck picked up), this change reassigned it.
