### ISSUE TITLE
Clarify what export IDF does, and maybe offer two options

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#441]
In the past using the file menu to "export idf" got you the exact same IDF you end up with if you run your simulation. Now that we are including always run measures as part of a model (even though external to the .osm) file, users may be confused about what export idf will produce.

The easy solution is to leave it like it show a dialog saying "The exported IDF does not include the affect of any always run measures". The next solution would be to run the measures as part of this export, but that is tricky, if "Radiance" is checked, does that me you do a radiance run to get the same IDF that would have been passed off to EnergyPlus in an OpenStudio run.

This is low priority but I just wanted to document it.

**Comment by macumber** [comment]
@DavidGoldwasser @asparke2 I'm not sure this is valid, can this be covered by documentation?

**Comment by asparke2** [comment]
@macumber In my opinion, this should be documented in the SketchUp plugin documentation and then closed.  There is already [documentation for import and export options](http://nrel.github.io/OpenStudio-user-documentation/getting_started/features/#import-and-export-options) but that doesn't cover what this issue is about.

**Comment by macumber** [comment]
@DavidGoldwasser can we close this?
