### ISSUE TITLE
Importing GbXML file into OS will result into change in the naming of some of the spaces 

### ISSUE THREAD

**Issue by rwadhwa910** [NREL/OpenStudio#4425]
I am importing geometry from IES and while importing I am not able to import some of the names for these spaces.

OS 3.2.0. Windows 10 OS app 1.2.0
![OS](https://user-images.githubusercontent.com/63880759/131384268-373725c9-3325-42c8-8d83-031fd78d7265.PNG)

**Comment by jmarrec** [comment]
@rwadhwa910 Can you provide an example please?

**Comment by rwadhwa910** [comment]
> @rwadhwa910 Can you provide an example please?

Here is the link to the XML file.

https://drive.google.com/file/d/1ULIolNCC1-w8q2yTTuz0TpKyEj4deMb5/view?usp=sharing

**Comment by macumber** [comment]
The issue here seems to be that both spaces id="PD000001" and id="PD000004" have the same name "Pod 1 Multiple Classrooms".  OpenStudio requires that spaces have unique names so one of the spaces is given a random name.  This could be handled better e.g. by naming one space "Pod 1 Multiple Classrooms" and the other "Pod 1 Multiple Classrooms 2" or something.

**Comment by tijcolem** [comment]
Thanks for the comment @macumber. I don't view this as issue/bug as names should be unique. I am going to close this issue but happy to reopen if other ideas come up to support having the same name.
