### ISSUE TITLE
E+ 22.2.0 - `ZoneMixing` is now allowed at space level

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4673]
Allow setting ZoneMixing to a Space in model namespace?

**Comment by shorowit** [comment]
I'm running up against an E+ 22.2 error because of this. We assign a ZoneMixing object to a thermal zone (because that's all OpenStudio allows) and the thermal zone has two spaces in it, so E+ automatically reassigns the ZoneMixing object to each Space. Then our code tries to actuate the zone-level ZoneMixing object but it no longer exists and we get an error.

If we could assign a ZoneMixing object to a space and it was FT to E+ like that, it would eliminate our error.

**Comment by jmarrec** [comment]
this is going to require a (minor) ABI break. this one cannot stay at all (can't deprecate / overload to work around it) https://github.com/NREL/OpenStudio/blob/490d7848e2f0def6186ef4e1f40e7d7309ea1f33/src/model/ZoneMixing.hpp#L68
