### ISSUE TITLE
Review SqlFile wrapped queries for 'Additional Fuel'

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio#4705]
Issue overview
--------------
The SqlFile wrapped queries need some review. For example : https://github.com/NREL/OpenStudio/blob/6640698cfbf0d5fee1461f80fd343b396a226321/src/utilities/sql/SqlFile_Impl.cpp#L1561-L1565
Although the wrapped queries are still in use (for example in the Xcel reporting measure) I don't think ColumnName ='Additional Fuel' exists anymore and the queries are all returning 0.

**Comment by tijcolem** [comment]
@kflemin Would you be able to go through the otherFuel sql queries and determine which ones broke, or returning zeros? 
Probably want to look into adding some tests for this as well as these could change again.

**Comment by kflemin** [comment]
@tijcolem 2 questions:

1. I believe that multiple new Fuels were added: Gasoline, Diesel, Coal, Fuel Oil No 1, Fuel Oil No 2, Propane, Other Fuel 1, Other Fuel 2.  I am not sure what "Additional Fuel" used to cover (was it just Other Fuel 1, or a combination of some of the fields above?) 
2. depending on the answer to #1, should we be adding SqlFile_Impl methods for those other fuels? right now there are only methods for electricity, natural gas, other fuel, district heating, district cooling, and water.

@DavidGoldwasser, do you know what "Additional Fuel" used to represent?

**Comment by shorowit** [comment]
My two cents: deprecate the additional fuel methods and create new methods for each fuel type. (That will help ensure that a user doesn't double count energy use by asking for both, e.g., fuel oil energy use and additional fuel energy use, the latter of which includes fuel oil.)

**Comment by asparke2** [comment]
Fully agree with deprecating the `otherFuelFoo` methods (in both `SqlFile` and `Facility`) and adding methods specifically for the listed fuels, otherwise the query always returns zeroes, which is worse.  Just hit this doing an OS 2.9.1 to 3.4.0 migration for ComStock.

For reference, here is the table in EnergyPlus before they changed the fuel type enumerations and reporting:
![image](https://user-images.githubusercontent.com/2009290/196790029-f6e28bc8-349f-465c-8298-2ff75d83c120.png)

And the same table after the changes (not from the same model) This shows the fuels that need to have methods added. Note that Other Fuel 1 and Other Fuel 2 are NOT the same as the previous Additional Fuel column:
![image](https://user-images.githubusercontent.com/2009290/196790106-e53e194d-b71a-482c-bfc2-41a3652c68e8.png)

In the older versions of EnergyPlus:
Additional Fuel = Gasoline + Diesel + Coal + Fuel Oil No 1 + Fuel Oil No 2 + Propane + Other Fuel 1 + Other Fuel 2

I agree with @shorowit, don't re-map the query to match the sum of the previously-included columns because people will likely double-count the fuels, think `otherFuelFoo` returns Other Fuel 1 + Other Fuel 2, or some other similar mistake.
