### ISSUE TITLE
Making Python Binding interaction more Pythonic

### ISSUE THREAD

**Issue by GFlechas** [NREL/OpenStudio#4745]
Enhancement Request
--------------
Making working with the Python bindings feel more native to Python than their current form by leveraging python data structures such as dictionaries for model manipulation.

## Detailed Description
In their current form, using the Python OpenStudio bindings as a proficient python programmer is tricky. The [Full OpenStudio SDK Documentation](https://openstudio-sdk-documentation.s3.amazonaws.com/index.html) is useful for getting a sense of what changes can be made to an object, but figuring out syntax conversion is not intuitive. Given that Python Measures are close in the pipeline, this feels significant to consider before broad adoption. My understanding is that the Ruby Measures are more like a C flavored ruby (though please correct me if I'm wrong here) which is a moderate barrier to entry for new OpenStudio users if they want to start writing measures. So before Python measures get widespread use (given Python's broader adoption especially with new coders), it seems like a good time to make the flavor of the python bindings more intuitive.

I'm specifically thinking of the way python handles iterable objects and its dictionaries so my examples are tilted with that direction in mind, however, I suspect there are other python features I'm overlooking that would be useful ways to engage with an OpenStudio model.

At a high level, OpenStudio model objects in python don't appear iterable. If I grab all the objects in a model like in the code below, I haven't found a built-in way to iterate through the objects themselves and see what I have. Say I wanted to visualize all the different objects in a model, unless I parse all the objects as strings (`object_as_string = str(object)`) and break them apart, I can't find a way to collect all the Thermal Zones, all the Spaces, all the Load Types, etc in a generalized capacity. There's targeted ways (like getSpaces, getThermalZones), but these require me to know the attribute I'm trying to access rather than being able to generalize code. Additionally, I can't iterate a model object's settings (it looks like these might be called fields?) to see what's available or to alter them.

I think one way to do this would be interacting with the model objects as dictionaries. In the following example, this seems like an intuitive way to inspect and then alter an object in Python. If I had a thermal zone and wanted to see what settings were available, a dictionary seems the most intuitive. Then if I wanted to assign a new thermostat, using this dictionary structure seems like the most intuitive way to assign it.

```
translator = openstudio.osversion.VersionTranslator()
osm = translator.loadModel(path_model).get()

zones = osm.getThermalZones()
interest_zone = zones[0]
zone_name = interest_zone['name']
zone_settings = interest_zone['settings']
for field, setting in zone_settings.items():
     print(f"{field} is set to {setting}")

# Maybe I want to alter the thermal_zone setpoint
new_setpoint = openstudio.model.ThermostatSetpointDualSetpoint(osm)
zone_settings['setpoint'] = new_setpoint
```

There also doesn't appear to be a 'type' attribute to objects. I can't figure out how to take an object and figure out if it's a Thermal Zone, a Space, a Node, etc. A type() attribute similar to name() would be useful. Maybe it's already in there, but I've been using 'dir(obj)' and sorting through attributes trying to find something with no luck so far. This may not be a super useful bit of code, but hopefully illustrates what I'm thinking.

```
model_handles = osm.handles()
model_objects = osm.getObjects(model_handles)
focus_type = "OS:Thermal Zone"
types = [obj for obj in model_objects if obj.type() in [focus_type]]
zones = [type for type in types if type in ["OS:Thermal Zone"]]
```

Additionally, OpenStudio model objects aren't hasable. This is an aspect of Python I'm not fully comfortable with, but I noticed there isn't a __hash__ attribute to objects. This seemed odd given that every object has it's UUID which operates on the a similar premise to a hasable object in python. I haven't yet bumped into a usecase where I needed an object to be hashable, but figured it was worth noting.

I think the real benefit that's opened up to the OpenStudio ecosystem with Python bindings is how much more approachable using measures will become. Measure writing looks like it's predicated on knowing exactly what you can do with a model, or at least that's the way that it feels. I think Python's object structure usually makes it easy to learn new modules because they can be "inspected" within a notebook if you're not sure how to use them. And inspecting and working with the Module in a notebook while checking back and worth with the documentation makes it pretty fast to get things rolling. There's enough syntax difference between Ruby and Python that the SDK documentation is hard to adopt as a new learner. 

I don't fully appreciate how hard this would be to implement with the Python bindings. I hope none of this comes across as trivializing how much work an enhancement like this would take. I've just seen discussion about Python Measures in the pipeline and wasn't sure the best venue to communicate this feedback. I'm extremely excited by the prospect of Python Measures and know a lot of work has gone into the bindings up to this point. This seems like the best time to potentially adapt the coding style required for interacting with the bindings before people begin writing and publishing measures for the BLC down the road. And if something I've discussed here doesn't make sense I'm really happy to chat about it further.

Thanks for reading!

## Possible Implementation
I realize the python bindings get made by an external program, so maybe rather than altering the bindings themselves, possible integration would be a helper module. So you'd `import openstudio` and then also something like `import openstudio_pythonic as osp` where the helper module middlemans between the official bindings and more pythonic interaction. Maybe you'd just need to import the helper module itself unless you needed to do something specialized and then you could `import openstudio`. 

I'm not sure what the process looks like for compiling the bindings, but having a separate module that sits between the user and the official bindings could potentially mitigate some double work. Maybe the helper module would go through and handle converting the OS objects to dictionaries, lists, and strings, and then when users modify values it goes through and converts back to the appropriate OS object types.

**Comment by jmarrec** [comment]
@GFlechas thanks for the detailed suggestions. 

I guess a numbered list would be helpful to discuss here, as there has several different and distinct points here, and I hope I cover all of them:

1. Using a dictionary instead of method names.

This is not going to happen. Not only for technical/feasibility reasons, but because I strongly disagree. Each object in OpenStudio has nice API with getters and setters for each field. The naming convention (lowerCamelCase) we use for this will 99% of the time let you figure out a getter /setter name from just **printing** out the object.

If you use a sensible editor (Ipython, Jupyter notebook), you get **TAB** completion working as well.

Given a Field "Floor Area", I know the getter is probably `floorArea`, the setter `setFloorArea(double)` (and there are potentially a isFieldNameDefaulted and  resetFieldName if the field is optional, and there could be isFieldNameAutosized / autosizeFieldName if the field is autosizable)

<img width="753" alt="image" src="https://user-images.githubusercontent.com/5479063/208922164-d7e56e9b-3ee3-42b8-8305-8f37f8a27b39.png">


**AND** that API is the same in C++, C#, Ruby, Python. This is a hard selling point.

This is WAY better than having a dictionary. You'll still have to inspect the dictionary keys anyways, but you'll miss all of the other features.

2. Getting an object type

```python
In [10]:  obj = m.modelObjects()[3]
In [11]: print(obj)
OS:PortList,
  {70c78953-9f36-46c6-b69c-811dfcda8078}, !- Handle
  {3892b69b-c71e-44d5-95b8-8b64863dc346}; !- HVAC Component

In [12]: obj.iddObjectType().valueName()
Out[12]: 'OS_PortList
```

Here's a ruby method (but you can do the same in python, since we use the same API for all languages, see how nice that is?) I use to cast any ModelObject to its derived type: https://github.com/jmarrec/Pry-and-Powershell-for-OpenStudio/blob/90c7a7396d45e6490e0d1595831feca8789c5cfe/.pryrc#L108-L146


3. Getting objects in a generalized way

`m.modelObjects()`? Then you loop on these and check the iddObjectType? Or you use the getSpaces() + getThermalZones() (in which case you have the derived object, not the ModelObject, but you can also do derived.to_ModelObject, and modelObject.to_Derived to go the other way)

4. Listing fields in an object

Aside from just printing the object and seeing it's serialization (which includes the names of the fields) you can also query the IddObject attached to an object (it's less convenient than just printing, I would use that only to try and do some generalized things). Eg I can print all the fields in an object:

```python
iddObject = z.iddObject()
for i in range(iddObject.numFields()):
    f = iddObject.getField(i).get()
    print(f.name())
```

Each field also has a properties() method and from there you can tell if a field is autosizable, autocalculate, etc, and you can get it's `type().valueName()`

Your imagination is the limit if you want to use that, eg:

```
iddObject = z.iddObject()
for i in range(iddObject.numFields()):
    f = iddObject.getField(i).get()
    getter = f.name().replace(' ', '')
    getter = getter[0].lower() + getter[1:]
    try:
        func = getattr(z, getter)
        val = func()
        print(f"Field '{f.name()} is a {f.properties().type.valueName()}, {getter=}, {val=}")

    except AttributeError:
        print(f"Field '{f.name()} is a {f.properties().type.valueName()}")
```

Our API is quite consistent and this because we internally use these features (in ruby) to generate boilerplate C++ code for an object from its IDD when we first add it. an extract: https://github.com/NREL/OpenStudio/blob/c66aa6dbff58e93d09c8f1064167f684e0eace5a/developer/ruby/SubProjectClassGenerators/ModelClassGenerator.rb#L228-L244


If this is still escaping you, I would suggest you get a few hours of training on OpenStudio SDK and Scripting to clear out the confusion and cover some less known things like the understanding the concept of OptionalClass object instances.

(Disclaimer: I provide such trainings, but note there are other providers. I'm not trying to sell anything, this is a genuine recommendation)

5. Making an object hashable.

I'm not sure what applications would require this to be honest, and it's trivial to work around it. If you want to use objects as dict keys, just use the handle instead, which is hashable. eg this works fine: `d = {}; d[z.handle()] = 'A'`

6. Further thoughts

If you do find other areas where you think things can be improved, please report it to us.

For eg, it's possible that some classes still aren't exposed correctly in the right namespace, similar to this fixed issue: https://github.com/NREL/OpenStudio/issues/4133 where you initially had to do `fan = openstudio.model.openstudiomodelstraightcomponent.FanVariableVolume(model)` instead of `fan = openstudio.model.FanVariableVolume(model)`

**Comment by jmarrec** [comment]
I'm closing this issue, but feel free to add comments
