### ISSUE TITLE
Allow `ScheduleFile` constructor with path instead of ExternalFile argument

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#4763]
Issue overview
--------------
Running the following command on Windows:
`external_file = OpenStudio::Model::ExternalFile::getExternalFile(@model, schedules_path)`

It's throwing an error:
`OS Message: Failed to copy file from "C:/Users/shorowit/AppData/Local/Temp/1/schedules20221212-6228-2tv9lb.csv" to "C:/Program Files (x86)/NREL/BEopt_3.0.0/./files/schedules20221212-6228-2tv9lb.csv"`

https://github.com/NREL/OpenStudio/blob/70df42e000cfe751e28a1e8c33b3c0c2e13786be/src/model/ExternalFile.cpp#L277

I can't tell if the problem is that it doesn't have permission or that there's a space in the path. Either way, I don't think there's a way to tell OpenStudio where to copy this file, so it'd be nice if it could more gracefully handle this.

**Comment by shorowit** [comment]
Why does OpenStudio have to make a copy of the schedule file anyway? Can't it just use the file directly for the EnergyPlus IDF? That would A) prevent issues like this and B) prevent having lots of extra files that aren't cleaned up when running lots of simulations.

Seeing if I can develop a workaround for BEopt...

@jmarrec @macumber @tijcolem @joseph-robertson

**Comment by jmarrec** [comment]
I think the rationale was a model (with its companion directory) should be self contained so you don't run into issues if you simply move or modify a CSV file. After copying, the path is relative and relocating the model, such as moving back/forth a temp directory like OSApp does, just works.
I think this rationale is sound.

**Comment by jmarrec** [comment]
@shorowit what is schedules_path in your example? And what your cur directory and your model's path?
Trying to see if there is an actual bug here or just a feature request/suggestion.  Thanks

**Comment by shorowit** [comment]
@jmarrec Looking back at this with fresh eyes, I think I really have a feature request.

My feature request is to add a `ScheduleFile` constructor that allows a path instead of an `ExternalFile` argument. Our residential software tools/workflows don't use the "companion directory" approach that the OS app does, and the use of an external file for ScheduleFiles creates more complications/headaches for us than anything. And it results in extra copies of CSV files in weird locations. Adding a second constructor would allow us to avoid the OS issue altogether, so we can just point the OSM directly to the CSV file path of our desire.

Is this feature request possible/practical?

**Comment by jmarrec** [comment]
I think that makes sense. I can look into whether that's pratical or not. If it is, we should clearly document that the user is responsible for ensuring the file exists and is valid though (a use at your own risk disclaimer basically)

**Comment by joseph-robertson** [comment]
Seems like we'd need to update the IDD. We'd need to either (a) have Schedule:File's "External File Name" field accept a `\type url`, or (b) introduce a new field, e.g. "File Path", that accepts a `\type url`. Something like that?

**Comment by joseph-robertson** [comment]
Also wouldn't we need an API break on `ExternalFile externalFile() const;` to `boost::optional<ExternalFile> externalFile() const;`?

**Comment by shorowit** [comment]
Could you leave the IDD/API how it is now but, when a path is supplied to the `Schedule:File` overload constructor, automatically create an `ExternalFile` object behind the scenes that points to the specified path? So everything would work like it does now, in that the `Schedule:File` still points to an `ExternalFile`, but the `ExternalFile`'s File Name would point to the original path and not a copied location. That seems like it would minimize the changes needed.

**Comment by joseph-robertson** [comment]
So we'd need a new `ExternalFile` constructor (or use the existing ctor and introduce some kind of optional flag) that sets File Name as the full path, and also doesn't do all the parent folder / copy file stuff.

**Comment by shorowit** [comment]
Sounds right to me.

**Comment by shorowit** [comment]
Actually, make that's the better solution. I there was a new `ExternalFile` constructor (or existing ctor with optional flag), then you wouldn't have to make any changes to the `ScheduleFile` object. On our end, we could make use of it and then just continue to pass an `ExternalFile` object to the `ScheduleFile`. That's even less of a change on your end.

**Comment by shorowit** [comment]
(I vote for the optional argument.)

**Comment by joseph-robertson** [comment]
I kind of like the idea of a `ScheduleFile` ctor where you pass in a path, though. Seems nice to not have to deal with another model object.

**Comment by jmarrec** [comment]
I'm thinking out loud here, on purpose. I'll write up my recommendation when I'm done thinking about it.

ExtrernalFile's ctor is `private` on purpose. The factory static method `ExternalFile::getExternalFile` is what's public and does an added check of returning any existing ExternalFile that has the same requested filename. It then forwards to `ExternalFile::ExternalFile(model, filename)` which does copy it.

https://github.com/NREL/OpenStudio/blob/42683d615dd470d90390175c1fdc884039dbd767/src/model/ExternalFile.cpp#L209-L283

We could make the ctor public, but I think that would create confusion.

The ScheduleFile Ctor taking only a path, while convenient, is maybe not such a good idea because the current one is, by design, taking an ExternalFile **and** a column number, and you want to avoid instantiating several ExternalFile objects to point to the same file. I think we want to retain that behavior.

I think `ExternalFile::getExternalFile` should always have taken a `path` instead of a `std::string`... Internally it does convert it to a path... Not sure we want to break API there (though bindings users wouldn't be affected, but C++ ones would)

----

Suggested approach:

* modify ExternalFile

```diff
-    static boost::optional<ExternalFile> getExternalFile(const Model& model, const std::string& filename);
+    static boost::optional<ExternalFile> getExternalFile(const Model& model, const std::string& filename, bool copyFile = true);
[...]
private:
-    ExternalFile(const Model& model, const std::string& filename);
+    ExternalFile(const Model& model, const std::string& filename, bool copyFile = true;
```

if `copyFile` is false, ensure the path that `filename` represents is absolute and stop there.

* Add the overloaded ScheduleFile ctor that takes a path

```c++
    ScheduleFile(const openstudio::path& externalFilePath, int column = 1, int rowsToSkip = 0);
```

I'm am now going to check out Joe's PR and will review the initial implementation based on the above.
