### ISSUE TITLE
BCL dialog units should match user preferences for SI or IP

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#477]
I think this has always shown IP regardless of whether the user preference was set to SI or IP.

Work around used to be to use the BCL website, but looks like that also just shows SI for now.
https://openstudio.nrel.gov/forums/openstudio-plug-sketchup/general-discussion/questions-about-climate-thermal-zones

**Comment by evanweaver** [comment]
@DavidGoldwasser @macumber @axelstudios Currently, there is no provision for BCL units conversion.  The units' string in the BCL is free-form, and since it follows no convention, I think that it would likely open a much larger can of worms if I get the string from the BCL, parse it in the app, and then attempt to determine if it can be converted from SI to IP.

A much more holistic approach would be for the BCL to add units type checking and also provide a conversion engine.

I think we should choose to close this bug, and not act on it, but I want your collective input.

**Comment by axelstudios** [comment]
I don't foresee any major updates to the BCL or the API, and attempting to parse and convert the values in the BCL dialog is definitely asking for trouble

**Comment by DavidGoldwasser** [comment]
The original BCL did switch units in web interface, but that broke (or was a feature of the new one). I'll just flag this as won't fix. At some point will have to go back to it.
