### ISSUE TITLE
Ruby/Python Workflow crash

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#4945]
The attached workflow is crashing on Mac OS.

[Crash.zip](https://github.com/NREL/OpenStudio/files/12441782/Crash.zip)

**Comment by jmarrec** [comment]
@kbenne I can create a crash - on macOS at least - using a single ruby measure, just placing some dumb error in there.

```
OpenStudio::Vector3d.new("WRONG TYPE")
```

I found that because it crashed with a single measure [create_bar_from_space_type_ratios](https://github.com/NREL/openstudio-model-articulation-gem/blob/e20645aed0f4b5c69deeec2087d06418d296c0d4/lib/measures/create_bar_from_space_type_ratios/measure.rb#L274), when I didn't pull the merge of: 
* https://github.com/NREL/OpenStudio/pull/4960


This throws in ruby:

```
ArgumentError: Wrong arguments for overloaded method 'Vector3d.new'.
Possible C/C++ prototypes are:
    Vector3d.new()
    Vector3d.new(double x, double y, double z)
    Vector3d.new(openstudio::Vector3d const &other)
```

But during the `openstudio labs run -w workflow.osw` you get the infamous rb_ec_tag_jump with a crash dump.
