### ISSUE TITLE
Default to space-level FT

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#5007]
Enhancement Request
--------------
The ability to FT to spaces instead of zones was first introduced in [OpenStudio 3.3](https://github.com/NREL/OpenStudio/releases/tag/v3.3.0) (Nov 2021) as an opt-in capability. It allows taking advantage of new capabilities in EnergyPlus (that were, in part, developed to match OpenStudio) and simplifies the translation of the OpenStudio model to EnergyPlus.

I think everyone agrees that it should become the default FT behavior and _opt-out_ at some point. But when?

@kbenne @jmarrec @joseph-robertson @DavidGoldwasser

**Comment by jmarrec** [comment]
3.5.0 from memory no?

**Comment by brianlball** [comment]
@mdahlhausen

**Comment by mdahlhausen** [comment]
I'm happy to align openstudio-standards with this in the next release.

**Comment by kbenne** [comment]
I'm going to close this because I realize now that translating to EnergyPlus spaces has been the default since 3.4.1. As far as I can tell we failed to highlight this in the release notes, but at this point it is in the past so I think we should move on. 

Please reopen if I'm missing some details that still need to be addressed.
