### ISSUE TITLE
The field !- External File Name gets deleted when using OS:Table:Lookup and OS:Table:IndependentVariable

### ISSUE THREAD

**Issue by Ski90Moo** [NREL/OpenStudio#5067]
Issue overview
--------------
The field !- External File Name gets deleted when using OS:Table:Lookup and OS:Table:IndependentVariable

https://unmethours.com/question/97826/tablelookup-external-file-name/

## Current Behavior
Edit the .osm file to include the external file name:
![Screenshot 2023-12-22 091003](https://github.com/NREL/OpenStudio/assets/69771412/148f9268-39ec-446d-8e1f-81a4d80d9432)

Open using the OpenStudio App and run the simulation.  The simulation fails and the reopening the .osm file reveals that the field was deleted:
![Screenshot 2023-12-22 091045](https://github.com/NREL/OpenStudio/assets/69771412/6fe6515a-72f9-43bd-b07f-129be377cd96)

## Steps to Reproduce

1.
2.
3.
4.

## Details
In addition, there are no details for where the .csv file should be placed such that EnergyPlus can access it.  The Input Output reference manual, Engineering manual, and SDK documentation does not indicate where the file should be placed.
### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
![Screenshot 2023-12-22 092014](https://github.com/NREL/OpenStudio/assets/69771412/e4797bac-bdeb-4159-8860-b155813facbf)

 - Version of OpenStudio (if using an intermediate build, include SHA):
![Screenshot 2023-12-22 092038](https://github.com/NREL/OpenStudio/assets/69771412/31c48a58-8846-4151-aa83-175b14fdadc5)

### Context
Unable to reference external csv file that contains custom heat pump performance curves.

**Comment by jmarrec** [comment]
The field is there as reserved for potential future implementation. There is no getter/setter for it, nor a constructor that accepts an ExternalFile, and that's because we didn't add this capability when we replaced Table:MultiVariableLookup with Table:Lookup / Table:IndependentVariable in https://github.com/NREL/OpenStudio/pull/4652.

As a result, editing the OSM file manually obviously isn't expected to work (and it would NOT work like this even if this was implemented, you'd be missing an OS:ExternalFile entry).

I didn't want to take the liberty to edit your post, so I'm closing this one and opening https://github.com/NREL/OpenStudio/issues/5077 to replace it
