### ISSUE TITLE
Release .zip Instead of .tar.gz for Windows

### ISSUE THREAD

**Issue by bonnema** [NREL/OpenStudio#5218]
Enhancement Request
--------------
Release .zip Instead of .tar.gz for Windows

## Detailed Description
A .zip would be more appropriate for Windows that a .tar.gz (e.g., natively supported)

## Possible Implementation
Is probably a configuration option

**Comment by bonnema** [comment]
Interesting. I did not know that. So maybe this issue should be to provide a .zip in addition to the .tar.gz?

**Comment by shorowit** [comment]
Personally, I don't think it's worth it. Note that [PeaZip](https://peazip.github.io/) is a nice free tool for Windows that can work with tar.gz.

**Comment by bonnema** [comment]
It might not be. I just found it odd, and I know many folks do not have administrative rights on their Windows computers. A .zip might come in handy in that case. Maybe it depends on the level of effort required to determined if it is worth it or not.

**Comment by jmarrec** [comment]
7-Zip is the de-facto standard on windows IMHO. 

And you already have the `tar` command on windows unless you use a **very** old windows 10 build. https://devblogs.microsoft.com/commandline/tar-and-curl-come-to-windows/

Open a prompt, `tar xfz my.tar.gz`. 

Anyone having problems with that can create zip themselves on another machine if they want.

Yes, it is easy to request a zip instead of a tar.gz (CPACK_BINARY_TGZ=OFF CPACK_BINARY_ZIP=ON), and but I actually like this is a tar.gz and not a zip, because when we consume it in other CI / github actions script, it's one less really annoying `if [[ "$RUNNER_OS" == "Windows"; then unzip -o my.zip; else tar xfz my.tar.gz, fi`
