### ISSUE TITLE
controller outdoorair object

### ISSUE THREAD

**Issue by loooic** [NREL/OpenStudio#5227]
I am using the openstudio package in python. I want to modify the object Controller:OutdoorAir object.

I want to put 'True' or 'Yes' for de field : 'High Humidity Control' and put the name of the zone for the field 'Humidistat Control Zone Name'.

To do this I do the following instructions :

controller_outdoorair = [CA for CA in openstudio.model.getControllerOutdoorAirs(osm)]

for index in range(len(controller_outdoorair)): 
      controller_outdoorair[index].setHighHumidityControl(True)

It works for the field 'High Humidity Control' but It seems that there is no function for the field 'Humidistat Control Zone Name'. The instruction 
controller_outdoorair[index].setHumidistatControlZoneName("Zone name") 
does not work.

I read the documentation here : [https://openstudio-sdk-documentation....](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.8.0-doc/model/html/classopenstudio_1_1model_1_1_controller_outdoor_air.html)

It sounds that the function to define the zone name does not exist.

Is it normal ?

Regards,

**Comment by joseph-robertson** [comment]
Indeed `setHumidistatControlZone(...)` is commented out and unavailable: https://github.com/NREL/OpenStudio/blob/develop/src/model/ControllerOutdoorAir.hpp#L111.

There is also no forward translation for this field: https://github.com/NREL/OpenStudio/blob/develop/src/energyplus/ForwardTranslator/ForwardTranslateControllerOutdoorAir.cpp#L143-L158.

I need to check whether this omission is intentional or not. The RT seems to suggest that it's intentionally not supported: https://github.com/NREL/OpenStudio/blob/develop/src/energyplus/ReverseTranslator/ReverseTranslateControllerOutdoorAir.cpp#L126-L129.

**Comment by jmarrec** [comment]
It's been commented out since the first commit, 11 years ago. 

https://github.com/NREL/OpenStudio/blob/c3a44f5d935a274d1d833323933d7df7f53e21dc/openstudiocore/src/model/ControllerOutdoorAir.hpp#L112-L113

This is very likely because the `ZoneControlHumidistat` was added only 10 years ago: https://github.com/NREL/OpenStudio/commit/fe0d5002754a51c763580c98911d237909a20a87

It stayed that way because no one requested it before.

**Comment by jmarrec** [comment]
https://bigladdersoftware.com/epx/docs/24-1/input-output-reference/group-controllers.html#field-humidistat-control-zone-name

> **Field: Humidistat Control Zone Name**

> This input defines the zone name where the humidistat is located. This is the same name used in the ZoneControl:Humidistat object. This field is required when the input field High Humidity Control is specified as Yes.
