### ISSUE TITLE
Openstudio 1.7 downloading BCL

### ISSUE THREAD

**Issue by AmirHossein503** [NREL/OpenStudio#5238]
Issue overview
--------------
Hello, I used last version of openstudio but when I want to download measure from BCL , it tell need newer version.
![11](https://github.com/user-attachments/assets/68a8227a-7a56-47c8-b1d1-38fa43c676f6)
![22](https://github.com/user-attachments/assets/75782535-89d4-4835-924e-a5a895e3ecc3)

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by mdahlhausen** [comment]
The [OpenStudio Application](https://github.com/openstudiocoalition/OpenStudioApplication/releases) is a separate code base. Version 1.7 of the OpenStudio Application uses OpenStudio v3.7.0.
The error you experienced is because those BCL measures have a minimum version requirement of OpenStudio v3.8.0, which requires a newer version of the OpenStudio Application. The OS App 1.8 [pre-release is available](https://github.com/openstudiocoalition/OpenStudioApplication/releases/tag/v1.8.0-rc3), which uses OpenStudio v3.8.0.

**Comment by jmarrec** [comment]
* This is strongly related to https://github.com/NREL/OpenStudio/issues/5230
