### ISSUE TITLE
Finding system swig [Build]

### ISSUE THREAD

**Issue by zwillikon** [NREL/OpenStudio#5276]
I'm trying to replace the [AUR binary](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openstudio) PKGBUILD with a new built-from-source recipe. Linking to system libraries is an ArchLinux goal. Running cmake on git master results in:

```
  Could not find a package configuration file provided by "SWIG" with any of
  the following names:

    SWIGConfig.cmake
    swig-config.cmake
```

ArchLinux's swig package has never contained any CMake config files for several versions.

Is [Conan-SWIG](https://github.com/conan-io/conan-center-index/tree/master/recipes/swig/all) nonstandard?

**Comment by jmarrec** [comment]
This is because of this line, which contains the `CONFIG` directive: https://github.com/NREL/OpenStudio/blob/cae94352f7d5ce2c44602dbda113fcb7bf085ab8/CMakeLists.txt#L444

I am not in the least familiar with AUR binaries or whatever, so I can't really help more than that.
Is patching an option for these builds? If so, try to remove the CONFIG bit?

Conan, when you run conan install is creating config files in your build directory to tweak a few things. 

Out of convenience, I'm providing a zip that contains the conan generated files for the machine I'm on, so you can have a look.

[SWIGConfigConan.zip](https://github.com/user-attachments/files/17570974/SWIGConfigConan.zip)

**Comment by jmarrec** [comment]
I'm closing this issue as this is something out of our scope, but I'm happy to keep chatting here if I can help.
