### ISSUE TITLE
support 4 nodes for WaterHeater:Mixed

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#5308]
While EnergyPlus allows for heat exchange using four nodes (two for the supply side and two for the use side), OpenStudio does not seem to support this setup for WaterHeater:Mixed.

@joseph-robertson can you confirm if this is a current limitation and if it would be possible to add this functionality to OpenStudio to match EnergyPlus capability for WaterHeater:MIxed?

**Comment by joseph-robertson** [comment]
@DavidGoldwasser You're talking about placing, for example, the WaterHeaterMixed on the demand side of one plant loop (source side) as well as on the supply side of another plant loop (use side)? I know we can do this with WaterHeaterStratified (e.g., as a storage tank), so I'd be surprised if we can't with WaterHeaterMixed. The FT for WaterHeaterMixed seems to imply the source side nodes get translated.

I feel like maybe this OpenStudio-resources test demonstrates connection to the source side? https://github.com/NREL/OpenStudio-resources/blob/develop/model/simulationtests/heatrecovery_chiller.rb#L70-L86

**Comment by BehnamMohseniGharyehsafa** [comment]
Hi @joseph-robertson

Kindly find the attached pictures, is it possible to develop such primary and secondary loops?

![photo_2024-11-18_16-10-29](https://github.com/user-attachments/assets/b61a175a-3f99-4dd7-90e4-9485513df163)
![photo_2024-11-18_16-11-36](https://github.com/user-attachments/assets/9d01eda2-f3e0-4b37-bf72-65b2feb3bf57)

Below is the screenshot of an empty Fluid-Fluid HeatExchanger item in OpenStudio in an empty HVAC system, where you can define the supply and demand node for the component:

![image](https://github.com/user-attachments/assets/682aa5c5-6034-4fd5-8e1c-2140c3ba0b46)

When I define the demand and supply side for the heat exchanger, it will automatically show the 4 branches.

But for the OS:WaterHeater:Mixed, there are no such things in the OpenStudio Application. 

I have formulated an OSM shown below:

![photo_2024-11-18_15-41-55](https://github.com/user-attachments/assets/c5e7124e-dcc2-4050-ab0b-4d4c85395053)
![photo_2024-11-18_15-48-31](https://github.com/user-attachments/assets/18679811-07a9-4979-9076-82539f71cd1d)

I am interested in modulating the charging and discharging of the tank. At some specific time, only charging, from the supply side (Node $\beta$ and Node $\alpha$) happens, and at another time discharging from Node 25 and 26 happens. 

I cannot find a place to define the supply side for the WaterHeater:Mixed component. I have attached my OSM for your reference for deeper investigation:

[behnam_simulation.zip](https://github.com/user-attachments/files/17926075/behnam_simulation.zip)


Would it be possible for you could modify the OSM, or refer me to an OSM example where such an idea in the first 2 attached pictures has been implemented? That would be great if I can see that the WaterHeater:Mixed in the HVAC Systems in the OpenStudio Application has 4 distinct branches. Is it possible to solve the challenge sustainably and robustly? I mean by defining such things as Heat Exchanger for the WaterHeater:Mixed.

**Comment by BehnamMohseniGharyehsafa** [comment]
@joseph-robertson 

Thank you very much for your attached example link, I can see that the WaterHeater:Mixed got four branches as like my Fluid-Fluid heat exchanger:
![image](https://github.com/user-attachments/assets/a87fa132-ae61-4d59-a72a-b638e0793b9f)

However I checked the details of the WaterHeater:Mixed in the OpenStudio Application, and there is no information about the Supply and Demand nodes. I guess the only option to have such a thing is **just** by **modifying** the **IDF**. Am I right?

If so, would it be possible to add this feature to the WaterHeater:Mixed for the OpenStudio Application?

This is because I am using LadyBug tools and they have a specific plug-in called IronBug. In this plug-in, they use OpenStudio systems to formulate detailed HVAC. For the HeatExchanger, since there is a specific section for the Supply and Demand Node in OpenStudio, they already integrated this feature in IronBug. But since there are no such things for the WaterHeater:Mixed, formulating the setup gets very challenging and requires directly modifying the IDF and this is not a very robust solution on a large scale for big buildings and communities, as you need to know the name of the nodes exactly. In IronBug, they have developed a methodology to bypass this challenge (but for the WaterHeater:Mixed they do not have this feature)
Kindly find the attached picture, where the HeatExchanger is defined in IronBug:

![image](https://github.com/user-attachments/assets/edc3ca5e-130b-4873-9e4f-aa63911d15c8)


Thank you very much for your time and assistance and I am looking forward to hearing from you soon.

**Comment by BehnamMohseniGharyehsafa** [comment]
@DavidGoldwasser 
@joseph-robertson 

Is it possible to develop such feature inside the OpenStudio Application, where you can specifically have demand and supply node (not in IDF and EnergyPlus mode)?

**Comment by DavidGoldwasser** [comment]
@BehnamMohseniGharyehsafa if the request is adding something to the OpenStudio SDK then this is the right placer for that. If it is exposing that capability in OS app, that is maintained by the OpenStudio Coalition, and is on this repo https://github.com/openstudiocoalition/OpenStudioApplication/issues

I haven't had chance to look through the thread enough to see if there is change needed to OpenStudio SDK?

**Comment by BehnamMohseniGharyehsafa** [comment]
@DavidGoldwasser, thank you for your message. I’ve just created a ticket on the OpenStudio Application issue forum on GitHub, which you can find here:


https://github.com/openstudiocoalition/OpenStudioApplication/issues/772

I would greatly appreciate it if you could kindly assist in addressing and resolving this issue. I have dedicated my entire Erasmus+ internship to defining a working package, but I am now at a standstill due to this challenge.

Your time, support, and assistance would mean a great deal to me in overcoming this roadblock. Thank you so much in advance for your help.

**Comment by BehnamMohseniGharyehsafa** [comment]
@DavidGoldwasser Could the modifications and enhancements be applied to the OpenStudio SDK or application?

**Comment by BehnamMohseniGharyehsafa** [comment]
@joseph-robertson Thank you very much for the example and the sent link

I drew inspiration from your example as well as an example shared with me by Dan Macumber. I also analyzed other OpenStudio examples, including one featuring a WaterStorage system connected to a solar collector. Upon review, I realized that the SDK and OpenStudio already had the required functionality. 

I reported the challenge to the Ladybug Tools developers, and I am pleased to share that the system is now fully operational.

@DavidGoldwasser I sincerely appreciate your time, support, and assistance.
