### ISSUE TITLE
Version translation is very slow

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#637]
Tested on old template files (circa 0.11.5)

**Comment by macumber** [comment]
Issues https://github.com/NREL/OpenStudio/issues/3146 and https://github.com/NREL/OpenStudio/issues/3501 are addressed by updating the libraries shipped with OS.  However, this issue needs to look at why this translation is so slow in the first place.  We need to do profiling and possibly refactor the way version translation works.

**Comment by joseph-robertson** [comment]
@lefticus Can you give us some profiling information?

**Comment by macumber** [comment]
Biggest issue is that you are having to load and parse like 30 idd files.  You should not have to load old idd files to do the version translation, you are basically just applying rules to text files until you get to the current version.

**Comment by lefticus** [comment]
@joseph-robertson can you give me a specific test to run that demonstrates the issue?

**Comment by lefticus** [comment]
@macumber 38 Idd files at least, it seems.

**Comment by lefticus** [comment]
# Intro

I look into Dan's comments on whether or not all of the IDD's need to be parsed. As far as I can tell, only the necessary IDD's are currently being parsed, based on the model file that is trying to be opened. I don't think there's anything further that can be done there.

I considered options like lazily loading only the pieces of the IDD that actually needed to be used for translation. There is some possibility there, but it would likely come at the cost of higher memory usage and complexity, with possible new multithreading issues.

On the topic of multithreading, I did also consider the idea of launching each parser in its own thread, so we could get some parallelization of the IDD parsing. That option is still on the table, and likely not a bad idea.

# Issues Found

After a few attempts at profiling and some failed attempts at fixing the speed of parsing IDD's I landed upon this one line of code:

https://github.com/NREL/OpenStudio/blob/develop/src/utilities/idd/IddObject.cpp#L639

```
while (boost::regex_search(copyText, matches, iddRegex::lastField())){
```

For the use case of a translation (I was using the ForwardTranslator_DemoModel_2012 unit test for my test case) that single line of code accounted for 40% of the runtime.

It turns out that the specific regex used in that line `(.*)([AN][0-9]+[\\s\\t]*[,;].*)$` is incredibly expensive with any regex library. It must greedily consume characters while looking for the pattern and backtracking to get the last possible Field.

I understand why it was implemented this way, because there is a field begin marker, but no way to know when a field has ended, so parsing back to front makes sense.

Furthermore, I noticed a considerable amount of time was being spent in the `to_lower_copy` and `trim` functions from boost. This is because they use the currently locale to properly find the whitespace and lower case versions of each character.

# Solution

## `lastField`

Instead of parsing back-to-front, I swapped the parsing to front-to-back. There is no end-of-field marker, but I can use the start of the next field to find the end of the current field.

From a pseudo code perspective this looks something like:

```
start = currentLocation
end = startOfNextField(currentLocation+1)
if (end == NotFound) end = endOfString
```

Result: ~2x faster parsing of IDDs

## `trim` and `to_lower_copy`

The IDD input files are guaranteed to be ASCII characters only. There should never been any Unicode or special characters in field names and IDD object types. To avoid the extra cost locale-aware operations I implemented my own functions:

 * `ascii_to_lower_copy`
 * `ascii_trim`

I then replaced all calls to the `boost` versions with my versions *in only the IDD parser*. We want to maintain correctness for other character encodings whenever possible.

# Final Result

Once the parsing and ascii functions where updated **I saw a net improvement of about 3x. That is, from 7.2s to about 2.4s to run the aforementioned `DemoModel` translator tests.**

This solution is very low (almost 0) risk. We can discuss further possible improvement with multithreading or further lazy-loading, of objects, which would be higher risk.

# Implementation

I actually implemented this 2 different ways. One with replacing boost::regex entirely with CTRE (compile-time-regular-expressions). 

Note: the current branch names are poorly done.

 * CTRE https://github.com/NREL/OpenStudio/tree/637_speedup_version_translation
 * Staying with Boost::Regex https://github.com/NREL/OpenStudio/tree/637_speedup_version_translation_new_parsing_method

CTRE
 * Likely faster compile times
 * Likely lower memory usage
 * Higher risk, if there is some unknown bug in regex handling, or if I broke something in conversion
 * Potential to fix the ThreadSanitizer errors we were getting in the Logger code, if I deploy it further inside of OpenStudio
 * Works with existing compilers, requires C++17

Boost::Regex
 * Very low risk
 * Much smaller set of code changes
 * Same or almost the same performance as CTRE for our use cases

re @joseph-robertson @kbenne

**Comment by lefticus** [comment]
After I get some feedback on the possibilities I'll make a proper PR.
