### ISSUE TITLE
Many objects in OpenStudio still appear to accept bad input values, but seems like it is just displaying the bad value and not storing it.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#656]
cc: @macumber 
Tested with 1.1.1 installer. Below are steps to reproduce.
1. Launch OpenStudio  app with empty model
2. Go to "Materials" sub-tab under "Constructions"
3. Make a new "Simple Glazing System Window Material"
4. Click in "U-factor" box and set value to 2 (make sure you are in IP units)
5. Tab to the next field

It looks like your U-Factor is set to 2. But if you do any of the three following things it goes back to its previous value (0).

A. Click in the U-Factor field again to activate it
B. Switch away from and then back to the material object.
C. Move focus on your computer away from the OpenStudio app (You don't even need to move focus back, in the background it reverts to 0.

One things is to confirm that this value should be constrained as it is. Seems to top off between 1.2 and 1.3. 
(I did confirm that IDF Editor has this limit. 1.232 or 7 if in SI (W/m2-K)

The second is to improve the behavior to not allow you to enter an invalid value. It should either show you an error dialog, or just set it to the max value, or something else, but it should never appear to accept the bad value. @nllong and I had switched away thinking I had set it to 2, to find it was still really 1.

I expect there is a similar behavior for other number input fields throughout OpenStudio App? (Confirmed. See same behavior trying a negative Lighting power value for lights definition.)

**Comment by macumber** [comment]
I just re-confirmed this but the behavior of when it changes back seems to be different now, changing focus does not seem to do this for me, clicking on the another field does not, clicking on a second field does.

Gridview seems to have a similar problem, however in grid view you do not see the problem until you change tabs and go back, clicking on other fields does not cause the error to revert.  We should be checking the return value of setter methods, if they return false we should refresh the field.

**Comment by macumber** [comment]
Increasing priority due to user report

**Comment by mbadams5** [comment]
@macumber @kbenne could this be related to #945? 

And more specifically the following line which was the problem in #945.

https://github.com/NREL/OpenStudio/blob/da05779942b7a00ea3cbcb482c7ac31c0869c46b/openstudiocore/src/model_editor/InspectorGadget.cpp#L647

**Comment by macumber** [comment]
For space load instances, the multiplier has a minimum of 0. I noticed that I can enter in a negative number in the multiplier field in grid view for loads in a space type. Number appears to stick but gets cleared when I switch tabs and come back,

**Comment by macumber** [comment]
@evanweaver you still working on this for 1.7.0?

**Comment by evanweaver** [comment]
@macumber I think that this ticket is fairly risky and somewhat involved.  For the newer, second generation of data display widgets, osconcept classes will need to be extended to allow provisions for setting min and max settings.  In turn, any IDD min and maxes will need to be provided at widget creation.

A additional approach would be to attempt to set a widget's a new value in model, check for success, and rollback to the widget's original value more quickly in the workflow than is currently done.

I have also derived validators to attempt to disallow a null string entry, but the way QWidgets update, this type of validator made it more than cumbersome to change the widget's existing data.

That said, have added appropriate validators (ex: QIntValidator to OSIntegerEdit) which helps quite a bit.

Finally, since this bug has existed since the inception of the OS data display widgets 4 years ago, and since the risk seems high to fit it in to 1.7, I vote we wait.

**Comment by DavidGoldwasser** [comment]
@evanweaver and @macumber I'm fine waiting on this, It is known issue with easy work around.

**Comment by evanweaver** [comment]
As tested in 2.4.0, this has been fixed. Typing in "2" (as described at the top) and leaving the cell results in the value being reset to the original, valid value.
