### ISSUE TITLE
Water use equipment does not show up in facility tree under space

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#884]
@asparke2 @DavidGoldwasser FYI

relates to https://github.com/NREL/OpenStudio/issues/825

**Comment by macumber** [comment]
@kbenne @DavidGoldwasser @asparke2 

What is the right thing to do here?  Do we want to deprecate water use equipment?

**Comment by macumber** [comment]
Sorry, I was thinking of [HotWaterEquipment](http://bigladdersoftware.com/epx/docs/8-1/input-output-reference/page-015.html#hotwaterequipment), not sure what the status of that is.

However, for WaterUseEquipment, should it be shown in this tree?

**Comment by asparke2** [comment]
@macumber yes, WaterUseEquipment should be shown in the tree under a space if it is indeed assigned to a space (like all the other SpaceLoadInstances).  This is something that should/will be covered in Marj's redesign of the facility tab.  WaterUseEquipment is tricky since it doesn't need to be assigned to a particular space to be valid in the model.   Since you can always get to all WaterUseEquipment (whether assigned to a space or not) from the HVAC>Service Water Heating>Water Use Connection objects, I don't think this bug is worth looking at until the facility tab redesign.

**Comment by evanweaver** [comment]
No longer valid.
