### ISSUE TITLE
Allow shared thermostats

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#985]
This is just the nature of how we made the new templates. isn't just an issue of having a long pulldown list. In the past there was a thermostat named something like "hotel general" one named "kitchen" and another named "corr_lobby_retail" or something like that.

I could assign thermostats to the entire building in three steps. Users now need to assign unique thermostats for every space type because they don't know that many of them are really the same. I guess this will be fixed when we make a wizard.

One thought I have is to just not do this in the plugin with space attributes and write a measure for OS app to assign thermostats based thermostatName = "#{space.name} Thermostat"

Still not a very clean solution. If only the preferred heating and cooling schedule for a space type could be stored in the space type object :)

**Comment by DavidGoldwasser** [comment]
Solution will be to change thermostat in plugin so will be unique for every thermal zone. Then they will behave as expected in GUI. Will try to fix existing models in version translation.

**Comment by aaron-boranian** [comment]
Allow shared thermostats

Problem: In the past, one could assign thermostats to the entire building in three steps. However, now users now need to assign unique thermostats for every space type because they don’t know that many of them are really the same. I guess this will be fixed when we make a wizard.

Solution: Write a measure for OS App to assign thermostats based on thermostatName = “#{space.name} Thermostat”

Migrated from [UserVoice](http://openstudio.uservoice.com/forums/308629/suggestions/9099544)
